### ISSUE TITLE
Admin sign in

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#1]
Admin is not getting accessed
![image](https://user-images.githubusercontent.com/85341053/129680273-5faa7a19-f288-4e3a-8a06-df41f58ca7dc.png)

**Comment by technicalbirdVayuz** [comment]
Fixed
![image](https://user-images.githubusercontent.com/18699624/129859146-459ec1a7-e5e1-437e-b0ec-198937568973.png)
