### ISSUE TITLE
Athlete > Notifications > There are only only one Notification, but it's showing 11

### ISSUE THREAD

**Issue by Arushi1390** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#10]
![Screenshot (640)](https://user-images.githubusercontent.com/88670762/129689088-0795ae0c-30d4-42c4-94e6-de3613bd9a12.png)

**Comment by technicalbirdVayuz** [comment]
Renamed to Notifications. 
![image](https://user-images.githubusercontent.com/18699624/129878899-7b388494-20d7-4323-a60b-f932ad49624f.png)
