### ISSUE TITLE
Coach Sign up >> Other >> complete coach profile

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#11]
Follow this doc for the changes
https://docs.google.com/document/d/1V0ybKFsAN7aZemRD7VkiYtXXu_DU89bylYMajpWXYyo/edit?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Is it additional, as its not mentioned in the original doc?

**Comment by rgnarok** [comment]
Check this 
![image](https://user-images.githubusercontent.com/85341053/130051706-8561c9e7-b390-4844-b303-e79e662197ca.png)

**Comment by technicalbirdVayuz** [comment]
@rgnarok This is additional work for us. We will not work on the same until & unless additional marked on the same. Will share the additional hours else let me know if we need to revert back the modules as they are not mentioned in the documentation as they should.

**Comment by rgnarok** [comment]
@technicalbirdVayuz  had a call with Steve we can put this on hold for now and will do it in the future build if required.

**Comment by technicalbirdVayuz** [comment]
Closing this then
