### ISSUE TITLE
Change Images on the - Select Profile Type to the USA images from homepage 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#113]
Change Athlete, Coach, Retired and Referee Images.  Leave Organization image the same
![5_28_19_Annie_Drews_Attacks_vs_SRB2b](https://user-images.githubusercontent.com/77851393/132143073-68cd243e-6e4d-4d92-8ad6-f625b104bfdd.jpg)
![ref](https://user-images.githubusercontent.com/77851393/132143078-8d380fda-57e1-469d-bf89-6efb46a84df9.jpg)
![maxresdefault](https://user-images.githubusercontent.com/77851393/132143123-cfca2b1f-0476-418e-995a-f343d01c1246.jpg)
<img width="249" alt="coach" src="https://user-images.githubusercontent.com/77851393/132143151-fdd6c996-382d-4b5f-9bca-072b6382923f.png">

**Comment by vayuzpriya** [comment]
Fixed
