### ISSUE TITLE
Admin >> add college

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#116]
![image](https://user-images.githubusercontent.com/85341053/132185012-9fd5e4b1-1ce6-4262-a2db-269226c3b367.png)
Change institution to college

**Comment by technicalbirdVayuz** [comment]
This form should enable for college only. For rest of the ASsociation types, its not required. Let me know if this needs to be skipped in case of associations other than College. In that case, it will be directly created from the first page itself

**Comment by technicalbirdVayuz** [comment]
> This form should enable for college only. For rest of the ASsociation types, its not required. Let me know if this needs to be skipped in case of associations other than College. In that case, it will be directly created from the first page itself

@rgnarok
