### ISSUE TITLE
Chnage Parent Email after athelte signup to USA 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#120]
Please change message to below 

Hi Parent(s)/ Guardian(s) of Jenna Arch,

 

We would like to inform you that Jenna Arch has signed up for a free account at Volleyball Unite - **North America's** Premier Volleyball Network!!

 

Volleyball Unite is a safe and secure platform for aspiring athletes, coaches, referees, and associations to socialize, share valuable volleyball information, and create connections.  

The volleyball profile does not contain any contact information (i.e. email, address, or phone number. The only people who can view Jenna’s profile are verified premium coaches and those that Jenna has agreed to connect with on the platform.  

 

Our Mission

 

"Every volleyball athlete in North America should have an opportunity to be recruited to Clubs and Colleges.."

 

Please review our Terms of Reference and Privacy Policy for more information.  

If you have any questions or concerns please feel free to contact us at info@volleyballunite.com

Regards,

Volleyball Unite

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by rgnarok** [comment]
Email not coming up
arushi12@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
@rgnarok It would depend on the DOB, as per the shared creds, DOB of an athlete is in 2000, It should be less than 18 yrs only then mail would be received
