### ISSUE TITLE
Athlete Verification 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#121]
Athlete Verification process is not working.  I signed up with Jenna Arch (jennaarch@mailinator.com) and password Volleyball11$

There is nowhere that it tells me to become "verified".

Please add the following notification when an athlete signs up in addition to the notification to complete their profile:

"Get verified athlete status by having a coach on the VU network "Verify" you. (put a green checkmark here).   Send a request to any coach on VU to verify.

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/132507662-9e31b07f-84db-487d-a7fd-2479784f6cf0.png)
Modified the text a bit. Let me know if needs a change

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/133255167-06aaec66-e2f2-4a69-a6c8-814348a5f71f.png)
@technicalbirdVayuz No notification

**Comment by technicalbirdVayuz** [comment]
Pls check again, code was not made live for this I guess

**Comment by technicalbirdVayuz** [comment]
Pls, check for reported issues only. If there is any other issue then please report it as a new one. It becomes difficult to manage if we mix issues.

I hope this would not be a problem, So closing this
