### ISSUE TITLE
Verification Badge 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#123]
Once an athlete and coach get verified they need to have a green checkmark badge.  Then when they go premium it turns to blue

**Comment by technicalbirdVayuz** [comment]
@rgnarok  please discuss this as athletes can. directly go premium that should not create a conflict. Also, making it one badge would provide no surety that he is verified also.

**Comment by stevekamps** [comment]
An athlete or coach should need to be verified before they can go premium.  Please keep the premium list if an unverified athlete or coach goes to see what premium features they get.  Then when they click on "Go Premium" have a message pop up that says.....

"You need to be verified before you can purchase a premium membership.  Get verified coach status by having an organization (College, Club, School) on the VU network "Verify" you. (put a green checkmark here). Send a request to any Organization on VU to verify."

Or if an athlete....... "You need to be verified before you can purchase a premium membership.  Get verified athlete status by having a coach on the VU network "Verify" you. (put a green checkmark here).

**Comment by stevekamps** [comment]
An athlete or coach should need to be verified before they can go premium.  **I would like the ability for an athlete to go premium without being verified.**   **A Coach needs to be verified as this becomes a safety issue.**

Please keep the premium list if an unverified athlete or coach goes to see what premium features they get.,

How you want to see them on Admin Panel or any mail trigger. Please discuss with @rgnarok. We will then take this forward
Then when they click on "Go Premium" have a message pop up that says....

Popup messages configured

**Comment by technicalbirdVayuz** [comment]
#185

**Comment by stevekamps** [comment]
Refer to issue #185
