### ISSUE TITLE
Athlete Verification

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#125]
For the notification that a coach receives from a requested athlete please change message to:

"NAME" has requested a profile verification. "Click here" to verify that they are an athlete

"NAME" (ATHLETE) has requested a profile verification. "ACCEPT"

**Comment by technicalbirdVayuz** [comment]
Changed to 1st or 2nd?

**Comment by stevekamps** [comment]
Both of these notifications occur.  the first one appears and then when you click on verify the second message appears and then they can "accept"
Please change the wording to above

**Comment by technicalbirdVayuz** [comment]
@rgnarok Can you discuss this on your next call with @stevekamps ?

**Comment by stevekamps** [comment]
Verification process is not working at all on my end

**Comment by stevekamps** [comment]
It is not working for any athlete that gets created 

myajones@mailinator.com
Volleyball11$

**Comment by technicalbirdVayuz** [comment]
@rgnarok  I reviewed it again its working, Please review at your end also

**Comment by stevekamps** [comment]
OK that makes sense.  The issue I am having is that the coach verification is not working.  So I can't test the new atheltes and new coaches that I am creating.
