### ISSUE TITLE
Remove Request Verification badge once verfied

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#126]
Remove "Request Verification" badge once a coach or athlete is verified

**Comment by technicalbirdVayuz** [comment]
Please share the credentials, as per the changes there already it should not be visible once profile is verified

**Comment by stevekamps** [comment]
tomsmith@mailinator.com
Volleyball11$

He is verified by High School ABC but does not have a green badge and all other organizations still have the "Request Verification " badge appearing

**Comment by technicalbirdVayuz** [comment]
Green Badge will be configured across the platform, pls confirm whether the request verification button is coming now on Search or not. Made the required changes
