### ISSUE TITLE
Move the "League" text field in athlete College search to below Conference rather than at the top of list 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#127]

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/132501602-ee913b22-905b-4de2-acf6-b8559faebfe5.png)
League text field is already below Conference. 

Please mention the order to clarify the same

**Comment by stevekamps** [comment]
Sorry I meant Move the COnference below the region.

**Comment by technicalbirdVayuz** [comment]
Ok. @stevekamps Just one request when you shared the inputs & the thread is having **required more inputs** tag, please remove it. It becomes easy for us to filter

**Comment by technicalbirdVayuz** [comment]
Fixed
