### ISSUE TITLE
Club Admin Email

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#129]
When an athlete signs up as a school/club athlete and their club is not listed the club admin email template needs to be changed.  Please change to the text below.

Hello Volleyball Club Administrator,

 
One of your athletes has joined the Volleyball Unite community and wants to list their affiliation with your club to build their online volleyball portfolio.

What is Volleyball Unite?

We are North America'ss premier inclusive volleyball recruiting network enabling the entire volleyball community to UNITE and share valuable information.

 
Why Volleyball Unite for Clubs?

As the club administrator, you can create a free club page on our platform in under 5 minutes. The club page can be used to showcase your club, teams, and athletes. Post success stories and push mass communication to all of your followers on the platform.

 
Your athletes and coaches will enjoy the many features of Volleyball Unite including:

 Connect with other athletes and coaches
 Follow Clubs and Institutions
 Create dynamic posts to share with connections and followers
 Create groups to communicate with team on mobile apps
 Create events and sync with phone calendar
 Create Blogs to draw more followers to your club
 List signed and selected athletes
 And much more
 

We are Volleyball Unite and we are creating a whole new ball game.

To create your free club page please click here for Sign up

 

 

If you have any questions please don’t hesitate to contact us at info@volleyballunite.com

 
Regards,

Volleyball Unite

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/133247948-29289166-7e31-4c05-8187-53df985ddd21.png)
Not able to check as this is not giving an option to add administrator email

**Comment by technicalbirdVayuz** [comment]
> ![image](https://user-images.githubusercontent.com/85341053/133247948-29289166-7e31-4c05-8187-53df985ddd21.png)
> Not able to check as this is not giving an option to add administrator email

#193

**Comment by technicalbirdVayuz** [comment]
> When an athlete signs up as a school/club athlete and their club is not listed the club admin email template needs to be changed. Please change to the text below.
> 
> Hello Volleyball Club Administrator,
> 
> One of your athletes has joined the Volleyball Unite community and wants to list their affiliation with your club to build their online volleyball portfolio.
> 
> What is Volleyball Unite?
> 
> We are North America'ss premier inclusive volleyball recruiting network enabling the entire volleyball community to UNITE and share valuable information.
> 
> Why Volleyball Unite for Clubs?
> 
> As the club administrator, you can create a free club page on our platform in under 5 minutes. The club page can be used to showcase your club, teams, and athletes. Post success stories and push mass communication to all of your followers on the platform.
> 
> Your athletes and coaches will enjoy the many features of Volleyball Unite including:
> 
> Connect with other athletes and coaches
> Follow Clubs and Institutions
> Create dynamic posts to share with connections and followers
> Create groups to communicate with team on mobile apps
> Create events and sync with phone calendar
> Create Blogs to draw more followers to your club
> List signed and selected athletes
> And much more
> 
> We are Volleyball Unite and we are creating a whole new ball game.
> 
> To create your free club page please click here for Sign up
> 
> If you have any questions please don’t hesitate to contact us at [info@volleyballunite.com](mailto:info@volleyballunite.com)
> 
> Regards,
> 
> Volleyball Unite

Done!

**Comment by stevekamps** [comment]
when you choose club not listed it asks for club admin email.  When I enter an email the club admin does not receive the email to join VU
