### ISSUE TITLE
Athlete > Unite >Correct the line " No unite request received"

### ISSUE THREAD

**Issue by Arushi1390** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#13]
![Screenshot (641)](https://user-images.githubusercontent.com/88670762/129691007-465c72a3-e292-479e-9c32-087fb2e93c3c.png)

**Comment by technicalbirdVayuz** [comment]
Fixed.

**Comment by rgnarok** [comment]
UI need fixing
![image](https://user-images.githubusercontent.com/85341053/130616868-e15d93f4-6a2c-4a19-8142-155512f629a6.png)

**Comment by vayuzpriya** [comment]
Fixed
