### ISSUE TITLE
Coach - Premium

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#131]
Search filter and Virtual Bench not showing up for high school coach

tomsmith@mailinator.com
Volleyball11$

**Comment by technicalbirdVayuz** [comment]
Its working, Please share the section where it is not visible
![image](https://user-images.githubusercontent.com/18699624/132814216-dd7055c5-21aa-4182-9631-3bc298b668e4.png)

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please discuss this, it was not there in the requirement earlier

**Comment by stevekamps** [comment]
Correct.  I don't want high school coaches being able to search for athletes.  I need to change the premium language for high school coaches
