### ISSUE TITLE
Club Signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#133]
New club created 
clubabc@mailinator.com
Volleyball11$

The club has the search filters and virtual bench activated and they are not premium.

**Comment by technicalbirdVayuz** [comment]
The search filter is activated only for the first 3 use, & Virtual bench is there for prompting users to go for premium

![image](https://user-images.githubusercontent.com/18699624/132814712-8ef236bc-0882-4f59-af38-28f50ae6ffe6.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/132814786-1997aafb-6032-4b08-92da-9fc05cc380f4.png)

![image](https://user-images.githubusercontent.com/18699624/132814828-54c88070-568e-4bd8-b207-53b9d6a8b90e.png)
