### ISSUE TITLE
Remove University from Athlete Type choices

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#138]
In the USA we only use the word College

**Comment by technicalbirdVayuz** [comment]
College is also there, Removing university would remove the flow also associated with it. Please confirm

![image](https://user-images.githubusercontent.com/18699624/134162442-b5cc2eaa-cb3a-4946-8840-9a4c702621d9.png)

**Comment by stevekamps** [comment]
remove University please.  We only need College in the USA as that is what all schools refer to themselves as
