### ISSUE TITLE
CLUB - Incorrect message on search filter 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#141]
For a club the search filter message is not the correct message for a non-premium club. The message that appears is the non-premium message for athletes searching for Colleges

**Comment by technicalbirdVayuz** [comment]
Would be great if you could share the message

**Comment by stevekamps** [comment]
remove search filters for club, association and school.  Only required for College Organization

**Comment by technicalbirdVayuz** [comment]
Fixed, pls check
