### ISSUE TITLE
College athelte signup - Notification

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#143]
Halleyjones@mailinator.com
Volleyball11$

When I created this athlete she had an immediate notification that says 
Thanks for purchasing. Your account is upgraded to a premium account.

She is not premium in the dashboard and she is not premium while logged in

**Comment by stevekamps** [comment]
Same notification occurred for a Club coach signup 
glendavis@mailinator.com
Volleyball11$

**Comment by technicalbirdVayuz** [comment]
this has been fixed yesterday

**Comment by stevekamps** [comment]
OK if it is fixed then please close
