### ISSUE TITLE
Change Images in Dashboard to USA images

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#148]
Change Images in Dashboard to USA images.

Athlete, Coach, Referee, Retired images. Change to USA images

**Comment by vayuzpriya** [comment]
Where do we need to change? @rgnarok

**Comment by stevekamps** [comment]
![image](https://user-images.githubusercontent.com/77851393/133695312-af5c18d8-801f-49d7-898b-476477693ac6.png)

**Comment by vayuzpriya** [comment]
Fixed
