### ISSUE TITLE
Events -  Text 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#150]
For Coach Events please change the text to the following:

Public (Visible to United Connections)
Private (Invited Connections)

Then for Organizations (Club, School, College) events change to: 
Public (Visible to Followers)

- Does this go to all followers feeds? 
-

**Comment by technicalbirdVayuz** [comment]
Does this go to all followers feeds?
- Yes
