### ISSUE TITLE
Add the Following Description When Virtual Bench Window Opens for Premium 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#152]
Add future prospects to your Virtual Bench to follow their development.  This is a private list that nobody else can see.  The athlete will get notified that you have added them to your Virtual Bench.

**Comment by technicalbirdVayuz** [comment]
@vayuzpriya  please create a layout for adding the description

**Comment by vayuzpriya** [comment]
@technicalbirdVayuz  @rgnarok  Pls connect with me for this.

**Comment by vayuzpriya** [comment]
![Screenshot from 2021-10-05 11-44-05](https://user-images.githubusercontent.com/81085431/135970174-b65979f2-5327-4bd6-9e65-9917fa1dee53.png)
@rgnarok @stevekamps @technicalbirdVayuz 
Please check
