### ISSUE TITLE
Website - Links 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#155]
Please link all buttons to the "Launching soon page".  The download app buttons need to send people to the launching soon page as well.  The Join Now button on safari does not send a user to the launching soon page

**Comment by technicalbirdVayuz** [comment]
Please link all buttons to the "Launching soon page". 
The download app buttons need to send people to the launching soon page as well. 
- Download Apps from respective stores linked to Coming soon page
The Join Now button on safari does not send a user to the launching soon page
- Its working fine, Can you share the screen capture video for this?

**Comment by stevekamps** [comment]
Join NOw and Download App button do not hyperlink to the coming soon page

https://user-images.githubusercontent.com/77851393/133790429-805337cc-84fa-49fd-bc01-d20e0d5f02f6.MP4

**Comment by stevekamps** [comment]
The join Now shoots to bottom of screen

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/133790546-3a409abf-8ba7-4a6b-ba62-3dbd9a29982c.MP4

**Comment by stevekamps** [comment]
download app button does not hyperlink

**Comment by technicalbirdVayuz** [comment]
Fixed on hEroku

**Comment by stevekamps** [comment]
OK Please fix on volleyballunite.com

**Comment by technicalbirdVayuz** [comment]
Done
