### ISSUE TITLE
Website - Athlete, Coach, Organization, Referee, Retired links not working 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#156]
Website - Athlete, Coach, Organization, Referee, Retired links not working on cell phone view (safari or chrome)

**Comment by technicalbirdVayuz** [comment]
It's working as expected, please share the screen capture video if possible

**Comment by technicalbirdVayuz** [comment]
https://user-images.githubusercontent.com/18699624/133743876-864417a2-5353-40f5-b4d0-d82fea9ed4f1.mov

https://user-images.githubusercontent.com/18699624/133743889-fa7515e6-b635-432b-b68b-4bee76e466c5.mov

**Comment by technicalbirdVayuz** [comment]
https://user-images.githubusercontent.com/18699624/133744451-805ca3b6-6d4c-4e93-afa8-f2d1c906fc7a.mp4

Pls check

**Comment by technicalbirdVayuz** [comment]
Also, working on Cell phone. checked on Chrome

**Comment by stevekamps** [comment]
They are working now but the autoscroll needs to stop when you click on them.  It is also jumping all ove

https://user-images.githubusercontent.com/77851393/133790777-25fda7a0-c2ad-4c37-9009-97dde3b80262.MP4

r

**Comment by technicalbirdVayuz** [comment]
Autoscroll fixed. #195
