### ISSUE TITLE
Website - Move text in footer

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#157]
In Cell phone view please move "Volleyball Unite 2021. All Rights reserved. to the bottom of the footer. We want the social media icons to be on the top of the footer

**Comment by technicalbirdVayuz** [comment]
![Uploading image.png…]()
Fixed

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/133743440-639688f3-8837-4ed0-88ac-03592080888d.png)

**Comment by technicalbirdVayuz** [comment]
![Uploading image.png…]()
Website

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/133744238-d1951502-4511-4e58-a387-392df5299327.png)
