### ISSUE TITLE
Add a autoscroll to the website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#158]
Add a autoscroll to the website - Have the homepage autoscroll (every 4 seconds) through the Athlete, Coach, Organizations, Referee, and Retired

**Comment by technicalbirdVayuz** [comment]
Fixed.

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/133789665-aa91ae5a-7a3f-4c22-ad7f-1690f5d5258a.MP4

clicking on one of the users needs to stop the scrolling

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/133789773-365e0f27-d3fc-44fe-9893-6b2a703ea5a9.MP4

Scrolling is jumping all over the place.  When you first go to the website and stay at the top of the website it will all of a sudden shoot you down to this section

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/133789924-23262849-d1e3-4b10-b455-e5eb6ee279b0.MP4

**Comment by stevekamps** [comment]
Please remove the auto scroll feature for athlete, coach, organizations etc.   It is too busy

**Comment by technicalbirdVayuz** [comment]
Removed

**Comment by technicalbirdVayuz** [comment]
#195
