### ISSUE TITLE
Athlete > Unite > Withdraw request - Change the model text to - Sure, you want to withdraw the request?

### ISSUE THREAD

**Issue by Arushi1390** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#16]
![Screenshot (643)](https://user-images.githubusercontent.com/88670762/129691675-095d3e4a-2f7b-465d-8daa-bb5f074bef21.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129881853-c2b0b6a7-99c7-45bc-bfdc-fb33d752dd22.png)
Fixed
