### ISSUE TITLE
Remove the period from the end of the Organization description.

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#164]
Remove the period from the end of the Organization description in signup process

**Comment by technicalbirdVayuz** [comment]
Can you share the screenshot for the screen? you are referreing to?

**Comment by stevekamps** [comment]
![image](https://user-images.githubusercontent.com/77851393/134216748-c78f6326-f082-43f9-9b1d-56d2eb3a8284.png)

**Comment by stevekamps** [comment]
remove period in organization description
