### ISSUE TITLE
Remove Virtual Bench and Search Filter Icon for School & Club type 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#169]
Remove Virtual Bench and Search Filter Icon for School, Club, and Association Organization types

**Comment by stevekamps** [comment]
We do not want the ability for a club or high school page/administrator to be able to use  advanced search filter or virtual bench.  Please remove them

**Comment by technicalbirdVayuz** [comment]
@rgnarok  please discuss this
