### ISSUE TITLE
Successful registration message for coach, athlete, referee, retired

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#183]
Change Great to "Welcome to Volleyball Unite!!"

**Comment by technicalbirdVayuz** [comment]
Suggestion is to change it to Congrats, "Welcome to Volleyball Unite" is a long message, would not look good on Mobile

**Comment by stevekamps** [comment]
Make fonts smaller and say "Welcome to VU!!"  

This would look fine on the cell phone screen and would fit on 1 line.  See attached

**Comment by stevekamps** [comment]
![Screenshot 2021-09-21 at 10 45 22 AM](https://user-images.githubusercontent.com/77851393/134212943-526b417f-31a2-4993-b255-3750fc2b15da.png)

**Comment by technicalbirdVayuz** [comment]
Text changed, @vayuzpriya pls check for UI

**Comment by vayuzpriya** [comment]
FIXED
