### ISSUE TITLE
Coach Verification Process Not working 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#187]
Coach Verification Process Not working 

- No verification request badge is appearing on any organization

**Comment by stevekamps** [comment]
Athletes don't have the option to send a verification request to coaches.

**Comment by technicalbirdVayuz** [comment]
@rgnarok  Can you connect with @stevekamps for this?

**Comment by stevekamps** [comment]
This is not working
