### ISSUE TITLE
Coach >> Event >> Create event

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#19]
Banner image not getting upload
![image](https://user-images.githubusercontent.com/85341053/129693743-38151467-5e63-4a8d-b652-5f4704db4f86.png)

**Comment by technicalbirdVayuz** [comment]
Please try again or share the exact test case. Tried the same procedure, its working

**Comment by rgnarok** [comment]
Working now please close
