### ISSUE TITLE
Website Jumps down to the middle

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#199]
Website Jumps down to the middle of the page without touching anything.

**Comment by technicalbirdVayuz** [comment]
Should we remove auto-scroll then?

https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/issues/158

**Comment by stevekamps** [comment]
We want the autoscroll on for Feed, Evetns, Groups etc.  just like the VU Canada page. 

But please remove the autoscroll for the Athetle, Coach, Organization etc section.

Currently when I go the website it automatically jumps down to the middle fo the webpage

**Comment by technicalbirdVayuz** [comment]
Removed Autoscroll
