### ISSUE TITLE
The Event end date calendar is giving option to old dates Coach >> Event >> Create/Edit 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#20]
The Event end date calendar is giving option to old dates 
![image](https://user-images.githubusercontent.com/85341053/129694117-73080156-ce7a-489f-a6eb-e659e5856413.png)

**Comment by technicalbirdVayuz** [comment]
Please clarify these 2 pointers,
1. Do you need dates in **to date** calendar to starts after 18 Aug if in from date 18th Aug is selected i.e dynamic end date handling
2. You need dates in the **to date** calendar to starts from the least of today's date (the date individual is creating the event)

**Comment by rgnarok** [comment]
1 is good

**Comment by technicalbirdVayuz** [comment]
That's the question, if you reported this considering 1st in mind then that can't be done. Library does not provide option to dynamically change start date

**Comment by rgnarok** [comment]
Make it 2 then

**Comment by technicalbirdVayuz** [comment]
Ok Done
