### ISSUE TITLE
USA Website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#202]
Please make the following changes to USA website:
1. Please make the flags centered under Join Now on Cell phone view (Issue #201)
2. Please link the Youtube to the USA youtube link: https://www.youtube.com/channel/UCIb1c9KMW0Nr1a1zt3KfOyw
3. Website - Change Privacy Policy and Terms of Conditions
Change from Volleyball Unite Recruiting Ltd. to "Amateur Sports Unite LLC" (Issue #200)
4. Make sure Contact Us Email is working and gets delivered to info@volleyballunite.com
5

**Comment by vayuzpriya** [comment]
Please make the flags centered under Join Now on Cell phone view (Issue Website #201)
Please link the Youtube to the USA youtube link: https://www.youtube.com/channel/UCIb1c9KMW0Nr1a1zt3KfOyw
Website - Change Privacy Policy and Terms of Conditions
Change from Volleyball Unite Recruiting Ltd. to "Amateur Sports Unite LLC" (Issue Website - Change Privacy Policy and Terms of Conditions #200)
 **these issues fixed**
