### ISSUE TITLE
Homepage changes both on VU USA and canada

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#215]
1.  We want the top slogan to say 
a) Canada's Premier Volleyball Community
b) North America's Premier Volleyball Community 

2. IN the middle red section of .ca and .com sites please remove the word recruiting and also remove the last paragraph (see attached). Please capitalize the "P" on Premier

3.  For athlete description point number 1 for both .ca and .com please change the first bullet point to the following:
Create your FREE Volleyball Profile

**Comment by technicalbirdVayuz** [comment]
it was fixed
