### ISSUE TITLE
Coach/Athlete/ Organisation >> Event listing

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#22]
Change the title from recurring to recurring today
![image](https://user-images.githubusercontent.com/85341053/129695173-effbc42b-848c-4bc4-9010-39c93ba05f7d.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129883070-5ef1ad87-1e8b-45a8-95f2-e4612adf5a16.png)
Done
