### ISSUE TITLE
Athlete

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#220]
Remove virtual bench and change it to wishlist

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by rgnarok** [comment]
Text is incorrect it is coming wishlisted users it should be wishlist

**Comment by technicalbirdVayuz** [comment]
![screenshot-2021-11-16_15 13 44 603](https://user-images.githubusercontent.com/18699624/141961339-75582144-70c9-4b0e-af57-29afb62296f2.png)
