### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#222]
Image and cover images of the users are not coming up not the deafult one too

**Comment by technicalbirdVayuz** [comment]
Can you share the screenshot also

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/141608664-ee9abe1d-433d-4ada-9d69-724c07adb5a5.png)

**Comment by technicalbirdVayuz** [comment]
Made modifications in the server APIs for the Default Images, Cover images also fixed

**Comment by rgnarok** [comment]
Default image reflection in search for users who has not updated

**Comment by technicalbirdVayuz** [comment]
Fixed. please check for new users.
