### ISSUE TITLE
Athlete verification request

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#227]
No option coming up to request a coach to verify from search connection and profile not coming up
Also there is no option to see whether the coach is verified or not

**Comment by technicalbirdVayuz** [comment]
No option coming up to request a coach to verify from search connection and profile not coming up
- Have you clicked on the 3 dots?
Also there is no option to see whether the coach is verified or not (this has not been added for now) will add

ALso, pls share the user creds

**Comment by rgnarok** [comment]
Creds: kush41@mailinator.com, Kush96agra@
Also shouldn't we have the same view as we have for the web like giving the option to request verification

**Comment by technicalbirdVayuz** [comment]
**Request Verifcation** button text is itself is too long &  cannot be adjusted in the cards. that's why 3 added in 3 dots. 

Also there is no option to see whether the coach is verified or not - Added

Corrected the flow, Please check in the upcoming build

**Comment by rgnarok** [comment]
Cannot see the verification tag on a hamburger, my profile, and view profile, for both athlete and coach

**Comment by technicalbirdVayuz** [comment]
Done
