### ISSUE TITLE
Coach >> Profile verification request

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#229]
on clicking this grey screen is coming

**Comment by technicalbirdVayuz** [comment]
please share user creds & screenshot!

**Comment by rgnarok** [comment]
kush15@mailinator.com
Kush96agra@
Cannot share the screenshot as i removed the user as premium then the profile verification screen also get removed

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by rgnarok** [comment]
The screen is coming grey 
![image](https://user-images.githubusercontent.com/85341053/142163317-7638c0a0-40c6-473b-b485-b9691e502f08.png)

**Comment by technicalbirdVayuz** [comment]
Please share the recording
