### ISSUE TITLE
athlete view profile >> Contact

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#231]
In case I am scrolling up and down the contact button is loading

**Comment by technicalbirdVayuz** [comment]
Not understood. Can you share a video?

**Comment by rgnarok** [comment]
https://user-images.githubusercontent.com/85341053/141608019-3f927f92-6b11-457c-834f-b7cb4c7f4322.mp4

**Comment by technicalbirdVayuz** [comment]
Fixed
