### ISSUE TITLE
Athlete search

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#233]
on pressing 3 dots of the university cards there is no option to add on wishlist coming up

**Comment by technicalbirdVayuz** [comment]
Please share the account creds

**Comment by rgnarok** [comment]
kush15@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
Checked this for the shared creds,  Please check this pointer again. Logic is applicable only for associations (institute type) not for all (Same is there in Web also).

**Comment by rgnarok** [comment]
In case i am applying filter and than accessing the 3 dots the option to add on wishlist is not coming up

**Comment by technicalbirdVayuz** [comment]
Fixed
