### ISSUE TITLE
Wishlit 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#237]
Before adding any college to the wishlist nothing is coming up a grey screen is there it mush show black screen with illustration

**Comment by technicalbirdVayuz** [comment]
![screenshot-2021-11-16_15 59 34 608](https://user-images.githubusercontent.com/18699624/141968901-eb58ce93-75d0-459d-ad8c-df4d52d1575e.png)
This is the screen when no user is added to wishlist, pls share yours screen & creds

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/142162145-e487db2c-230f-45ca-9bda-760be4f8ce97.png)
Creds kush41@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
This was fixed earlier. So Closing this
