### ISSUE TITLE
Athlete >> Email from coach 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#24]
Fix the Part after HI
It must come below Hi 
![image](https://user-images.githubusercontent.com/85341053/129696607-420d9d31-5b7e-4f99-bcd3-d93e6145d1a1.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129887690-72c83458-7e5d-4cb5-ab92-8d9c0c3dfd9a.png)
I hope its fine now
