### ISSUE TITLE
Unable to edit the profile (Association)

### ISSUE THREAD

**Issue by ShikharVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#243]
![image](https://user-images.githubusercontent.com/86296418/143861952-60a5326e-725d-473b-818a-60088deb4ea4.png)
![image](https://user-images.githubusercontent.com/86296418/143861969-c6f8fd3b-e0f0-4820-b671-291d3f9c4a76.png)
Url : https://vu-usa.herokuapp.com/profile-insitute-edit
Creds : maroof.institute@gmail.com
Password : Mkn123@#

**Comment by ShikharVayuz** [comment]
I was trying to fill out the complete form so all the keys could be visible in the postman but I am unable to do so.

**Comment by technicalbirdVayuz** [comment]
Fixed
