### ISSUE TITLE
No Notifications upon signup for coach 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#248]
1. Get verified coach status by having an organization on the VU network "Verify" you. (green check mark) Send a request to any organization on VU to verify you
2. 2. To receive your "Verification badge (green checkmark) simply search for an organization by name and send a request to become verified.  If your organization is not activated on VU, send them the App Link to Join
3. Use our Share App feature to invite your players, coaching staff, and organization to the VU Network 
4. "Coach Name" complete your coaching profile by adding all previous coaching positions
5. Welcome to Volleyball Unite!!!  Enjoy all the features and benefits of being part of this community

**Comment by rgnarok** [comment]
Still not fixed check by creating new coach profile

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/149936046-f6127cea-c4f8-4d47-be47-b40481292f04.png)
![image](https://user-images.githubusercontent.com/85341053/149936747-0bbe0a03-5b7a-48fd-8ddc-c2e8cf1169f0.png)

Still not added Please check properly before sharing >> "Coach Name" complete your coaching profile by adding all previous coaching positions"

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/150284601-059537b0-17ad-4570-803b-ab621561c5c1.png)
Configured in Web
