### ISSUE TITLE
Athlete Verification not working 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#249]
Athlete signed up on app and no buttons to request verification appear on the coach badge

**Comment by rgnarok** [comment]
Need to add the request 
verification button on the card rest flow is working perfectly fine
If this is not possible can we add a guide so that the athlete will know he need to click on 3 dots as the experience is not seamless right now

**Comment by technicalbirdVayuz** [comment]
Sorry, that can't be done for now. There is a difference in showing a guide when data is coming dynamic, it works when data is there already

**Comment by stevekamps** [comment]
A solution needs to be created for this.  I agree it is not seamless.  A coach and athlete will not know they have to click on the 3 dots to get verified.  We need a request verify button just like on the web version

**Comment by technicalbirdVayuz** [comment]
@stevekamps 

As a solution, we can add a floating button that will be visible for athletes & coaches. On clicking of it, we can showcase the bottom sheet & we can add a few animations to make it more interactive. We have implemented this in the app, you can check in the latest build & share your feedback on the same!

![screenshot-2022-01-13_14 30 24 503](https://user-images.githubusercontent.com/18699624/149342771-54ea218c-5dca-4316-929a-5e584a852c24.png)
![screenshot-2022-01-13_14 30 51 991](https://user-images.githubusercontent.com/18699624/149342783-63ccc9ef-02dd-4983-af99-420f269aa07f.png)

**Comment by stevekamps** [comment]
OK. Please push out all these changes to a new app version.  I have tested on version 5 and it is not working

**Comment by rgnarok** [comment]
Working as per shared solution
