### ISSUE TITLE
Coach >>Athlete view profile 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#25]
Make T small in To
![image](https://user-images.githubusercontent.com/85341053/129704774-982b570a-a3ca-413e-8e78-184d6640a2ea.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129884980-04d8f12b-e525-4c1f-b275-3c7f53d89ce6.png)
Fixed
