### ISSUE TITLE
Athelte Premium Description 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#251]
Please add the exact premium wording we have used on the USA web version 
- add this wording to the app premium section

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz Please provide the athlete credentials.

**Comment by technicalbirdVayuz** [comment]
athleteapp3@mailinator.com
12345678aA@

**Comment by ShikharVayuz** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/86296418/146132455-efbbd178-adba-4bc9-a960-607e26c8aa82.png">
Fixed

**Comment by technicalbirdVayuz** [comment]
Will check after integration of Premium module
