### ISSUE TITLE
Club Event Creation 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#253]
When a club creates an event and it comes into my athelte feed (timhadwin@mailinator.com) it says rejected on the app when I click on the event.

When I click on the event on the web version there is no where for me to select that I am "attending" the event

**Comment by stevekamps** [comment]
![image](https://user-images.githubusercontent.com/77851393/143953837-69a21f56-085c-4c57-98df-4261b1bf0a30.png)

**Comment by rgnarok** [comment]
I selected attending in the app but there is no tab come which shows i am attending the event for the athlete and on the web the there is no reflection on what i did on the app and i select the attending on the web then nothing is happening.
Steve01@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
Please check for the pointer which is reported & if there is any other issue then create a new issue @rgnarok

**Comment by stevekamps** [comment]
Club ABC created a new event - Beach Tournament. 

Candis said she is attending. 

Club ABC gt a notification that just says "Candis".  It should say"Candis is attending the event Beach Tournament.  This works on the web version but not on the app version

As the club that created the event I want to be able to see who is attending the event as well. This feature works on the web version but not available on the app version
