### ISSUE TITLE
Add Share APP Icon and Discussion Icon to App feed page

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#254]
Add Share APP Icon and Discussion Icon to App feed page like you have done with VU Canada

**Comment by technicalbirdVayuz** [comment]
@rg

**Comment by technicalbirdVayuz** [comment]
@rgnarok  @stevekamps Please provide more clarity or share screenshot for the reference screen

**Comment by stevekamps** [comment]
Yes. Please Add Share APP Icon and Discussion Icon to App feed page like you have done with VU Canada
