### ISSUE TITLE
Referee Notifications upon signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#255]
1. Use our Share App feature to invite fellow referees to the VU Network 
2. "Referee Name" complete your referee profile and add a headline
3.  Create a "Group" and add referees for instant In-App communication
4. Welcome to Volleyball Unite!!!  Enjoy all the features and benefits of being part of this community

**Comment by technicalbirdVayuz** [comment]
Configured in web
