### ISSUE TITLE
Retired Athlete 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#256]
Retired Athlete signup (jamesnelson@mailinator.com) had the Coach notifications come through when they completed signup process.

Retired can just have the following notifications regardless fi they were a former coach or athlete

1. Use our Share App feature to invite former teammates, coaches, and organizations to the VU Community
2. "Retired Name" complete your profile and add all of your past volleyball history
3. Welcome to Volleyball Unite!!! Enjoy all the features and benefits of being part of this community

**Comment by technicalbirdVayuz** [comment]
Backend Configuration Done!
