### ISSUE TITLE
Cover Pic Update turns screens to black

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#259]

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz  Please provide the api for the Cover pic as I have not worked on this part. Was done previously.

**Comment by technicalbirdVayuz** [comment]
The same API will be there for Cover Image like the rest of the other user profiles. Please check the same issue is there with the profile image

**Comment by ShikharVayuz** [comment]
The package for amazon aws s3 was removed earlier due to gradle error which caused the error to occur.

**Comment by technicalbirdVayuz** [comment]
If I update the image from camera, issue is there, with gallery its working
