### ISSUE TITLE
Admin >>User >> Block 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#26]
I have made the user inactive receive the email also but i can access my account.

![image](https://user-images.githubusercontent.com/85341053/129708448-4f71d2ec-28f0-49cf-b536-15adf4de061d.png)

![image](https://user-images.githubusercontent.com/85341053/129707666-bc2739f1-a3aa-4663-8b6b-a2ecfec59a22.png)

**Comment by technicalbirdVayuz** [comment]
Need discussion on this
