### ISSUE TITLE
Instagram does not check for instagram Url

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#260]
It does check for Valid URL but not for valid Instagram URL

**Comment by ShikharVayuz** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/86296418/145071138-fb2b738d-fc94-4576-a019-6bd99000aed0.png">

**Comment by technicalbirdVayuz** [comment]
https://www.instagram.com/apple/?hl=en

**Comment by technicalbirdVayuz** [comment]
Try this, you will get an error

**Comment by ShikharVayuz** [comment]
Fixed
