### ISSUE TITLE
Information is not in sync with Profile page

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#262]
- [Club URL is there but its not there in web ]
- Icons issue is still there
- There are more fields on the Web
- School type is not getting updated
- Team URL is not clickable but clickable in web

**Comment by ShikharVayuz** [comment]
1) Made url clickable.
2) School type is getting updated please recheck.

**Comment by ShikharVayuz** [comment]
Need updates on "more fields in web".
