### ISSUE TITLE
Conference is not there in the edit form

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#265]

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz  Conference field is not getting updated at web. So cant find the key value pair for the same.

**Comment by technicalbirdVayuz** [comment]
Its fixed in web

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/86296418/145162979-5c1fc0f7-fa5c-4a68-a2e5-c2662537a92b.png">
Field Not present at the web profile UI.
