### ISSUE TITLE
Field Not getting updated (Association Institute)

### ISSUE THREAD

**Issue by ShikharVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#268]
Key : "phone_extension"

**Comment by technicalbirdVayuz** [comment]
It is working fine, please discuss on call if possible

**Comment by ShikharVayuz** [comment]
Post Body : {"name":"Maroof","headline":"2019 National Champs","institution_url":"http://writersmelon.s3.amazonaws.com/images/1613390304338_1613390304338.jpg","association_type":"ASSOCIATION_INSTITUTE","institution_team_name":"Fantastic Team","institution_team_url":"http://writersmelon.s3.amazonaws.com/images/1613390304338_1613390304338.jpg","head_coach_name":"Ankit Arora","assistant_coach_name":"Coach Sarah","institution_phone":"072-066-47813","head_coach_email":"shobhitayadav@ymail.com","instagram_url":"https://www.instagram.com/volleyballunitecanada/?hl=en","province":"Alaska","city":"Bhiwani","league":"NAIA","region":"Northeast","school_type":"Public","enrollment":null,"tuition_in_state":23,"tuition_out_state":3214,"division":"NAIA","phone_extension":"23","user_id":"1eb370367c8186c03f3df2b97b507e32"}


Fetch Body : {
    "status": 200,
    "data": [
        {
            "_id": "qYpbnA9BjLe8Fs3XT",
            "user_id": "1eb370367c8186c03f3df2b97b507e32",
            "name": "Maroof",
            "email": "maroof.institute@gmail.com",
            "city": "Bhiwani",
            "province": "Alaska",
            "user_type": "ASSOCIATION",
            "association_type": "ASSOCIATION_INSTITUTE",
            "password": "c00d1846d6b03c4e2256484e84960cc4",
            "about": "Coder7\n9",
            "coach_association_name": "Jmi",
            "cover_image": "https://s3-ca-central-1.amazonaws.com/volleyballunite/images/volleyballunite/images/pRzRN.png",
            "coach_email": "test@mailinator.com",
            "coach_name": "John",
            "coach_phone": "8745029282",
            "institution_phone": "072-066-47813",
            "institution_team_name": "Fantastic Team",
            "institution_team_url": "http://writersmelon.s3.amazonaws.com/images/1613390304338_1613390304338.jpg",
            "institution_url": "http://writersmelon.s3.amazonaws.com/images/1613390304338_1613390304338.jpg",
            "division": "NAIA",
            "phone_extention": "2436236322",
            "profile_picture": "https://s3-ca-central-1.amazonaws.com/volleyballunite/images/volleyballunite/images/V9gjl.png",
            "gender": "Male",
            "type_of_school": "All Group",
            "enrollment": null,
            "tuition": "Learn And Play",
            "act_score": "98",
            "sat_score": "87",
            "gpa": "9",
            "is_active": true,
            "premium_user": true,
            "email_status": true,
            "special_case": true,
            "created_at": 1626252479771,
            "payment_configured": true,
            "skip_payment": true,
            "updated_at": 1638944662361,
            "platform": "Android",
            "token": "f4uY9ARaTmC36sbQvb29uQ:APA91bHZzJGcgfVJcLXvax29XDXc701QYOMZDdfraTsuhToRZN4v4yIDHARUeniNSetmEmlOAswONB6kcmrvut7U_NGAUntactR8g8sPx-FX5y7OBAfMHpC5WScf4Sv6mhcPMKBDnrJd",
            "assistant_coach_name": "Coach Sarah",
            "head_coach_email": "shobhitayadav@ymail.com",
            "head_coach_name": "Ankit Arora",
            "headline": "2019 National Champs",
            "instagram_url": "https://www.instagram.com/volleyballunitecanada/?hl=en",
            "league": "NAIA",
            "phone_extension": "23",
            "region": "Northeast",
            "school_type": "Public",
            "tuition_in_state": 23,
            "tuition_out_state": 3214,
            "conference": "cheers",
            "total_connections": 0,
            "total_following": 0,
            "is_connected": true
        }
    ],
    "is_connected": true
}
