### ISSUE TITLE
Instagram URL is not showcased in Profile section, Association Club

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#269]

**Comment by technicalbirdVayuz** [comment]
If instagram url is empty, it should not be visible in the profile,

**Comment by technicalbirdVayuz** [comment]
![Screenshot_20211209_101930](https://user-images.githubusercontent.com/18699624/145336427-842b1936-2dbb-4a88-a6eb-3a36f23d7676.jpg)

**Comment by technicalbirdVayuz** [comment]
Also, it is not visible for high school
![Screenshot_20211209_103411](https://user-images.githubusercontent.com/18699624/145337668-2c37a249-333c-4ce1-809f-7bc7abb3e30a.jpg)

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz  Connect with me to check if done right.
