### ISSUE TITLE
End point to fetchAllTeamMembers returning different response

### ISSUE THREAD

**Issue by ShikharVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#273]
Required Response : Get added athlete details.
Current Response : All Committed Users 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/86296418/145762108-16c436ac-5e6a-4a7f-a68f-e4347a05a9ad.png">

**Comment by technicalbirdVayuz** [comment]
Please connect to discuss this, you are using the wrong api somewhere, we need to debug further

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz Sure, But as I was earlier told to use this end point. We can connect to debug the issue.

**Comment by ShikharVayuz** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/86296418/145935234-b4d97133-b025-483f-9968-23dd94a91d0b.png">
