### ISSUE TITLE
Need to add google analytics

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#274]
Hi Kush,

 

I have set up Google Analytics for volleyballunite.com and now I need this code added please.

 

<script async src="https://www.googletagmanager.com/gtag/js?id=G-XK2JZ4HSKD"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());

 

  gtag('config', 'G-XK2JZ4HSKD');

</script>

 

Please let me know when this is completed as it should only take a minute but critical to our success and I want to test as soon as possible.

**Comment by technicalbirdVayuz** [comment]
Configured on Production, Pls ask him to check

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/145936587-9279aae4-b1be-4fed-88af-598403c6c599.png)

**Comment by rgnarok** [comment]
done
