### ISSUE TITLE
Sign up - Organisation

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#278]
In case i have not selected any organisation type and after OTP verification i  kill the app then after again sign in it is taking me to the feed section where i see no details added and it is directly taking me as a club. Correct this it must take me to the sign up step where it is break

**Comment by technicalbirdVayuz** [comment]
Please share the screen recording for this. We are not facing this issues.

Killing the app in between redirecting to Sign-in Screen

**Comment by rgnarok** [comment]
working fine now closing this
