### ISSUE TITLE
Athlete >> Search 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#29]
I have not used the search filter but i am getting this after 3 searches
![image](https://user-images.githubusercontent.com/85341053/129711413-99118cda-ce90-4606-b46e-423a247bbdfe.png)

**Comment by technicalbirdVayuz** [comment]
@rgnarok  Have checked this case no such issue occurred.

Please share the user credentials, will share what all keywords has been searched by that user.

**Comment by rgnarok** [comment]
arushi@mailinator.com
VUPassword1@

**Comment by technicalbirdVayuz** [comment]
Normal Search would be open. For Advance search, 3 times usage would be free & then the premium would be required. Please confirm

**Comment by rgnarok** [comment]
Yes it is the flow , Advance search means searching using advance filter
