### ISSUE TITLE
View Athlete profile

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#295]
Organisations cannot endose the athlete so remove this they can only see if the athlete has been endorsed
Give option to add on virtual bench which is missing

**Comment by technicalbirdVayuz** [comment]
@ShikharVayuz Give option to add on virtual bench which is missing - Done
Organisations cannot endose the athlete so remove this they can only see if the athlete has been endorsed
 - Not done (you have removed the card for endorsement, how will organization view)
