### ISSUE TITLE
Coach >> Feed >> Create post

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#30]
I am not adding anything but it is automatically creating blank posts
![image](https://user-images.githubusercontent.com/85341053/129727692-cb2aea13-f515-4ca6-9b94-1518b60f45ab.png)

**Comment by technicalbirdVayuz** [comment]
Can you share the creds

**Comment by rgnarok** [comment]
kush10@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
Fixed
