### ISSUE TITLE
Profile verification requests

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#307]
The coach who is asking for verification his details are coming wrong it is showcasing the coach as athlete correct that

**Comment by priya-iyer-vayuz** [comment]
![image](https://user-images.githubusercontent.com/94518947/147544707-c5ed10f7-ab89-4fb6-9d9a-05f35a41388d.png)

**Comment by rgnarok** [comment]
Still not fixed check the detail page of the coach fix this
