### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#308]
Push notifications are not coming up on the app

**Comment by technicalbirdVayuz** [comment]
Can you share which all notifications not coming?

**Comment by rgnarok** [comment]
I checked the like and comment plus the notification for the coach requested for review they all were not coming up as push notification

**Comment by technicalbirdVayuz** [comment]
We need to create a list of push notification which are not working

**Comment by technicalbirdVayuz** [comment]
@rgnarok Let us know by when you could share a list of notifications that are not working?

**Comment by rgnarok** [comment]
@technicalbirdVayuz  no notification is coming as pushed whether it is sign up, like comment or request verification please configure for all and check

**Comment by technicalbirdVayuz** [comment]
We need test cases on the sheet, if you can not provide then let us know. @rgnarok

**Comment by rgnarok** [comment]
@technicalbirdVayuz @ShikharVayuz  the way notification are now coming are not as per canada, also push notification is not there if the app is in background or killed
