### ISSUE TITLE
Coach >> Athlete view profile >> Event RSVP 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#31]
I have accepted a public event as an athlete but it is not visible on the athlete profile

![image](https://user-images.githubusercontent.com/85341053/129855907-5d044815-38b5-4c0d-881e-c6de16825370.png)

![image](https://user-images.githubusercontent.com/85341053/129855802-afc1f72d-d6da-47ec-baff-fd5ac7beb468.png)

**Comment by technicalbirdVayuz** [comment]
It could be part of the Athletes profile, but for view profile , pls confirm

**Comment by rgnarok** [comment]
Yes it is confirmed only the coach who is connected to the athlete or premium coach can see the public events in which the athlete is taking part

**Comment by technicalbirdVayuz** [comment]
But that's additional logic, We should not spent time on additional things

**Comment by rgnarok** [comment]
This is not an additional logic it is due to this reason this was created that coaches if it is not so then why this has to be do anything with coaches as written in SOW. 
![image](https://user-images.githubusercontent.com/85341053/131279213-50212595-ec85-4a8a-9d2b-efe3b134ec10.png)
![image](https://user-images.githubusercontent.com/85341053/131279058-4fe425f7-5e9e-428c-ba5e-cfde6cf087de.png)

**Comment by technicalbirdVayuz** [comment]
Only Premium Users & connected can see the profile, So its added on View profile page. let me know in case of any issue
> Yes it is confirmed only the coach who is connected to the athlete or premium coach can see the public events in which the athlete is taking part
