### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#310]
- Remove Groups
- In case i am accessing the advance filters it is not working it is getting disappear and then comes up

**Comment by technicalbirdVayuz** [comment]
@priya-iyer-vayuz please make changes for association only

**Comment by technicalbirdVayuz** [comment]
In case i am accessing the advance filters it is not working it is getting disappear and then comes up
- This would be working as the same way as we need to call the API first to check whether free filters are remaining or not
