### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#311]
Added instagram detail is not getting showed in the profile

**Comment by ShikharVayuz** [comment]
@rgnarok  Please mention the credentials as well because this could be a backend error.

**Comment by rgnarok** [comment]
I am using the creds shared by @technicalbirdVayuz  and this is not working for all

**Comment by rgnarok** [comment]
@ShikharVayuz  check for highschool and club

**Comment by ShikharVayuz** [comment]
@rgnarok Ok will check!
