### ISSUE TITLE
Hamburger - High school

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#313]
- Correct the organisation type under the headline
- Correct the elements,remove groups add events, add premium, add profile request verification add, change following to followers and add correct API to it so that it will show correct results

**Comment by technicalbirdVayuz** [comment]
Reported Followers point here: https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/issues/324

rest are done
