### ISSUE TITLE
Coach >> Settings >> Subscription details

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#32]
Not coming up and no option to cancel it
![image](https://user-images.githubusercontent.com/85341053/129857612-cb08d9a8-54da-4e79-bf9f-8b0856807bbc.png)

**Comment by technicalbirdVayuz** [comment]
Please share the credentials

**Comment by rgnarok** [comment]
kush10@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
Please create another user. This one has older details. 

Have you enabled premium from the backend?

**Comment by rgnarok** [comment]
Yes i have enabled it from the backend

**Comment by technicalbirdVayuz** [comment]
Please create a new user & check this again. It should work, same has been checked from my end.
