### ISSUE TITLE
Admin >> user management

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#33]
Change the text from province to state 
![image](https://user-images.githubusercontent.com/85341053/129861352-849fe64d-d0a1-4c08-91e9-36e47f663559.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129886583-8b275dfd-2a96-4f2b-891d-25be2ae43232.png)
Fixed
