### ISSUE TITLE
Athlete Verification flow

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#336]
Athlete verification flow on the app is not there, 
I cannot see request verification button on coach card and details pages the following:
- Search listing 
- Unite section

**Comment by rgnarok** [comment]
We need to add buttn which is visible like in the web as it is not helping on 3 dots @technicalbirdVayuz @ShikharVayuz

**Comment by technicalbirdVayuz** [comment]
Button could not be added for the following reason
- Request verification | Requested Verification as a text is too long, it would be a problem for low-resolution devices

Button can be added but text change is recommended first

**Comment by technicalbirdVayuz** [comment]
Moving discussion to #249
