### ISSUE TITLE
Coach Premium Description - Apps 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#346]
Please change the premium description for coaches on the APP so that it is consistent with the web version.

- Search for athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club, Jersey Number, etc)

- Access to full profiles of all athletes on Volleyball Unite.

- Add prospective athletes to your Virtual Bench.

- Access to all committed and signed athletes on College and Club pages

- Receive a premium badge on your coach profile badge

- To search for signed/committed Athletes... Go Premium Now!!

**Comment by rgnarok** [comment]
Not fixed

**Comment by rgnarok** [comment]
In complete last 2 pointers still not coming
