### ISSUE TITLE
Notifcation when a club views athlete profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#347]
Please change the notification for an athlete when a club views profile to the following:

"An Association has viewed your profile. Go Premium to find out who it was. "

Hyperlink the word premium to allow easy click for going premium

**Comment by technicalbirdVayuz** [comment]
Configred in Web

**Comment by stevekamps** [comment]
Capitalize the A on Association please

**Comment by rgnarok** [comment]
- Still incorrect plus on the web it is going organisation so please do it "An organisation"
- On web notification not coming for the same flow
- On app , make Premium text red plus on clicking on it a grey screen coming up

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/149708389-5e588ee1-2764-4331-9031-af3f0d5aad2b.png)

Checked For web

It is working fine, Please share both creds you used while checking

**Comment by priya-iyer-vayuz** [comment]
@technicalbirdVayuz  require link for hyperlink text premium

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/149935189-21798dc6-c408-45f6-b6b0-5e917674982f.png)

Still on the app the following are missing:
1. An organisation not A association 
2. Premium is not in red as on the web

Please check properly before sharing
