### ISSUE TITLE
Change Athlete Premium descriptions on Apps to match the web version 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#348]
Features
- Search for all College Volleyball Programs in the USA using our powerful search filters (search by State, Region, Conference, Division, Tuition, etc)

- Add your favorite programs to your College Wish List

- Receive a PREMIUM badge to showcase your player profile (add badge here)

- See who viewed your profile.

- Receive a notification when a Coach/College adds you to their virtual bench.

- Access the committed athletes on College pages

- Access all signed/selected club athletes on the respective club team page.

- Unlock the endorsement profile section and get endorsements from your coaches.

- Up to 1 GB of images, video, posts on feed for 1 year.

**Comment by rgnarok** [comment]
Not fixed
