### ISSUE TITLE
Club - Adding Teams on APP. Levels need changed

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#350]
I Created a club
clubxyz@mailinator.com
Volleyball11$

On the app when I go to create a team it has under level the following choices (varsity, Junior Varsity, Middle School).  These are the levels for a school organization.  

For a club organization, the levels need to (U13, U14, U15, U16, U17, U18, U19, 19+)

**Comment by technicalbirdVayuz** [comment]
for Organization of type College
 - varsity, Junior Varsity, Middle School
  for Organization of type Club
  - U13, U14, U15, U16, U17, U18, U19, 19+
  for Organization of type High School & PROVINCIAL 
  - varsity, Junior Varsity, Middle School

**Comment by stevekamps** [comment]
We don't have to worry about College as they have been created already.  

For Club the type needs to be U13, U14, U15, U16, U17, U18, U19, 19+

For School the type needs to be Varsity, Junior Varsity, Middle School

For Association the type needs to be U13, U14, U15, U16, U17, U18, U19, 19+

**Comment by technicalbirdVayuz** [comment]
Configured in Web. Please check

**Comment by technicalbirdVayuz** [comment]
Configured in App also
