### ISSUE TITLE
Club Menu on App. Add an S

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#351]
Please add an S to Signed Athletes

**Comment by priya-iyer-vayuz** [comment]
require screenshot

**Comment by stevekamps** [comment]
On the App menu for a Club..... it currently says "Signed Athlete".  It needs to say "Signed Athletes".  You continually miss the S's and it drives me crazy. We have been down this road with VU Canada.  I'm not wasting my time with a screenshot.
