### ISSUE TITLE
Club Premium Features 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#352]
When you click on Events as a nonpremium club it says you have to go premium. When I click on the premium button it takes me to the coach premium page rather than the Association premium page.  Same thing when I sign in as a High School.

The premium link on its own redirects to the correct place

Change Premium  features for Association to the following: (on web and apps)
Features
- Access to all committed athletes on College rosters

- Access to all Club rosters

- Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)

- Created Events will also be searchable by all followers (i.e. High School Camp)

- Mobile phone calendar event synchronization

- Receive a PREMIUM badge to showcase your profile

**Comment by rgnarok** [comment]
Not fixed check for the club
club11@mailinator.com , pass - Kush96agra@
