### ISSUE TITLE
High School Signup - Spelling error

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#353]
Athletic Director is correct spelling

**Comment by technicalbirdVayuz** [comment]
![screenshot-2022-01-07_15 13 42 949](https://user-images.githubusercontent.com/18699624/148524995-8a53c0eb-c005-404b-b6cc-fb5f7f9406c8.png)
It was correct in the signup. made changes while editing
