### ISSUE TITLE
Add done button when adding Athletic Director Phone number 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#355]
Add done button when adding Athletic Director Phone number .  Right now the screen gets stuck on phone pad and I cant submit 

Also same thing happens when I try to edit coaching info.  I need a submit or done button on phone pad when entering coaches phone numbers

**Comment by rgnarok** [comment]
Please mention the usertype and module

**Comment by technicalbirdVayuz** [comment]
User type : Association (High School) @rgnarok, Module is sign up & Edit profile

**Comment by rgnarok** [comment]
Done
