### ISSUE TITLE
College Profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#364]
1.  Under Institute Information please change to "COLLEGE URL" and "TEAM URL"
2.  Add instagram URL

**Comment by technicalbirdVayuz** [comment]
Please share the screenshot, reference of the issue is not clear

**Comment by stevekamps** [comment]
Change Association URL to "COLLEGE URL"

Change Institute Team URL to just "TEAM URL"

**Comment by stevekamps** [comment]
![IMG_9708](https://user-images.githubusercontent.com/77851393/148432437-b918e6d6-46fd-45de-b565-f2c204d19598.jpg)
![IMG_9709](https://user-images.githubusercontent.com/77851393/148432444-71361f5f-89fa-4331-8139-b291ac8a2ea5.jpg)
