### ISSUE TITLE
College - Can't upload photo or video to feed from phone on APP 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#366]
I am guessing this is the same for all users

**Comment by technicalbirdVayuz** [comment]
Will check on the iOS

**Comment by stevekamps** [comment]
None of the image uploads are working on the app - Feed, Profile Images, cover photo

Event Image does upload and works

**Comment by rohitrvayuz** [comment]
This has been fixed and reviewed.
