### ISSUE TITLE
Change Premium description on APP for College 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#367]
Says Association at top. Perhaps to make things easier for all users at the tip just put "Premium Features".  

- Access to all committed athletes on College rosters

- Access to all Club rosters

- Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)

- Created Events will also be searchable by all followers (i.e. High School Camp)

- Mobile phone calendar event synchronization

- Receive a PREMIUM badge to showcase your school profile (put no blue badge here)

**Comment by rgnarok** [comment]
Text still not change check for the user maroof.institute@gmail.com , pass - Mkn123@#
