### ISSUE TITLE
College - Followers are showing up as grey boxes in app

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#369]

**Comment by technicalbirdVayuz** [comment]
Please share the credentials of the logged in user

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/148431453-f58c18a4-f384-4664-a583-3056d546b78f.MP4

Maroof.institute@gmail.com
Mkn123@#

I have made sure I followed this College with a player......so that is not the issue
