### ISSUE TITLE
Club - City dropdown menu not functioning in profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#370]
Club - City dropdown menu not functioning.  After choosing a State the city doesn't function with that state.  It shows only states again in the  dropdown menu

- likely not working on any of the organizations

**Comment by technicalbirdVayuz** [comment]
Can you pls attach the screenshot?

**Comment by stevekamps** [comment]
Working Now . Closing
