### ISSUE TITLE
Event Creation not functioning on App.  

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#372]
Event Creation not functioning on App.  

- Put in all info and hit create and it just spins and doesn't create event on the app 
-

**Comment by technicalbirdVayuz** [comment]
Can you confirm the OS pls, Is it android or iOS?

**Comment by technicalbirdVayuz** [comment]
Checked in Android, its working @stevekamps

**Comment by stevekamps** [comment]
IOS is not working

**Comment by technicalbirdVayuz** [comment]
Duplicate #236 Moving the discussion there
