### ISSUE TITLE
Association User - Add Events to Web Version 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#376]
Association User - Add Events to Web Version as a PREMIUM feature

**Comment by technicalbirdVayuz** [comment]
Events are not visible currently if the association is not premium, Do you want this to be enabled then show a popup saying this section is accessible to only premium users? Please confirm

**Comment by stevekamps** [comment]
Yes please have Events tab visible on web and apps.  Then a popup if they click on it that says "Creation of Events is accessible to Premium Users.  Go Premium Now"

**Comment by technicalbirdVayuz** [comment]
Fixed this in Web

**Comment by stevekamps** [comment]
Leave open until it is fixed on the App

**Comment by technicalbirdVayuz** [comment]
![Screenshot_20220113_111045](https://user-images.githubusercontent.com/18699624/149272423-9988eda5-bb7c-40c5-a208-83cd1a691a28.jpg)
Its configured in app also, please recheck

**Comment by rgnarok** [comment]
This is done
