### ISSUE TITLE
Referees & Retired  - Add premium upgrade and features 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#379]
Add a Premium for Referees & Retired on web and app

Retired (Athlete or Coach) and Referee - $19.95/year – be able to see who viewed your profile, Be able to see College “Committed athlete” badges on respective teams, be able to see club and school “selected athlete” badges on respective teams, be able to see Regional/State Associations “Teams” of player badges

**Comment by technicalbirdVayuz** [comment]
@rgnarok  Please discuss this flow. Premium was not there for Referee earlier

**Comment by stevekamps** [comment]
Yes this is the documentation that I sent you and copied and pasted.

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please discuss

**Comment by rgnarok** [comment]
@stevekamps  we had a discussion about it that what will referee do by checking out on the college and club athletes  then we came to a conclusion that it is not required as referee has nothing to do with it plus all the other users are getting group as a normal feature but solely for referee giving it premium will not make sense. If required we can discuss further on this. But for now we believe it is not required and it is not included. 
Let me know when can we discuss the same

**Comment by stevekamps** [comment]
referee, retired and high school coach don't need premium. Closing issue
