### ISSUE TITLE
Athlete > Feed > There is a hover over Name, but it's not clickable.

### ISSUE THREAD

**Issue by Arushi1390** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#38]
![Screenshot (644)](https://user-images.githubusercontent.com/88670762/129896218-a421ca48-5ef6-4bac-8e81-253de436becd.png)

**Comment by vayuzpriya** [comment]
@Arushi1390  issue not clear please elaborate

**Comment by vayuzpriya** [comment]
@rgnarok  @technicalbirdVayuz  NO update

**Comment by vayuzpriya** [comment]
@rgnarok  @technicalbirdVayuz @Arushi1390  Please explain the issue

**Comment by vayuzpriya** [comment]
Fixed
