### ISSUE TITLE
Athlete Profile - Physical Attributes 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#381]
Change from CM to Feet and inches.
Please add a dropdown menu for feet from 4-7 and a drop down menu for inches from 1-11

**Comment by technicalbirdVayuz** [comment]
Configured in Web

**Comment by rgnarok** [comment]
I am adding vertical from the app it is not getting reflected on the web plus i updated on the web still not visible
I am adding dominant hand on the app t is not getting reflected on the profile of the app
