### ISSUE TITLE
Adding Volleyball info to profile

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#382]
When a retired user registers as a retired player it asks for College and University.  Please remove University from the choices.

If I choose past College it shows up as CCAA in my profile after I save it.

The same thing occurs for all "Other Athelte Users' and also current club athletes that try to add a College to Profile.

These need to be updated to the USA Divisions for College

**Comment by technicalbirdVayuz** [comment]
@stevekamps Please confirm the following changes
- CCAA needs to be renamed to college across the platform
- Remove University tab from Retired sign up form

**Comment by stevekamps** [comment]
Yes replace CCAA and change to College

Remove University option from signup form for retired and athlete.  Also remove from where they can add previous playing experience.

**Comment by technicalbirdVayuz** [comment]
CCAA has been replaced earlier. I have signed up with a new retired user & chosen college while adding details it is showing me college only, CCAA is not being shown.

Please share the credentials of user

Regarding, remove University, required changes has been done (in web)

**Comment by stevekamps** [comment]
CCAA shows up in the athlete profile when you had previous playing experience and choose College.

**Comment by rgnarok** [comment]
1. Retired - Athlete >> Profile >> Add volleyball information >> Remove Usports
2.Athlete >> Profile >> Add volleyball information >> Remove Usports
