### ISSUE TITLE
Premium Organization - viewing another Organization 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#383]
When a premium organization (i.e. collegexyz@mailinator.com) (Volleyball11$) views another club (i.e. Club ABC) the club ABC profile comes up as an athlete profile rather than the club info profile and teams .  see video below

**Comment by stevekamps** [comment]
![IMG_9724](https://user-images.githubusercontent.com/77851393/148485080-6a053966-8952-48d4-8f8d-2d2e15fa9b07.jpg)

**Comment by technicalbirdVayuz** [comment]
@stevekamps Can you attach the video, only image is attached

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by rgnarok** [comment]
Working fine
