### ISSUE TITLE
Coach Contact Email 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#386]
Change the subject line to:

Volleyball Unite | Coach Contact
![contactemail](https://user-images.githubusercontent.com/77851393/149196415-3e4af8de-12d4-4c92-ad3c-5e6cc76a197a.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/149266588-ffe24d06-8a76-488d-8f86-c28e4be5f770.png)
Fixed. Closing this
