### ISSUE TITLE
Coach Contact Email Content 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#387]
Change the email to the following:

Hi <Name>,

<Name >- (coach or organization) has viewed your profile on Volleyball Unite and they wish to contact you.

Phone: 555-555-5555
Email: collegexyz@mailinator.com

<Name> (coach or organization) message:

Regards, (don't forget this comma)
(add a space here)
Volleyball Unite Admin

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/149267656-7eb25211-b4cf-4f00-be21-86b895d130d1.png)

I hope this would work
