### ISSUE TITLE
Add to Virtual Bench 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#388]
Currently for a premium coach or premium organization when visiting an athlete profile it says "Add Virtual Event".

Please add the word "to"

i.e. "Add to Virtual Bench"

**Comment by technicalbirdVayuz** [comment]
Configured in Web

**Comment by ShikharVayuz** [comment]
@stevekamps Please provide an screenshot for the reference (Mobile app)

**Comment by priya-iyer-vayuz** [comment]
no available text issue as such in the application code. Please attach a screenshot

**Comment by rgnarok** [comment]
Didnt find this closing it for now @stevekamps please share the screenshot in case you find the same
