### ISSUE TITLE
Changes to Physical Atrributes 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#390]
Please change the following in Physical Attributes (Athlete Profile)

Change all (feet) drop-down menus to 4-12 for consistency.

Change Skipe touch to "Spike Touch" 

Standing touch should be "Standing Reach"

Vertical Touch should just be "Vertical"
![phsycialattributes](https://user-images.githubusercontent.com/77851393/149200208-a3eb0607-ea80-47a9-89fd-04284c4c82eb.jpg)

**Comment by technicalbirdVayuz** [comment]
- Change all (feet) drop-down menus to 4-12 for consistency. - done 
- Change Skipe touch to "Spike Touch" - Done
- Standing touch should be "Standing Reach" - Done
- Vertical Touch should just be "Vertical" - Done

Changes done in Web

**Comment by ShikharVayuz** [comment]
Change all (feet) drop-down menus to 4-12 for consistency. - done
Change Skipe touch to "Spike Touch" - Done
Standing touch should be "Standing Reach" - Done
Vertical Touch should just be "Vertical" - Done
Changes done in App
