### ISSUE TITLE
Athlete Search Filters not working on IOS App

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#394]
Athlete Search Filters not working on IOS App

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/149204912-0327f97d-89dc-463f-a0dc-d7faaaf1576d.MP4

**Comment by rohitrvayuz** [comment]
This has been fixed and reviewed.
