### ISSUE TITLE
Athlete Message on App when they click on Wishlist 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#395]
Please see the current message that athletes get on the App when they click on "wishlist". 

It should say the following"

Activate the "Advanced Search Filter" enabling you to search for all College Volleyball Programs in the USA by City, State, Region, League, Division, Conference, Enrollment, and Tuition. Go Premium Now.
![Screenshot 2022-01-12 at 11 50 40 AM (1)](https://user-images.githubusercontent.com/77851393/149204198-2f43f2e2-6dfd-436e-9a05-aea1ee3d3fd0.png)

**Comment by rgnarok** [comment]
Text is not properly left aligned

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/149933996-82d70edb-aa25-44ea-9f02-d0a719f1daae.png)
Please check properly still not fixed
