### ISSUE TITLE
Homepage >> Coming soon

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#40]
Change the text to state for province
State and city dropdown text not visible

![image](https://user-images.githubusercontent.com/85341053/130007531-c1455546-0098-4ae7-a957-14dda24d3149.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/130015208-f094f595-b852-4fba-ba93-8973064b4296.png)
![image](https://user-images.githubusercontent.com/18699624/130015246-729bbffb-e70e-4b83-a51e-6a877eed39f8.png)
![image](https://user-images.githubusercontent.com/18699624/130015269-0cca6e9b-6dff-4830-8237-a76eeddd9351.png)

**Comment by technicalbirdVayuz** [comment]
Making code live also, Please close the issue from your end @rgnarok (After 10 min, it will be live)
