### ISSUE TITLE
Notification >> Coach

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#400]
On clicking to the notification s repated to profile view or edit profile it is taking to the grey screen

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz I have not received any notification regarding "complete your profile" when signed in as a new coach.
Creds : sjc@mailinator.com
Password : Mkn123@#

Note : Edit profile is working fine 
Device tested (H930DS aka LG V30+)

**Comment by ShikharVayuz** [comment]
@rgnarok Please share the coach creds that you have tested on along with screen record. 
Earlier I have checked with :
kushagra04@mailinator.com
Kush96agra@
