### ISSUE TITLE
Coach >> Profile

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#407]
What ever i am updating on edit profile the following are not getting reflected:
1. College name
2. College city
3. College State(Currently province is written please correct it)

**Comment by rgnarok** [comment]
Not fixed Please check properly and instead of institution it is College correct that

**Comment by technicalbirdVayuz** [comment]
As Discussed, In case of College labels would be INSTITUTE NAME, INSTITUTE STATE, INSTITUTE CITY, INSTITUTE TEAM NAME

The only changes would be changes in the dropdown in the App @ShikharVayuz @rgnarok @priya-iyer-vayuz
