### ISSUE TITLE
Repeated items on notifcations for athelte new signup - IOS 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#408]
Repeated items on notifcations for athelte new signup - IOS 
![IMG_9851](https://user-images.githubusercontent.com/77851393/150438002-b2a22133-ed1c-4417-8de6-3ad84b73f2f9.jpg)

**Comment by rohitrvayuz** [comment]
@stevekamps This is synced with the web flow. No notifications are repeating.
please check.
