### ISSUE TITLE
All states are not coming up in the list

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#41]
There need to be more states it is showing only 10  the number of states are 50 in USA check this please
![image](https://user-images.githubusercontent.com/85341053/130036033-cef61c76-4353-480b-a9cb-2ab1cbc5752e.png)

**Comment by technicalbirdVayuz** [comment]
There are 22k records, Would take around 2 hrs to update the same. Same has been updated to production. Please check

**Comment by technicalbirdVayuz** [comment]
Closing this! As it will be fixed automatically on Production
