### ISSUE TITLE
athleteclub2 is showing up as verified. They have not been verified yet

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#411]
athleteclub2 is showing up as verified. They have not been verified yet as per item #409. 
![IMG_9853](https://user-images.githubusercontent.com/77851393/150438526-c124aa13-c8f1-46ab-b6e0-2bf6c907d839.jpg)

**Comment by rgnarok** [comment]
Working fine
