### ISSUE TITLE
Incorrect notifcaiton for athelte signup on IOS 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#417]
Incorrect notifcation for athlete signup on IOS . See screenshot
![IMG_9871](https://user-images.githubusercontent.com/77851393/150653616-bf00cc7b-1ca5-41fc-b413-fb4d96a8e8c0.jpg)

**Comment by rgnarok** [comment]
Done
