### ISSUE TITLE
Change Followers to Following on this athlete, coach, retired, and referee page on IOS 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#418]
Change Followers to Following on this athlete and coach page on IOS
![Screenshot 2022-01-22 at 12 55 54 PM](https://user-images.githubusercontent.com/77851393/150653677-40275545-e0c3-4959-87bf-fad385e49fe6.png)

**Comment by rgnarok** [comment]
Done
