### ISSUE TITLE
Message for Club coach trying to go premium 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#419]
Change wording to this.......

You need to be a "Verified Coach" before you can purchase a Premium membership. To get your Coaching Profile "Verified" (input green badge here) simply "Search" for an Organization and send a request to become "Verified".

Once verified you can upgrade to a Premium Membership.

**Comment by rgnarok** [comment]
To get your Coaching Profile "Verified" (input green badge here) simply "Search" for an Organization and send a request to become "Verified".
This line is repeating on the app please fix

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/151186042-b4ca57be-7adc-4dd3-b52d-aa825c5a7790.png)

**Comment by ShikharVayuz** [comment]
![Screenshot_20220127-171445](https://user-images.githubusercontent.com/86296418/151352839-77db1032-c08c-47d7-9f7c-48d8f7c02362.png)
