### ISSUE TITLE
Coach search filter

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#42]
Not giving an option to search for 3 times using the search filter
![image](https://user-images.githubusercontent.com/85341053/130037769-dab33f8e-6cfd-452f-9ae8-c81d70304713.png)

**Comment by technicalbirdVayuz** [comment]
What needs to be done here?

**Comment by rgnarok** [comment]
Option to Add to Virtual Bench (Only for Coaches | Limited to 3 Searches for free) 
3 search using the filters are free if it is used then the message to do premium must appear

**Comment by rgnarok** [comment]
As discussed the 3 search flow on the call
Users who are not premium will et an option to use search filters only 3 times and they can add the athlete to the virtual bench once this is over then they will get an option to go premium

**Comment by technicalbirdVayuz** [comment]
**they can add the athlete to the virtual bench once this is over**  - This is for premium only correct?

**Comment by technicalbirdVayuz** [comment]
Please review, Option for adding virtual bench is in view profile only and premium check is added there
