### ISSUE TITLE
Coach clicking on Premium tab on IOS - Freezes screen 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#420]
Coach clicking on Premium tab on IOS - Freezes screen . See attached

https://user-images.githubusercontent.com/77851393/150654328-7113bbf7-ef8b-43fa-8eef-6fcaa03891c6.MP4

**Comment by rgnarok** [comment]
Working fine on Android device @technicalbirdVayuz

**Comment by stevekamps** [comment]
working. closing
