### ISSUE TITLE
High School Coach - Allow them to see club and college rosters 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#421]
Allow High School coach to see club team rosters and College team rosters.  Currently, it says you need to be premium to see the rosters when you try clicking on one.  But there is not premium for high school coach.
Please allow them to see the rosters for free and no premium option for this type of coach

**Comment by technicalbirdVayuz** [comment]
Configured for Web

**Comment by stevekamps** [comment]
Not working on my end. Still shows premium and doesn't allow me to see rosters

**Comment by technicalbirdVayuz** [comment]
What exactly does Roaster mean, is it Signed athletes & committed athletes both?

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please share this in Enhancement sheet, we will share the time for the same!
