### ISSUE TITLE
Add notifications when a club signs up 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#422]
- Welcome to Volleyball Unite!!  Enjoy all the features and benefits of being part of this community
- Use our Share App feature to Invite your club Coaches and Athletes to the VU Community
- Club athletes that signup on VU and choose your club will automatically appear in your signed athletes tab
- Create your teams and add your coaches and athletes to the roster.

**Comment by technicalbirdVayuz** [comment]
Configured in Web

**Comment by ShikharVayuz** [comment]
Configured in app

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/151189116-fe84716b-a8c4-45cf-b8e1-857e3be996d1.png)
![image](https://user-images.githubusercontent.com/85341053/151189174-44f79e0b-73ab-4265-8b77-f88bcbbb6918.png)
Not working

**Comment by technicalbirdVayuz** [comment]
Please share the creds, Its working fine,

![image](https://user-images.githubusercontent.com/18699624/151303102-1011f5a6-a043-4b51-9281-a9a9c361b1cf.png)

**Comment by rgnarok** [comment]
Creds are club01@mailinator.com
Kush96agra@
Alos create the club frm the app and check i did this way

**Comment by stevekamps** [comment]
works. Closing
