### ISSUE TITLE
Incorrect message comes up for clubs after their 3 search attempts with the search filter 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#424]
Incorrect message comes up for clubs after their 3 search attempts with the search filter . See attached

It should be the same message that comes up for coaches......

Activate the Advanced Search Filter enabling you to search for all Athletes on the VU Platform by Gender, Availability, Graduation Year, Position, State, City, School Jersey Number, Club, and Club Jersey Number. Go Premium Now!!
![IMG_9880](https://user-images.githubusercontent.com/77851393/150655090-2f0f15f7-2551-4ac8-9691-8832e7c7781c.PNG)

**Comment by rgnarok** [comment]
Done
