### ISSUE TITLE
Incorrect Popup when athlete clicks on wishlist on IOS when not premium 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#426]
Incorrect Popup when athlete clicks on wishlist on IOS when not premium . See attached.

The popup message should be.......

Add Colleges to your Wish List that meet your Athletic and Academic preferences. Colleges will be notified of your interests in their program. Go Premium Now!!
![Screenshot 2022-01-22 at 2 03 33 PM](https://user-images.githubusercontent.com/77851393/150655469-2e841ac6-d276-4e1a-87df-070d84b287e7.png)

**Comment by ShikharVayuz** [comment]
![Screenshot_20220127-165045](https://user-images.githubusercontent.com/86296418/151349349-c58a155c-3d02-4b74-a40a-dac513664618.png)
