### ISSUE TITLE
Athlete Edit Profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#427]
When adding additional playing experiences to your profile,   Under the College type please remove the line that says "Do you wish to be recruited to play University volleyball.  See attached
![IMG_9882 (2)](https://user-images.githubusercontent.com/77851393/150655742-7a183592-172a-4a00-b3a1-a94b73daa320.PNG)

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/151207216-b8fb0d90-1745-41c8-b41a-7d253a98318b.png)
Remove this yes and no too
