### ISSUE TITLE
Non-Premium Athlete = Allow them to see Rosters 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#431]
Please allow a non-premium athlete to be able to see the player roster badges if they search for a high school team, club team, College team, etc.

**Comment by technicalbirdVayuz** [comment]
Configured for current roaster in Web

**Comment by ShikharVayuz** [comment]
This was already configured in the app

**Comment by stevekamps** [comment]
Not working on IOS version 7 - see attached
Not working on web version either. It says they have to go premium

https://user-images.githubusercontent.com/77851393/151023112-82298fc1-1977-4678-a03f-d50f86aefe41.MP4

**Comment by technicalbirdVayuz** [comment]
We enabled only Current Roaster, For Teams it needs to be configured

**Comment by technicalbirdVayuz** [comment]
Moving to #421
