### ISSUE TITLE
Signed Athlete section not showing on CLUB ABC on IOS 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#432]
Signed Athlete section not showing on CLUB ABC .  Just a grey screen appears for the athlete profile 
- See attached video

clubabc@mailinator.com
Volleyball11$

https://user-images.githubusercontent.com/77851393/150691826-d8845326-f699-4c31-9b03-fabbd888fda6.MP4

**Comment by rgnarok** [comment]
Working fine in android @technicalbirdVayuz

**Comment by stevekamps** [comment]
working now. closing
