### ISSUE TITLE
Coach - Edit Profile on IOS 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#433]
Coach - Edit Profile on IOS issue.
- Tried adding a coaching position to my profile but it says "cannot leave State empty". See video.  The state was selected 
tomjones@mailinator.com
Volleyball11$

https://user-images.githubusercontent.com/77851393/150692405-3c852c63-5ff3-4b9b-b31b-7c6e67210023.MP4

**Comment by ShikharVayuz** [comment]
@rohitrvayuz This issue has not incurred on android please check for ios as well.

**Comment by stevekamps** [comment]
No it still does not work on the IOS.  Now the cities arent coming up either for each of the States. Please see attached 

https://user-images.githubusercontent.com/77851393/150875082-a99b7f1d-c9bf-4a86-b921-d29c80141d19.MP4

**Comment by rgnarok** [comment]
@technicalbirdVayuz this is wokring fine on android device

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/151404973-b4c8c9b6-d518-4c97-b210-c22d93b9a8bf.MP4

still not working on IOS version 9

**Comment by rohitrvayuz** [comment]
https://drive.google.com/file/d/1P4Mc9JRtjrhHPG07VqzI63y5k8-BkoHT/view?usp=sharing

**Comment by stevekamps** [comment]
The issue arises when you try to add a college coaching position.  The club and school additions are working

**Comment by rohitrvayuz** [comment]
> The issue arises when you try to add a college coaching position. The club and school additions are working

Ok. Will check again.

**Comment by rgnarok** [comment]
@rohitrvayuz  please update here

**Comment by ShikharVayuz** [comment]
@rgnarok Its fixed.
