### ISSUE TITLE
Coach Edit Profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#434]
In Edit profile section for a coach - When adding a College coaching position it only needs to say College. Not college and University
![Screenshot 2022-01-23 at 11 11 42 AM](https://user-images.githubusercontent.com/77851393/150692457-269d4876-d70f-4302-b062-2875ce4233b3.png)

**Comment by rgnarok** [comment]
Done
