### ISSUE TITLE
Need to be able to click on who is attending events 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#436]
Need to be able to click on who is attending events.  For both a hosted event or another public event.  This will be important for coaches to be able to see who is attending tournaments.  This feature is working on the web but not on the IOS 
![IMG_9902](https://user-images.githubusercontent.com/77851393/150693574-36c2cbe3-3950-4fc0-96e8-6b2a96aef1ef.PNG)
![IMG_9901](https://user-images.githubusercontent.com/77851393/150693577-a1f2cccf-c35e-445e-b622-3b50fbeb9a02.jpg)

**Comment by rgnarok** [comment]
Done
