### ISSUE TITLE
High School coach - No virtual bench required - Apps

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#437]
High School coach - No virtual bench required - Apps

Please see screen shot of high school coach - tomjones@mailinator.com      Volleyball11$

Since he is a high school coach he does not require the virtual bench as there is no premium for high school coaches 
![Screenshot 2022-01-23 at 12 11 13 PM (1)](https://user-images.githubusercontent.com/77851393/150694212-5025ccc7-ccfd-4adf-8267-b609bb1cae46.png)

**Comment by ShikharVayuz** [comment]
@stevekamps 
https://docs.google.com/spreadsheets/d/1ARK3HODV5_yWWq9ieR7zNcIn8UtbqZ0j1mFIwZUzbd4/edit#gid=1969783397
According to this sheet school coach does have premium and we have integrated the same flow in web. Please let us know what needs to be done.

**Comment by stevekamps** [comment]
OK then please add the premium into the hamburger menu and the premium features for the high school coach.  These are not included in the app right now.  Please also add the virtual bench to the high school coach hamburger menu with the correct messaging if they arent premium as per other coaches.

**Comment by rgnarok** [comment]
School Coach Premium (View club signed athletes player badges, club teams player badges, and College Committed athlete badges | Cannot view profiles of athletes they are not united with. No search Filter or Virtual Bench || Add Premium tab on school coach with the following Premium Feature for $25/Yr)
![image](https://user-images.githubusercontent.com/85341053/151307939-8f68ba1d-3803-4ed2-b228-91764beef4ea.png)
![image](https://user-images.githubusercontent.com/85341053/151307970-246e973b-9b7b-4d0d-ac69-9d6c99e22562.png)

kushagra11@mailinator.com
Kush96agra@
Still options on the app but on web wokring fine
