### ISSUE TITLE
Spelling Error on Athlete College signup - App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#439]
Spelling Error on Athlete College signup - App 
- you spelled College wrong 
![Screenshot 2022-01-23 at 12 38 57 PM (1)](https://user-images.githubusercontent.com/77851393/150695335-8e3db8cb-d21f-4464-85ea-1e6da0e10e2d.png)
-

**Comment by rgnarok** [comment]
Done
