### ISSUE TITLE
Coach >> Profile >> edit coaching information

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#44]
Edit coach information change province to state also I have choose coaching level college and it is showcasing school in the profile and edit profile plus it is not showcasing the details correctly
![image](https://user-images.githubusercontent.com/85341053/130039243-dd9f9de7-ec21-4113-a027-074a5ce84460.png)

**Comment by technicalbirdVayuz** [comment]
-  Edit coach information change province to state  - Done
-  I have chosen coaching level college  it is showcasing school in the profile - Please recheck now ( by signing up with new user)
-  and edit profile   it is not showcasing the details correctly, Please check & specify the details which are not coming correctly

Also, please add only one issue in the thread.

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/131389042-fbd046bb-c598-4428-9a67-9216ed45e27f.png)
Still showcasing club province instead of state
![image](https://user-images.githubusercontent.com/85341053/131389271-dc8f4e8c-a4bf-4a42-b1af-00e4e3d22c88.png)
Club state and city in edit profile not coming up

**Comment by technicalbirdVayuz** [comment]
PLs check

**Comment by technicalbirdVayuz** [comment]
Also, it takes time to load city & state. You need to wait
