### ISSUE TITLE
Athelte signup - App - Remove question

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#440]
Athlete signup - App - Remove the following question:

Do you wish to be recruited to USports?
![Screenshot 2022-01-23 at 12 42 22 PM (1)](https://user-images.githubusercontent.com/77851393/150695464-c68c7659-9a15-4ec5-8908-1dbbea1a1332.png)

**Comment by rgnarok** [comment]
Done
