### ISSUE TITLE
College - Can't search for atheltes to add to your committed athletes - App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#441]
using maroof.institute@gmail.com (Mkn123@#)

Lists all atheltes on the platform but can't search for one to add.

On the web it won't allow me to add committed athletes at all as it says I am not premium.  This should not be a premium feature

![Screenshot 2022-01-23 at 12 53 30 PM](https://user-images.githubusercontent.com/77851393/150695751-61ca2ea8-d8de-4f3c-8de6-f59fa61cc8ff.png)

**Comment by rgnarok** [comment]
@stevekamps  we discuss at time of Canada that the institution needs to buy either free or paid account and in free they can't access the committed athletes without paying to these sections

**Comment by rgnarok** [comment]
This is wokign fine on android @technicalbirdVayuz

**Comment by stevekamps** [comment]
working now . closing
