### ISSUE TITLE
Committed Athletes not showing on APP for College XYZ

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#444]
collegexyz@mailinator.com
Volleyball11$

When logged in as College XYZ the committed athletes are not showing
![Screenshot 2022-01-23 at 1 43 50 PM (1)](https://user-images.githubusercontent.com/77851393/150697339-c465a014-781b-491e-ac2d-dfcb692afd7e.png)

**Comment by rgnarok** [comment]
Done
