### ISSUE TITLE
Capatilize the "U" on About Us and Contact Us on the App hamburger menu

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#445]
Capatilize the "U" on About Us and Contact Us on the App hamburger men
![Screenshot 2022-01-23 at 1 53 49 PM](https://user-images.githubusercontent.com/77851393/150697630-45bb36ab-5538-476f-b44c-b760de3452d2.png)
u

**Comment by rgnarok** [comment]
Done
