### ISSUE TITLE
Coach >>Profile >> Volleyball information

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#45]
Add section of the other as shared in the documentation 
![image](https://user-images.githubusercontent.com/85341053/130039912-6f5aff25-518c-4960-9bc4-f513f48828d7.png)

**Comment by technicalbirdVayuz** [comment]
#11

**Comment by technicalbirdVayuz** [comment]
Closing this too #11 @rgnarok
