### ISSUE TITLE
Add a "b" in volleyball email at end of terms of service 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#453]
Add a "b" in volleyball email at end of terms of service. currently the email address is missing a b in volleyball

How to Contact Us:
Should you have questions or concerns about the Terms of Reference, please contact us at info@volleyballunite.com

**Comment by technicalbirdVayuz** [comment]
It will be done when we updated content #398
