### ISSUE TITLE
Volleyball Net on Homepage 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#455]
The background image on homepage seems to be off center compared to Canada. See attached.  Please add the net on the cell phone view. 
![Screenshot 2022-02-01 at 8 33 27 AM](https://user-images.githubusercontent.com/77851393/152000903-3c43a384-c6be-49cf-941a-493ed432477a.png)
![Untitled](https://user-images.githubusercontent.com/77851393/152000913-8da26777-1989-4815-b2ac-53f86ebf1bba.jpg)
![Untitled2](https://user-images.githubusercontent.com/77851393/152001029-326e682e-4e57-4653-8fa2-3d5c8fe4744a.jpg)

**Comment by stevekamps** [comment]
![Home  Volleyball Unite](https://user-images.githubusercontent.com/77851393/152001296-3dc257d7-72de-43ee-be88-279450e1b8d8.png)

**Comment by vayuzpriya** [comment]
![Screenshot from 2022-02-04 12-47-25](https://user-images.githubusercontent.com/81085431/152487806-cf76e542-d1bb-4be6-8498-336d1d2425e5.png)
![Screenshot from 2022-02-04 12-47-23](https://user-images.githubusercontent.com/81085431/152487815-ae725206-dfbe-4625-adbe-633c981cb827.png)

**Comment by rgnarok** [comment]
@stevekamps  this is fixed please check and confirm
