### ISSUE TITLE
Changes to hamburger menu on Cell phone web view 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#456]
1. Please capitalize the "U" on SIgn Up, the "I" on Sign In, and the "s" on Terms of Service.  
2. Add the word "Us' behind About so we are consistent

2. Move Contact Us to the bottom of the list 
<img width="375" alt="Screenshot 2022-02-01 at 8 34 10 AM" src="https://user-images.githubusercontent.com/77851393/152001752-64a7db8e-5c5f-4078-bd20-52f4af5db92e.png">

**Comment by technicalbirdVayuz** [comment]
Build was not deployed, yesterday. Please check now
![Uploading image.png…]()

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153138733-a9275c73-b38d-4a9a-a514-b666ba4983a3.png)

**Comment by technicalbirdVayuz** [comment]
We will update the build on Production
