### ISSUE TITLE
Change web URL to term-service

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#457]
currently the URL for Terms of Services is the following:
https://www.volleyballunite.com/term-condition

Please change to https://www.volleyballunite.com/term-service

**Comment by technicalbirdVayuz** [comment]
Fixed On Heroku

**Comment by stevekamps** [comment]
push to .com

**Comment by technicalbirdVayuz** [comment]
Done, Please check at https://www.volleyballunite.com/term-service
