### ISSUE TITLE
Terms of Service 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#458]
1.  Remove the extra space on Terms of Service between items 6 and 7
2. Add a space after the period in #8 
![Terms   Condition  Volleyball Unite](https://user-images.githubusercontent.com/77851393/152003269-cffdd13f-7759-480d-aa25-3219955aab7e.png)
![Terms   Condition  Volleyball Unite (1)](https://user-images.githubusercontent.com/77851393/152003278-e5fbef84-71d4-4c4d-bd33-2477099e6521.png)

**Comment by rgnarok** [comment]
This is done @stevekamps  please check
