### ISSUE TITLE
School Coach - No premium tab in Hamburger menu

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#459]
School Coach - No premium tab in Hamburger menu

**Comment by technicalbirdVayuz** [comment]
Added in Web

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153142741-695b6a75-f63d-4cee-843f-d6425f0477c1.png)
![image](https://user-images.githubusercontent.com/18699624/153142789-70cda92e-4425-4440-a686-a319061e1fe8.png)

**Comment by ShikharVayuz** [comment]
![Screenshot_20220209-174738](https://user-images.githubusercontent.com/86296418/153199594-25b6524a-849b-4043-9fd1-f9725f91cc15.png)
