### ISSUE TITLE
Users >> Subscription >> Price

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#46]
The subscription price added on the backend is not getting reflected on the payment screen
![image](https://user-images.githubusercontent.com/85341053/130040952-340d9a5f-3231-4a0b-a96f-3c237ac76b47.png)

**Comment by technicalbirdVayuz** [comment]
Pls share the credentials

**Comment by rgnarok** [comment]
@technicalbirdVayuz kush15@mailinator.com password Kush96agra@

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please sign up again & check. There are changes made in the signup values. based on that you will receive the updated value in the payment screen
