### ISSUE TITLE
School Coach - Should not be able to search for athletes

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#460]
School Coach - Should not be able to search for athletes. They also do not need a virtual bench

This was not part of the premium features for school coach

**Comment by technicalbirdVayuz** [comment]
Working in Web. Checked

**Comment by ShikharVayuz** [comment]
Disabled the advance filter option in app for School Coach.

**Comment by rgnarok** [comment]
Working properly
