### ISSUE TITLE
Club - Non Premium - IOS App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#461]
Club - Non Premium. When they click on events in the hamburger menu they get incorrect message.  

Should say - Creation of Events is accessible to Premium Users. Go Premium Now
![IMG_0074](https://user-images.githubusercontent.com/77851393/152438919-88adad39-4c0f-40a2-b36e-bb653fb18b66.PNG)

**Comment by ShikharVayuz** [comment]
Duplicate #478
