### ISSUE TITLE
Coach - Issues. Already verified, Can't search for an athelte 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#466]
Coach - Issues. Already verified, Can't search for an athlete

Dan is already verified.  He can't search for the athlete Ria.

COlleges come up when he is searching and the red button telling him to get verified comes up. He is already verified.  

https://user-images.githubusercontent.com/77851393/152441204-39afe46c-fc3a-409a-968e-ea724141aac1.MP4

**Comment by rgnarok** [comment]
Working fine
