### ISSUE TITLE
About Association for School Sign up - Web 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#468]
![image](https://user-images.githubusercontent.com/77851393/152443200-22156192-48f4-40fd-a448-d2589cf65130.png)

Change to About School

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/152940791-228cfd27-6831-409e-ac08-d1b9e1f0d9db.png)
