### ISSUE TITLE
Incorrect Notifications for School sign up and not consistent between web and app 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#469]
Please put the same notifications for both web and App as below:

- Use our Share App feature to Invite your Coaches and Athletes to the VU Community
- Create your School Teams and Add Players to the Rosters
- Edit your School Profile and Add all of your Coaching Staff Details 
- Welcome to Volleyball Unite!! Enjoy all the features and benefits of being a part of this community

**Comment by technicalbirdVayuz** [comment]
@stevekamps, Can you share a doc for all the notifications corresponding to types, We have changed this multiple times but every other time we have a new set of text provided

We have closed the signup for coach here
- https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/issues/248

now a different set of notifications has been provided

**Comment by technicalbirdVayuz** [comment]
High School Association does not have Roaster. Please share the updated text 

For now, integrated them into web

![image](https://user-images.githubusercontent.com/18699624/153151212-98f4070b-12b9-41a4-8306-1c39b53168ec.png)

**Comment by rgnarok** [comment]
Working fine
