### ISSUE TITLE
Club Web - Add Search Filter 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#471]
Club Web - Add Search Filter .  It appears on the App but not on the web version

**Comment by technicalbirdVayuz** [comment]
Ok. As per the doc, Search filters should be there for all types of associations.

Please check & confirm

**Comment by stevekamps** [comment]
Only need search filter and virtual bench for club and college organizations.

Do not need for School or Association

**Comment by technicalbirdVayuz** [comment]
Ok. Removed in Web

**Comment by ShikharVayuz** [comment]
Removed advance search filter for ASSOCIATION_PROVINCIAL and ASSOCIATION_HIGHSCHOOL

**Comment by rgnarok** [comment]
Done
