### ISSUE TITLE
CLub App - Premium Features - Change Association to "Premium Features"

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#472]
CLub App - Premium Features - Change Association to "Premium Features"  or "Club"

This can be consistent for all users whatever is easier.  

Same issue for College.  Maybe just change all users to to "Premium Features" 

![Screenshot 2022-02-03 at 4 16 42 PM](https://user-images.githubusercontent.com/77851393/152445423-25844f2b-fc6d-4b5b-8ef2-d546fbc73e99.png)

**Comment by rgnarok** [comment]
Done
