### ISSUE TITLE
CLub - App - When they click on Events in hamburger menu

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#473]
CLub - App - When they click on Events in hamburger menu and then events as a non premium an incorrect message comes up 
![Screenshot 2022-02-03 at 4 20 19 PM](https://user-images.githubusercontent.com/77851393/152445757-db3ea566-88b7-473a-8408-20f8607657c4.png)

**Comment by stevekamps** [comment]
On the web nothing is coming up when they click on events

![image](https://user-images.githubusercontent.com/77851393/152445881-46b3e263-00b9-4e33-a27f-c3f65e873ddc.png)

**Comment by technicalbirdVayuz** [comment]
https://user-images.githubusercontent.com/18699624/152926313-b987ee25-5180-4f9b-992d-bc9435cae343.mp4

Hi,

Can you share screen recording for the web? The text is visible at the end irrespective of location from where it is clicked

**Comment by stevekamps** [comment]
It is fine now on the web.  But we need the correct message to appear on the app

**Comment by rgnarok** [comment]
Working fine
