### ISSUE TITLE
Premium Features and Functionality

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#476]
There is a lot of inconsistent language, functionality, and messages between the web and app.  

- Please make the language below is consistent for all users on the web and the app

- Please ensure that what is described below is fully functioning on the web and app 

- Please ensure that the correct messages are appearing on web and app if a user is not premium and they click on one of these features. 

Premium Content Message

1.	Athletes (School/Club)

-	Search for all College Volleyball Programs in the USA using our POWERFUL search filters (search by State, City, Region, Conference, Division, Tuition, etc)
-	Add your favorite volleyball programs to your College Wish List
-	View all Committed Athletes on College rosters
-	View all Club signed Athletes 
-	View all Club rosters
-	View all School rosters 
-	Unlock the endorsement profile section and get endorsements from your coaches
-	Up to 1 GB of image/video posts on your feed for 1 year
-	Receive a PREMIUM badge to showcase your Athlete profile

2.	Athletes (All “Other” types & College Athletes)
-	View all Committed Athlete on College rosters
-	View all Club signed Athletes
-	View all Club rosters
-	View all School rosters 
-	Receive a PREMIUM badge on your Athlete profile

3.	Coaches (Club & College)

-	Search for Athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club,  Jersey Number, etc)
-	Access to full profiles of all Athletes on Volleyball Unite
-	Access to all Committed Athletes on College rosters
-	Access to all Club signed Athletes 
-	Access to all Club rosters
-	Access to all School rosters 
-	Add prospective athletes to your Virtual Bench 
-	Receive a PREMIUM badge on your Coach profile

4.	Coaches (School)
-	View all Committed Athlete on College rosters
-	View all Club signed Athletes
-	View all Club rosters
-	View all School rosters 
-	Receive a PREMIUM badge on your Coach profile
-	
5.	Organizations
a.	Colleges
-	Search for Athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club,  Jersey Number, etc)
-	Access to full profiles of all Athletes on Volleyball Unite
-	Access to all Committed Athletes on College rosters
-	Access to all Club rosters
-	Add prospective athletes to your Virtual Bench 
-	Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
-	Created Events will also be searchable by all Users (i.e. High School Camp)
-	Mobile phone calendar event synchronization
-	Receive a PREMIUM badge to showcase your College profile

b.	Clubs

-	Search for Athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club,  Jersey Number, etc)
-	Access to full profiles of all Athletes on Volleyball Unite
-	Access to all Committed Athletes on College rosters
-	Access to all Club rosters
-	Add prospective athletes to your Virtual Bench 
-	Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
-	Created Events will also be searchable by all Users (i.e. High School Camp)
-	Mobile phone calendar event synchronization
-	Receive a PREMIUM badge to showcase your Club profile

C. Schools

-	View all Committed Athletes on College rosters
-	View all Club signed Athletes 
-	View all Club rosters
-	View all School rosters 
-	Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
-	Created Events will also be searchable by all Users (i.e. High School Camp)
-	Mobile phone calendar event synchronization
-	Receive a PREMIUM badge to showcase your School profile

D. Associations

-	View all Committed Athletes on College rosters
-	View all Club signed Athletes 
-	View all Club rosters
-	View all School rosters 
-	Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
-	Created Events will also be searchable by all Users (i.e. Regional Camp)
-	Mobile phone calendar event synchronization
-	Receive a PREMIUM badge to showcase your Association profile

6.	. Referee
-	No premium upgrade available 

7.	Retired 	

-	 View all Committed Athletes on College rosters
-	View all Club signed Athletes 
-	View all Club rosters
-	View all School rosters

**Comment by technicalbirdVayuz** [comment]
For Retired, as per the original requirements, we do have a premium option.

For Referee, we do not have Premium on the header, So no text added there 

for rest of all types, we have updated the text on the web,

**Comment by rgnarok** [comment]
@ShikharVayuz  School premium text on app is not same to web
College premium web and app text not same please copy the web exactly
Association premium web and app text not same please copy the web exactly
Retired premium web and app text not same please copy the web exactly
