### ISSUE TITLE
Incorrect message coming up when COllege Maroof tries to clik on events in the hamburger menu 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#478]
Incorrect message coming up when COllege Maroof tries to click on events in the hamburger menu
![Screenshot 2022-02-04 at 5 22 26 PM](https://user-images.githubusercontent.com/77851393/152620220-32ab1134-06fa-42b3-a5d3-489a02d3cd61.png)

**Comment by technicalbirdVayuz** [comment]
Duplicate #486

**Comment by technicalbirdVayuz** [comment]
Duplicate #481
