### ISSUE TITLE
Athlete >> Verification request

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#48]
No need to show the verification option from the coaches who are not verified or premium. As you can see the coach kushagra is not verified but it is giving an option of verification
![image](https://user-images.githubusercontent.com/85341053/130356319-9670dea1-6235-43c5-b38c-dbaaa41062cb.png)
![image](https://user-images.githubusercontent.com/85341053/130356549-0b08e981-2734-4e03-afab-dc7b45f06105.png)

**Comment by technicalbirdVayuz** [comment]
Please check, validation added for coaches

**Comment by technicalbirdVayuz** [comment]
Code will be live in 10 min

**Comment by rgnarok** [comment]
Didnt get what is added?

**Comment by technicalbirdVayuz** [comment]
Following are the cases added, review required
- In case of a searched user is of type association, Request Verification button will appear in all the cases
- In the case of the user who is searching is of Coach or Athlete type, Request Verification button will come with those search results that have their profile verified already

**Comment by rgnarok** [comment]
Athlete can only be verified by coach still organisation are giving the option
![image](https://user-images.githubusercontent.com/85341053/131388638-75f813d9-8f9c-465d-92fc-2599a2458d95.png)

**Comment by technicalbirdVayuz** [comment]
Please confirm
- If a coach is searching then the Request Verification button will come with those search results that have their profile verified already (only coaches) & association
- If Athlete is searching then the Request Verification button will come with those who are verified Coaches only

**Comment by rgnarok** [comment]
If a coach is searching then the Request Verification button will come with those search results that have their profile verified already (only coaches) & association

- Only association can verify no other coaches can verify

If Athlete is searching then the Request Verification button will come with those who are verified Coaches only

**Comment by rgnarok** [comment]
[Verification Process (3).docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/7082357/Verification.Process.3.docx)
Check this @technicalbirdVayuz

**Comment by technicalbirdVayuz** [comment]
Please review
