### ISSUE TITLE
Public Events 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#482]
Add the red icon that notifies people that they have to click on the 3 dots to attend an event.  It is too difficult to find now
![Screenshot 2022-02-06 at 12 52 34 PM](https://user-images.githubusercontent.com/77851393/152698921-cb62091b-3da4-411c-80b5-d76d54ee3be9.png)

**Comment by ShikharVayuz** [comment]
Have changed the color of icon to red.

**Comment by stevekamps** [comment]
I don't see this on version 9 of the app

**Comment by ShikharVayuz** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/86296418/153402402-cd194d1c-e992-4194-937b-75c0c2317eb2.png">

**Comment by stevekamps** [comment]
Can we add this red button on bottom or in place of the 3 dots?
![View recent photos](https://user-images.githubusercontent.com/77851393/153439166-29ff1b59-1418-4fce-9f90-aab2c85c4dc8.png)

**Comment by rgnarok** [comment]
3 dots done
@ShikharVayuz  check the comment by @stevekamps
