### ISSUE TITLE
Cannot add previous college coaching expereince to profile 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#485]
annjames@mailinator.com
Volleyball11$

Cannot add previous college coaching experience to profile 

State error comes up. Have reported this in the past and you said it was fixed. It is not fixed

https://user-images.githubusercontent.com/77851393/152699488-f11b1d80-ff61-4f6f-9674-330b06b725d9.MP4

**Comment by rgnarok** [comment]
Done
