### ISSUE TITLE
Non-Premium club click on events in hamburger menu the incorrect message comes up 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#486]
Non-Premium club click on events in hamburger menu the incorrect message comes up
![Screenshot 2022-02-06 at 1 14 48 PM](https://user-images.githubusercontent.com/77851393/152699679-0b8311f5-764c-4b42-803d-683eeb763f09.png)

**Comment by rgnarok** [comment]
Done
