### ISSUE TITLE
No Premium listed in hamburger menu for coach 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#489]
![Screenshot 2022-02-06 at 1 31 10 PM](https://user-images.githubusercontent.com/77851393/152700228-864d4890-b978-4dcd-a6a3-1f13a0bcc305.png)

**Comment by stevekamps** [comment]
not showing on version 9 of the app

**Comment by rgnarok** [comment]
Done
