### ISSUE TITLE
Athlete >> Search Filters

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#49]
No option to access the filters to add the colleges on the wishlist
![image](https://user-images.githubusercontent.com/85341053/130357127-da2a724f-6ade-4477-8722-7f2758840960.png)

**Comment by technicalbirdVayuz** [comment]
It should be on Search bar, Please confirm

**Comment by technicalbirdVayuz** [comment]
Please provide the text: 
![image](https://user-images.githubusercontent.com/18699624/130398922-03b3d54a-df25-4b48-ab2a-b9126314258f.png)

**Comment by technicalbirdVayuz** [comment]
UI needs to be fixed. PLease review the functional part @rgnarok

**Comment by rgnarok** [comment]
No option to add on wishlist on the profile page of the college, rest the functionality is working fine
![image](https://user-images.githubusercontent.com/85341053/130613462-30477945-705a-451a-88a8-27fbe46d21a0.png)

**Comment by technicalbirdVayuz** [comment]
Please report this as a different issue. Original issue has been resolved

**Comment by rgnarok** [comment]
The search filter need to work 3 times but it is working for 4 in this what i did was i search 2 times then press resent than again it works for 2 times

**Comment by vayuzpriya** [comment]
![Screenshot from 2021-09-08 19-09-11](https://user-images.githubusercontent.com/81085431/132520130-b1f495bc-c9f9-40ec-b670-3c0ae65eba1e.png)
![Screenshot from 2021-09-08 19-09-08](https://user-images.githubusercontent.com/81085431/132520146-f23cb9a8-dcad-4614-857f-2e45adf314e3.png)
