### ISSUE TITLE
Web >> OTP >> Label text is missing whch is added on the doc

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#493]
![image](https://user-images.githubusercontent.com/85341053/153540940-c9878269-9f9b-484a-a215-3052f10266a8.png)
![image](https://user-images.githubusercontent.com/85341053/153541008-bcba5705-490f-4039-863a-2ffc5c15eb6e.png)

**Comment by rgnarok** [comment]
@technicalbirdVayuz  working fine 
@stevekamps please check at your end

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153569605-c418a441-e0a3-458b-b384-e4467614056f.png)
Closing this
