### ISSUE TITLE
High school and State organisation

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#494]
![image](https://user-images.githubusercontent.com/85341053/153545634-cd23172f-36c1-407e-a13a-046f651825dd.png)
Virtual bench is visible in the web and the app too, no need to add the virtual bench also in this case

![image](https://user-images.githubusercontent.com/85341053/153546773-937cfde4-bdae-4c88-96b3-4411a0b27871.png)

**Comment by technicalbirdVayuz** [comment]
Fixed in Web

**Comment by ShikharVayuz** [comment]
Fixed in mobile : VB removed for ASSOCIATION_PROVINCIAL and ASSOCIATION_HIGHSCHOOL
