### ISSUE TITLE
We only need the +1 for the phone number.  Please remove 91

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#497]
We only need the +1 for the phone number.  Please remove 91

**Comment by ShikharVayuz** [comment]
@stevekamps This will be done with live release currently for testing purpose only we have integrated this.

**Comment by technicalbirdVayuz** [comment]
Removed from web

**Comment by ShikharVayuz** [comment]
Removed from app
