### ISSUE TITLE
Athlete >> Wishlist

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#50]
Wishlist option should be on the header as we have for virtual bench for the coach
![image](https://user-images.githubusercontent.com/85341053/130357351-5dca74bb-19cd-475f-8c69-1a87c2a519b4.png)

**Comment by technicalbirdVayuz** [comment]
Fixed, pls share the text for non premium user if click on that option

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/130606581-93cd12bb-e65c-4201-8639-8b323e4d162d.png)
Not yet visible plus the text will be, "Activate the advanced search filter enabling you to search for available colleges on the platform by Region, League, Division, Conference, Enrollment, Tuition, City, State.

**Comment by technicalbirdVayuz** [comment]
What is not visible?

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/130742029-c0bdf867-fd14-4e5e-8c49-f397f788254a.png)
If user click on Wishlist


![image](https://user-images.githubusercontent.com/18699624/130742157-7094314d-2aba-4436-b8ae-185fcd13f78e.png)
If user click on Filter /
