### ISSUE TITLE
Make the Athlete Premium feastures on the app the same as on the web. 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#500]
Search for all College Volleyball Programs in the USA using our POWERFUL search filters (search by State, City, Region, Conference, Division, Tuition, etc)

- Add your favorite volleyball programs to your College Wish List

- View all Committed Athletes on College rosters

- View all Club signed Athletes

- View all Club rosters

- View all School rosters

- Unlock the endorsement profile section and get endorsements from your coaches

- Up to 1 GB of image/video posts on your feed for 1 year

- Receive a PREMIUM badge to showcase your Coach profile

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/154022430-f10a59e8-881a-4709-9c3e-e5ef3772724d.png)

On the web it is not as written please correct
@technicalbirdVayuz

**Comment by technicalbirdVayuz** [comment]
1st, its an App Pointers, 2nd, please compare text with the #476 pointer, if there is any issue then please share creds, will check

@rgnarok

**Comment by stevekamps** [comment]
Closing. Refer to Item #476
