### ISSUE TITLE
Can't join a public event on web version. The app is working well 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#501]
Can't join a public event on web version. The app is working well .

There is nowhere to choose to attend on the web version

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153816889-a9799d78-ddf2-43e8-a164-2d74f625096e.png)
![image](https://user-images.githubusercontent.com/18699624/153817484-53b6872b-bf71-4d3b-bc8a-da4e02c7aaab.png)
On accepting

**Comment by rgnarok** [comment]
Working fine
