### ISSUE TITLE
When a user accepts a Unite in the notifications area in the app the unite does not happen.  

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#503]
When a user accepts a Unite in the notifications area in the app the unite does not happen. 

https://user-images.githubusercontent.com/77851393/153634534-a998da56-8771-4f31-8c8b-2e41d6a94829.MP4

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/154071437-b9b4d51c-2981-427a-97a5-690971c7b098.png)

![image](https://user-images.githubusercontent.com/85341053/154071848-ea8ae902-270e-48b0-9d40-9379f1618635.png)

I accepted the request from the app everything is updated in the notification but not visible on the app and the web unite section 
@ShikharVayuz @technicalbirdVayuz

**Comment by ShikharVayuz** [comment]
https://user-images.githubusercontent.com/86296418/154204808-5c6493e6-0eb3-4c0c-9040-eed15e344ed3.mp4

**Comment by ShikharVayuz** [comment]
https://user-images.githubusercontent.com/86296418/154204900-0f62e474-bdad-4e7e-a84e-51dd040f14cf.mp4

**Comment by ShikharVayuz** [comment]
https://user-images.githubusercontent.com/86296418/154205350-e736a8a8-8602-4a4c-9e79-6ad3c984ad28.mp4

**Comment by rgnarok** [comment]
@ShikharVayuz  recording not working

**Comment by technicalbirdVayuz** [comment]
> but not visible on the app and the web unite

The following issue has been reported for App only, If there is issue on web, please share the recording

**Comment by rgnarok** [comment]
Web - https://drive.google.com/file/d/1fJ-A6PUsBkvr_P6peRIcTCTZ63qgtdoZ/view?usp=sharing
App - 
![image](https://user-images.githubusercontent.com/85341053/154230435-7543fb81-0ad6-44bb-b081-003957a9f943.png)

![image](https://user-images.githubusercontent.com/85341053/154230477-334db981-9438-4154-b5c2-1a32fbce3da4.png)

Please run end to end flow by send a request in search and accept it from app notification, then check the web and app unite section no update only notifications are getting triggered
@technicalbirdVayuz @ShikharVayuz

**Comment by technicalbirdVayuz** [comment]
Fixed in Web
