### ISSUE TITLE
Change Province to State in the Academic profile area on the Web version 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#505]
Change Province to State in the Academic profile area on the Web version 

![Untitled](https://user-images.githubusercontent.com/77851393/153635957-7f43d6d2-4c90-4ad6-9bda-4131d29d33ee.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153817984-c84fa3df-460b-404b-aa82-f0266a7b1b54.png)
