### ISSUE TITLE
Other - Athlete - Remove fren 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#506]
Other - Athlete - Remove fren 

Team name - Ex. Falcons
League/Divison - Ex. FIVB
![Untitled2](https://user-images.githubusercontent.com/77851393/153636432-516a09a2-e72c-41bc-abaa-54a351eb49e2.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/153818292-ec224f41-6a33-4a95-8860-0a4591cfec3a.png)
