### ISSUE TITLE
Athlete >> Premium payment

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#51]
Payment is not happening it is loading and after a time it shows something went wrong
![image](https://user-images.githubusercontent.com/85341053/130357732-f29b6b92-59ec-447e-a5e1-a7a99ec89564.png)

**Comment by technicalbirdVayuz** [comment]
Please share the user credentials

**Comment by rgnarok** [comment]
arushi10@mailinator.com
pwd - Kush96aga@

**Comment by technicalbirdVayuz** [comment]
Its working fine, Please cross check. Checked on both local & heroku
