### ISSUE TITLE
Dates not appearing in App for athlete I am united with 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#510]
Dates not appearing in App for athlete I am united with 

CLub ABC should be 2019-Present

etc.

https://user-images.githubusercontent.com/77851393/153639022-85aa88a7-bf5c-4237-a6f1-236e7138cd81.MP4

**Comment by ShikharVayuz** [comment]
This is working fine.
