### ISSUE TITLE
Notifications coming through on IOS with a banner at top. Can this be removed?

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#516]
Notifications coming through on IOS with a banner at top. Can this be removed?
<img width="375" alt="Screenshot 2022-02-11 at 10 52 01 AM" src="https://user-images.githubusercontent.com/77851393/153644086-c76cb1e8-fba6-4d85-960a-656b2ad04fe9.png">

**Comment by rgnarok** [comment]
@ShikharVayuz  please add a proper pointer here
