### ISSUE TITLE
Organization message when they click on an athlete

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#518]
An organization cannot Connect with anyone 

The message says Connect with Beth Martin first to view the profile.

The message for Association and School should be:

"You cannot view Athlete or Coach Profiles as an Organization"

For a Club and College Organization the message should be:

"To view full profiles upgrade to Premium"

This is where it would be nice for all Organizations to be able to "Follow" other Organizations as dicussed.

![Screenshot 2022-02-11 at 4 00 59 PM](https://user-images.githubusercontent.com/77851393/153682896-fed8b2a0-3f9d-41d8-82eb-aff720c6753d.png)

**Comment by ShikharVayuz** [comment]
Configured in app.

**Comment by rgnarok** [comment]
@ShikharVayuz  for association and school there are both the messages coming remove the second one

**Comment by rgnarok** [comment]
@ShikharVayuz  sign in with the following creds:
hs1@mailinator.com
Kush96agra@
1. It is showcasing me the toast plus i can access the profile of the athletes in search >> Don't give access to profiles of athletes and coaches just show toast
2. If i click on association cards it is showcasing me the same toast" You cannot view Athlete or Coach Profiles as an Organization" >> Instead change the athlete and coach to Other organisations
Please do this for association types too not only school

**Comment by rgnarok** [comment]
@ShikharVayuz  check again not working, i searched kushagra and then i can access the profile for athletes and coaches
