### ISSUE TITLE
Athlete >> Profile >> Attending event detail

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#52]
Recurringevent details not coming up on the listing 
![image](https://user-images.githubusercontent.com/85341053/130358128-78196050-483a-471e-a98c-c3a1509759a7.png)

**Comment by technicalbirdVayuz** [comment]
Can you share the user credentials?

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/130572916-5466ae2c-a21d-48f2-a700-3fb8ff0fe647.png)
Fixed, please crosscheck
