### ISSUE TITLE
Cannot view group members 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#520]
Cannot view group members .  Goes to grey screen. Please see attached video

https://user-images.githubusercontent.com/77851393/153683410-93c03422-a870-4342-92cc-1219150cafec.MP4

**Comment by ShikharVayuz** [comment]
@stevekamps Please provide me with the credetials for the same because it is working fine at my end.

**Comment by stevekamps** [comment]
Still not working.  
annjames@mailinator.com
Volleyball11$

**Comment by rgnarok** [comment]
Checked for the same members still not working
