### ISSUE TITLE
Change Title of Premium Features  for Association 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#523]
Change Title of Premium Features  for Association 

Currently says "Provincial"

Change to "Association"
![Screenshot 2022-02-11 at 4 34 38 PM](https://user-images.githubusercontent.com/77851393/153684811-a9c46c64-7f3d-4aca-88ba-a901614aea47.png)

**Comment by stevekamps** [comment]
and change feastures to:

Associations

View all Committed Athletes on College rosters
View all Club signed Athletes
View all Club rosters
View all School rosters
Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
Created Events will also be searchable by all Users (i.e. Regional Camp)
Mobile phone calendar event synchronization
Receive a PREMIUM badge to showcase your Association profile

**Comment by technicalbirdVayuz** [comment]
Text is fine in Web, cross checked
