### ISSUE TITLE
Delete all test users except for the following................

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#526]
Delete all test users except for the following................

1. College XYZ
2. Club Ace
3. Parkland School
4. Beth Martin - Athlete
5. Blake Dane - Coach

**Comment by technicalbirdVayuz** [comment]
We will delete all the users, once we tested the app internally & check Review required pointers
- https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22Review+Required%22
