### ISSUE TITLE
Add a URL Ex. for Instagram address

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#529]
Ex. https://www.instagram.com/volleyballuniteusa/

**Comment by technicalbirdVayuz** [comment]
Configured in web also

**Comment by rgnarok** [comment]
@ShikharVayuz  not added in case of the app, make the same place holder 
![image](https://user-images.githubusercontent.com/85341053/154226511-54ae54bc-12b3-4c09-815a-e6d1d0f10633.png)

**Comment by ShikharVayuz** [comment]
Will review and update

**Comment by ShikharVayuz** [comment]
![Screenshot_20220217-113134](https://user-images.githubusercontent.com/86296418/154415044-c3281960-3d46-4677-8bfd-7f7846c8a891.png)
