### ISSUE TITLE
Coach >> Athlete verification notification

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#53]
Change the text of the notification to " Athlete name has requested for a profile verification"
![image](https://user-images.githubusercontent.com/85341053/130358359-16dab2b4-32ab-492e-915b-a75f66f1c619.png)

**Comment by technicalbirdVayuz** [comment]
Notification trigger sheet is required, the notification which is there is for a different purpose
