### ISSUE TITLE
Add Hyphens in Orgainzation phone numbers 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#530]
Add Hyphens in Organization phone numbers 

EX. 555-123-4567

**Comment by technicalbirdVayuz** [comment]
Placeholder changed in web also

**Comment by rgnarok** [comment]
On both web and app it is not working:

-  App : Sign up for all organisation types when adding phone number tell us more about you screen add Hyphens automatically 
- App: Add the same on edit profile section for the organisations
- Web: Sign up for all organisation types when adding phone number tell us more about you screen add Hyphens automatically ( Working properly in case of association please add like this)
- Web: Add the same on edit profile section for the organisations
@technicalbirdVayuz @ShikharVayuz

**Comment by technicalbirdVayuz** [comment]
Configured in web also
