### ISSUE TITLE
Vertical  - Please add a 1,2,3 to the feet drop down menu on web and app 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#534]
Vertical  - Please add a 1,2,3 to the feet drop down menu on web and app

**Comment by ShikharVayuz** [comment]
@stevekamps Can you please provide screenshots for the same.

**Comment by technicalbirdVayuz** [comment]
Configured in Web

**Comment by technicalbirdVayuz** [comment]
@ShikharVayuz 
![image](https://user-images.githubusercontent.com/18699624/154221540-9e41b441-58bf-48fb-8daa-73e76fd7c081.png)
Please add 1,2,3 options in the list

**Comment by stevekamps** [comment]
Please add in the App as well
