### ISSUE TITLE
Can't change subscription premium price for Association 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#535]
Can't change subscription premium price for Association.  $99.95
![subs](https://user-images.githubusercontent.com/77851393/154174909-205dffde-168a-4d1f-ae66-d072e7ea72c2.jpg)

**Comment by technicalbirdVayuz** [comment]
Removed that, Please try to change pricing based on the association types. Feel free to reopen if the discussion is required
