### ISSUE TITLE
Subscription Additions 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#536]
Please add the following Organizations to Colleges. We want to have 3 different price levels

College - NCAA = $249.95
College - NAIA = $199.95
Junior College = $149.95

They all get same premium features we just want to price them different

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please discuss this in detail.

It was not mentioned initially, we have made the changes initially for Coaches also. That would be an interation. Additional checks & functionality have to be incorporated. Please share this in the sheet.

Currently only Association can have only 1 pricing if its bind with college

**Comment by rgnarok** [comment]
@stevekamps this was not decided earlier that the college will have different subsciption on the basis if league or division, these are additional work now Please discuss and let us know what to do

**Comment by stevekamps** [comment]
Yes it was always that plan to have different price points for College.  

Please add subscriptions for NCAA College,  NAIA College, and Junior College

They all get the same features, we just want to have different price points

**Comment by rgnarok** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/85341053/155268314-d11190da-7649-4eab-8870-e617135efaa2.png">

<img width="675" alt="image" src="https://user-images.githubusercontent.com/85341053/155268352-3364cd3a-f7f8-43ff-ad52-e1b63cc3e511.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/85341053/155268385-f93e0b9d-99a3-44aa-84f8-2081127a97f4.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/85341053/155268416-1a16670e-d4b8-487b-9768-59734ded125d.png">

As you can see we have documented the same where we have a common price for the college, not on the basis of division so if this is required it is an additional work we can share the time and once approved by you we will make the required changes

**Comment by stevekamps** [comment]
Yes we want different college
Prices

**Comment by stevekamps** [comment]
Please make the change

**Comment by stevekamps** [comment]
I am closing this. Lets keep all Colleges the same price.
