### ISSUE TITLE
Arizona Clubs

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#537]
Here is the Arizona Clubs CSV.  I see that it is different from the Colorado one we sent.  Based on the previous one I am guessing we need to keep them all consistent? 

We really don't need an address as in the Colorado CSV.  The Arizona spreadsheet is based on the fields in VU USA.  Let me know if anything needs to be changed for the upload to work.

Steve
[Fwd_ Arizona Clubs.zip](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8077053/Fwd_.Arizona.Clubs.zip)

**Comment by technicalbirdVayuz** [comment]
Duplicate #532

**Comment by technicalbirdVayuz** [comment]
[Arizona.Volleyball.Clubs.2022.xlsx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8078033/Arizona.Volleyball.Clubs.2022.xlsx)

**Comment by technicalbirdVayuz** [comment]
Sharing the Finalised club & college format,

[College & Club Format.xlsx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8078142/College.Club.Format.xlsx)

Please note: if there is any change in any of the fields then we have to further make modifications in code & configure as per the updated columns. Now, Reference to what has been shared with us as **Arizona Clubs**, they have different columns, So we would need to make modifications. Let us know if we can have uniformity across columns

**Comment by stevekamps** [comment]
The Club fields you sent me above do not make sense for what the club profiles look like on the VU platform.  For example we don't need address.   There is no coach field for clubs, no team website, no enrollment, no tuition etc 

Can the fields we don't need (listed above) be left empty?

**Comment by technicalbirdVayuz** [comment]
Update:

We have used this file & updated it from the panel itself & its  working fine
The issue was with the State column its named **AZ** we updated it to **state**.

Sharing the updated doc 

[ClubFieldsUSA.ARIZONA.csv](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8106912/ClubFieldsUSA.ARIZONA.csv)
@rgnarok @stevekamps 

Out of total 147 shared club, 124 are the valid ones

**Comment by technicalbirdVayuz** [comment]
Please check the updated clubs now, & let us know in case of any issue

**Comment by stevekamps** [comment]
The admin name and email for all the Arizona clubs did not come through on the profiles 

What do you mean by clubs that are not valid?

**Comment by technicalbirdVayuz** [comment]
Duplicate Emails,

**Comment by technicalbirdVayuz** [comment]
Closing this, Feel free to open
