### ISSUE TITLE
Add Share App button to all Users in Hamburger menu

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#539]
Add Share App button to all Users in Hamburger menu

**Comment by ShikharVayuz** [comment]
Feel free to open again. Duplicate #527

**Comment by stevekamps** [comment]
Just don’t close it if it isn’t on the live app build. Communicate that it will be pushed to update on certain date. It was closed a week and new version of app was published but still not fixed. I don’t have time to check all these details. Make them happen

**Comment by ShikharVayuz** [comment]
![Screenshot_20220221-124855](https://user-images.githubusercontent.com/86296418/154907134-73326ed1-a50d-447d-8ffa-95cd6f1c51dc.png)

**Comment by ShikharVayuz** [comment]
Please check with version 1.3.3 if this issue still persists please share the credentials.
