### ISSUE TITLE
Can't sign in on App with newly created users. 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#548]
Can't sign in on App with newly created users.   I created users on the app.  Can't login with them.

jennsmith@mailinator.com
Volleyball11$

timdavies@mailinator.com
Volleyball11$

Please see screen recording.

I can't send a password reset either. it says username not found.

https://user-images.githubusercontent.com/77851393/155594417-5ba146b0-ef8c-4507-9b5c-f83db7b3f9ea.MP4

**Comment by technicalbirdVayuz** [comment]
https://drive.google.com/file/d/1Gkva3B8XtxyxKnUCg5sNpn1LgNATzWCY/view?usp=drivesdk

**Comment by technicalbirdVayuz** [comment]
We have added a check in the backend. you could check the flow, it would work normally. Please check after 15-20 min. web Build will be live by then
