### ISSUE TITLE
CLub not listed auto email - change wording

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#549]
Change wording circled on attached screenshot to the text below

Volleyball Unite is North America's Premier Volleyball Social Network for the entire community to UNITE. VU is the platform for Athletes, Coaches, Referees, Colleges, and Associations to socialize, share, and create connections.

![Untitled](https://user-images.githubusercontent.com/77851393/155596589-7f3e10a4-a0ca-45c9-a0f8-d69fb5670beb.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/155928189-46e0a053-cb8d-48f5-a72d-56d4fafd9f62.png)
The text has been changed multiple times. That's why its marked as iteration

**Comment by stevekamps** [comment]
I don’t need backlash. Change it
