### ISSUE TITLE
Coach >> premium

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#55]
In case the coach is not verified he cannot go for the premium 
![image](https://user-images.githubusercontent.com/85341053/130359472-854a1df0-52ce-44d4-99bc-0783d5bc29f7.png)

**Comment by technicalbirdVayuz** [comment]
Can you please share the complete flow?

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/130734682-f227ae67-f03e-4d28-b9e8-b0a25b408f32.png)

**Comment by technicalbirdVayuz** [comment]
Please check the flow now. Also, provide the relevant text too
