### ISSUE TITLE
Athlete signing up for a non-existant club not appearing after they do signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#550]
Athlete signing up for a non-existant club not appearing after they do signup 

Tim Black signed up and said he plays for Club M.  Club M was not a created club.  Club M then created an account but Tim Black is not appearing on their signed athlete's list.  This feature works in VU Canada

I can't even add Tim Black because he does not appear in the list of athletes to try to add.

timblack@mailiantor.com
clubm@mailinator.com

same password - Volleyball11$

**Comment by technicalbirdVayuz** [comment]
We have checked the flow & its working fine.

Please make sure the **ADMINISTRATOR EMAIL** (in the association form) matches the **CLUB ADMINISTRATOR'S EMAIL** (in the Athlete form) 

Entire Flow Video: 
https://drive.google.com/file/d/15gEr6rCPsOe6mf5U9ieu4Yfq8w4DxJWl/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
> I can't even add Tim Black because he does not appear in the list of athletes to try to add.

Also, This is not coming because Athlete is already signed to a club. Please check the flow again & let us know in case of any issues

**Comment by technicalbirdVayuz** [comment]
@rgnarok  please check the flow

**Comment by technicalbirdVayuz** [comment]
Checked the flow in the app also. Working fine

**Comment by rgnarok** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/156193665-e0226acc-8136-40af-9047-265a0fa6d42b.png">
I created a user and do the same on the app side it is not working please check

**Comment by rgnarok** [comment]
lorain10@mailinator.com
Kush96agra@
club301@mailinator.com
Kush96agra@
