### ISSUE TITLE
College Athlete does not need search filter

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#552]
College Athlete does not need search filter.  Search filter is not needed and is not part of the premium features for a College athlete.

Please remove the search filter.

**Comment by stevekamps** [comment]
We could leave it if it is easier and make it part of the premium features?  Not sure if this is how you set this up? Please advise.

Right now the message they get when they clcik on the red search filter is incorrect. See attached.
![Screenshot 2022-02-27 at 8 20 53 AM (1)](https://user-images.githubusercontent.com/77851393/155888912-91bcd0a7-c405-4add-88ce-085fa6a6e029.png)

**Comment by technicalbirdVayuz** [comment]
Configured in Web

**Comment by ShikharVayuz** [comment]
Configured in app

**Comment by technicalbirdVayuz** [comment]
#578
