### ISSUE TITLE
College Claim Process

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#553]
Please change the package features to the following:

Search for Athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club, Jersey Number, etc)
Access to full profiles of all Athletes on Volleyball Unite
Access to all Committed Athletes on College rosters
Access to all Club rosters
Add prospective athletes to your Virtual Bench
Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
Created Events will also be searchable by all Users (i.e. High School Camp)
Mobile phone calendar event synchronization
Receive a PREMIUM badge to showcase your College profile
![packagedetails](https://user-images.githubusercontent.com/77851393/155889494-9e2dfc63-821f-428b-a525-5d0036702db1.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/155930274-fd752003-a39d-4ce7-a70f-3ffe852732d9.png)

**Comment by technicalbirdVayuz** [comment]
Fixed
