### ISSUE TITLE
Remove and replace coach notification on signup - App

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#555]
Remove and replace coach notification on signup - App.

Replace the app circled notification with the notification from the web that I have circled.  The wed notifications are all correct.
![coachnotification](https://user-images.githubusercontent.com/77851393/155895993-27595477-84f8-453f-b339-513af56aa5a6.png)
![Screenshot 2022-02-27 at 11 50 18 AM](https://user-images.githubusercontent.com/77851393/155896003-58bbc714-d1b9-49ba-9339-494572f705fb.png)

**Comment by stevekamps** [comment]
Not fixed on my IOS

**Comment by rgnarok** [comment]
kush40@mailinator.com
Kush96agra@

@ShikharVayuz
