### ISSUE TITLE
Association - Adding Teams and Level - App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#557]
Association - Adding Teams and Level - App 

Level for Association needs to be dropdown menu of 
U13, U14, U15,U16, U17, U18, 19+

It is correct on the web but incorrect on the App

**Comment by rgnarok** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/157261137-98cecb9d-03d0-413d-8741-41c793023cff.png">

It is in the web but still there is no option on the app
![image](https://user-images.githubusercontent.com/85341053/157261434-96d585ee-fe0d-46e0-b532-15be15615b4b.png)

**Comment by ShikharVayuz** [comment]
@rgnarok Please close this if fixed
