### ISSUE TITLE
Incorrect Premium feastures on App for Association 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#558]
Incorrect Association features listed on the App when an Association clicks on Premium.  It is correct on the Web 

View all Committed Athletes on College rosters
View all Club signed Athletes
View all Club rosters
View all School rosters
Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
Created Events will also be searchable by all Users (i.e. Regional Camp)
Mobile phone calendar event synchronization
Receive a PREMIUM badge to showcase your Association profile

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/156868018-394ad839-e58e-479a-99df-b32284f8ed1c.png)
@stevekamps  working fine
