### ISSUE TITLE
Change High School Signup Athletic Director Phone Number to have hyphens 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#559]
Change High School Signup Athletic Director Phone Number to have hyphens (i.e. 555-123-4567)

Currently it only accepts a 10 digit number with no spaces or hyphens

**Comment by technicalbirdVayuz** [comment]
Can you please share the screen recording?

**Comment by technicalbirdVayuz** [comment]
Also, Please mention the label whether it belongs to app or web

**Comment by stevekamps** [comment]
Signup with any new high school or existing one and you will see.

All passwords for all users are the same and dashboard gives email

**Comment by stevekamps** [comment]
Both

**Comment by technicalbirdVayuz** [comment]
https://drive.google.com/file/d/18Ul_SY9Xs87vFmYVWI7iVmwtI-6_x4J5/view?usp=sharing
https://drive.google.com/file/d/1aE9ISacXqdrpJQ7ils3i0fwaezfrCzfp/view?usp=sharing

Please check both, its working

**Comment by stevekamps** [comment]
If they are working then close . I don’t have time to keep checking

**Comment by technicalbirdVayuz** [comment]
@ShikharVayuz Please crosscheck in the Apps

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/156867817-f6be3962-2009-4777-9ad2-4cb7a2ee0f7f.png)
@stevekamps working fine
