### ISSUE TITLE
Organisation >> Highschool

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#56]
I created high school but i the profile the added details are not showing
![image](https://user-images.githubusercontent.com/85341053/130361971-212d8575-4655-4ff1-b77a-c087617cd1b0.png)

**Comment by technicalbirdVayuz** [comment]
![screenshot](https://user-images.githubusercontent.com/18699624/130577424-43211504-b9b6-416b-9ae7-cac63c9b4bbe.png)
Details have been added. 

Need following other details
- Can you share the documentation where Coaching details have been provided? (/signup-high-school-coaching-staff-details) (This URL)
- Let me know what all fields need to be removed/hidden from the view profile
- What all fields can be changed in Edit Profile/ is there any documentation for the same?

**Comment by technicalbirdVayuz** [comment]
Please review from reported pointer & share clarity on the sahre pointers

**Comment by rgnarok** [comment]
- Can you share the documentation where Coaching details have been provided? (/signup-high-school-coaching-staff-details) (This URL)
![image](https://user-images.githubusercontent.com/85341053/131276681-a4cf552d-e389-4ef4-85ae-48787b70f66c.png)

- Let me know what all fields need to be removed/hidden from the view profile

- What all fields can be changed in Edit Profile/ is there any documentation for the same?

**Comment by technicalbirdVayuz** [comment]
Which all fields are public?

**Comment by technicalbirdVayuz** [comment]
Ok. Then no need to hide anything I guess. 


Pls review
