### ISSUE TITLE
change the App premium features for School 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#561]
change the App premium features to the following below 

C. Schools

View all Committed Athletes on College rosters
View all Club signed Athletes
View all Club rosters
View all School rosters
Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)
Created Events will also be searchable by all Users (i.e. High School Camp)
Mobile phone calendar event synchronization
Receive a PREMIUM badge to showcase your School profile

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/155943195-3781b979-a77e-4c2e-8d5a-7757af85624f.png)
This is correct please confirm again
