### ISSUE TITLE
School Can't purchase Premium on App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#562]
School Can't purchase Premium on App 

Just a spinning wheel occurs. See video 

https://user-images.githubusercontent.com/77851393/155896904-1c1263db-7f65-44fe-b75a-16b5cc590ddb.MP4

**Comment by technicalbirdVayuz** [comment]
Please share the credentials of the logged in user

**Comment by stevekamps** [comment]
Look at last high school I signed up 

- dashboard gives email login 
- all passwords are Volleyball11$

**Comment by technicalbirdVayuz** [comment]
@ShikharVayuz  Please check with these creds


- utahhighschool@mailinator.com
- Volleyball11$

**Comment by ShikharVayuz** [comment]
![Screenshot_20220301-092736](https://user-images.githubusercontent.com/86296418/156102139-75fe97b0-ab7c-4229-9db2-266477c20e80.png)
