### ISSUE TITLE
Changes to School Coach staff details Profile section 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#563]
Change the following by adding the word coach as below: On App and Web 

Boys Varsity Coach Name
Boys Junior Varsity Coach Name
Boys Freshman Coach Name
Girls Varsity Coach Name
Girls Junior Varsity Coach Name
Girls Freshman Coach Name

**Comment by technicalbirdVayuz** [comment]
@stevekamps there are other fields too other than a name like email & phone no. Do we need to add coach word there also?
@rgnarok @ShikharVayuz 
![image](https://user-images.githubusercontent.com/18699624/157015719-0dbc9d60-5a17-4378-8966-d96a5fec7ffe.png)

**Comment by stevekamps** [comment]
Sure let’s add Coach to all fields

**Comment by technicalbirdVayuz** [comment]
Fixed
