### ISSUE TITLE
College Premium Feastures on App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#565]
Change the College Premium features on App to the following:

- Search for Athletes with advanced search filters.(i.e. by Availability, Position, City, State, Club, Jersey Number, etc)

- Access to full profiles of all Athletes on Volleyball Unite

- Access to all Committed Athletes on College rosters

- Access to all Club rosters

- Add prospective athletes to your Virtual Bench

- Create "Public Events" for all of your Followers to view in their Feeds (i.e. Tournament, Camps,)

- Created Events will also be searchable by all Users (i.e. High School Camp)

- Mobile phone calendar event synchronization

- Receive a PREMIUM badge to showcase your College profile

**Comment by rgnarok** [comment]
This is already done
![image](https://user-images.githubusercontent.com/85341053/155940563-e9dd74ff-2909-491e-839f-024b157a1ca4.png)

**Comment by stevekamps** [comment]
Not on my version

**Comment by rgnarok** [comment]
https://play.google.com/apps/internaltest/4699001397503217387
@stevekamps  check this android app

**Comment by stevekamps** [comment]
I use Apple
