### ISSUE TITLE
Retired - Premium 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#566]
- remove the top 2 premium bullet points in the app.
- No Premium button available for retired on the App
![Screenshot 2022-02-27 at 12 49 43 PM](https://user-images.githubusercontent.com/77851393/155897568-188d1d3e-a95f-47ad-8bb7-a4db33c5e244.png)

**Comment by ShikharVayuz** [comment]
![Screenshot_20220301-092422](https://user-images.githubusercontent.com/86296418/156101897-0bf69282-c17e-4c18-93cc-a675ea72b3cb.png)

**Comment by ShikharVayuz** [comment]
![Screenshot_20220301-170804](https://user-images.githubusercontent.com/86296418/156162696-67316441-435e-4e5a-aa85-82ff331b1957.png)
