### ISSUE TITLE
Verify Head Coach Email 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#569]
Change the screenshot text to..........  Verify Head Coach Email
<img width="375" alt="Screenshot 2022-02-27 at 1 48 44 PM" src="https://user-images.githubusercontent.com/77851393/155902092-d9cb960a-4172-4434-9e8e-b0fb9163a313.png">

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/155939957-7fcd22b6-f65c-4ca6-ad81-685af3b8be00.png)
