### ISSUE TITLE
Change The word Association on Colleges, Clubs, Associaiton , High School pages

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#571]
Change The word Association on Colleges, Clubs, Association , High School pages.

Change to Organization. 

Or better yet change to what type of respective organization they are (i.e. Club, College, Association, High School)
![View recent photos (1)](https://user-images.githubusercontent.com/77851393/155902565-18ec47e2-2c94-44df-a05a-e64a3f2ffb34.png)

**Comment by technicalbirdVayuz** [comment]
We are changing it to Organization

> Change to Organization.

**Comment by stevekamps** [comment]
still says Association when you open their profile.  Change to Organization
![Screenshot 2022-03-09 at 7 30 11 PM](https://user-images.githubusercontent.com/77851393/157578288-fe67c8d7-eec1-44b1-8cc8-f59b33ffb568.png)

**Comment by rgnarok** [comment]
Donr

**Comment by stevekamps** [comment]
Not fixed on Testflight 4
