### ISSUE TITLE
Search filters not working 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#575]
collegexyz@mailinator.com
Volleyball11$

amygreen@mailinator.com
Volleyball11$

Android doesn't even work for searching her school position and jersey number (libero and 13)

https://user-images.githubusercontent.com/77851393/156669988-f6f9c13c-1f34-4ada-ab18-facd426bea82.MP4

**Comment by rgnarok** [comment]
@technicalbirdVayuz  i have created a user, Ron wilson
Ron10@Mailinator.com
Kush96agra@
He is associated with a club so only the file for club signed in yes worked but rest of the club related information filter didnt show any result

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please discuss the cases we discussed internally with @stevekamps & share the update.

**Comment by technicalbirdVayuz** [comment]
Fixed, Pls check 

@rgnarok
