### ISSUE TITLE
Make word email all in capitals for consistency 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#576]
Make word EMAIL all in capitals for consistency 
![Screenshot 2022-03-09 at 7 31 42 PM](https://user-images.githubusercontent.com/77851393/157578485-f5aae8c9-6fcf-49a1-8846-cb85c327d8e6.png)

**Comment by rgnarok** [comment]
Done
