### ISSUE TITLE
Profile Editing on App - Can't get out after editing.  

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#577]
Profile Editing on App - Can't get out after editing.  

Need to close app as the hamburger menu does not work

**Comment by ShikharVayuz** [comment]
@stevekamps  Please share recording or steps to reproduce the issue.

**Comment by rgnarok** [comment]
Hi @stevekamps  it is wokring file please can you check again or share a video for the same
https://drive.google.com/file/d/1D8hSpqXTXMNFEgPVKQebeexumNw9GX94/view?usp=sharing
