### ISSUE TITLE
Athlete - Premium Web - Many issues 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#578]
Athlete - Premium Web - Many issues 

As you can see on the video this athlete is premium.  She does not have the search filter available to search for Colleges.  Her wishlist has the incorrect language for an athlete.  The Premium features are coaching premium features and are not accurate

https://user-images.githubusercontent.com/77851393/158072950-5f141a4c-0efe-4e96-afaa-fba6802f88c7.mp4

**Comment by technicalbirdVayuz** [comment]
As per #552 , College Athlete does not need search filters, So irrespective of their premium or non-premium type, there will be no search filter if the athlete belongs to the college.

![image](https://user-images.githubusercontent.com/18699624/158158743-d613d292-4c15-4c13-a49f-c97bce74749c.png)

**Comment by rgnarok** [comment]
Fixed
