### ISSUE TITLE
Athlete Premium description - web & App

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#579]
Athlete Premium description - web & App

Say coach . See attached
![athletepremim](https://user-images.githubusercontent.com/77851393/158073086-53a6969d-1228-4ecd-b5f9-1c81928da82c.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/158158101-13f3b0ca-e131-45d8-b36b-150dccebda03.png)
Changed in Web also

**Comment by rgnarok** [comment]
Fixed
