### ISSUE TITLE
Coach >> Verification

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#58]
A coach can only verify from the organisation remove the option from other coaches
![image](https://user-images.githubusercontent.com/85341053/130362850-b0dd2cd5-d0bf-45b2-af26-d39856e562b1.png)

**Comment by technicalbirdVayuz** [comment]
Related with  #48. Once #48 Resolved its also resolved, So closing this
