### ISSUE TITLE
Dashboard - Sorting

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#587]
Cannot click on a column to view/sort  by user type, by state, by city etc.

**Comment by technicalbirdVayuz** [comment]
Started this, Will be completed by tomorrow

**Comment by technicalbirdVayuz** [comment]
Fixed, Pls check.

**Comment by technicalbirdVayuz** [comment]
Duplicate #592
