### ISSUE TITLE
Hyperlinks need changed on website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#588]
A few of the hyperlinks on various pages of our website need to be linked properly.  

When I click on Join now on the homepage, and then Sign in on the next page it goes to launching soon.

On the IOS app hamburger menu when you click on about us or privacy policy or contact us.....the sign  in and signup go to launching soon page.

**Comment by technicalbirdVayuz** [comment]
Please check now, new build updated on Production
