### ISSUE TITLE
Coach >> verification

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#59]
On approving the verification there is no notification to the coach 
![image](https://user-images.githubusercontent.com/85341053/130363087-3efec2d2-83a8-48a5-9ea2-586f3c3a2e5c.png)

**Comment by technicalbirdVayuz** [comment]
Have you documented notification triggers sheet?

**Comment by rgnarok** [comment]
Not yet i will create the verification cases rest notifications are same and share them with you

**Comment by technicalbirdVayuz** [comment]
Please share the notification test cases then only update issues regarding notification. Closing this for now.
