### ISSUE TITLE
Text Verification Code not coming through on signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#590]
Text Verification Code not coming through on signup

**Comment by stevekamps** [comment]
web signup.  App signup it is working

**Comment by technicalbirdVayuz** [comment]
Both of them are using same set of code, Also, checked its working fine.

Please use resend option if it does not come for some  other reason but its working fine

**Comment by stevekamps** [comment]
![phoneverfifyweb](https://user-images.githubusercontent.com/77851393/161099791-0da29d5f-f524-4e8b-8b79-f725ae10e159.png)

**Comment by stevekamps** [comment]
Code is not coming through on my number as shown in screenshot.  This is a web signup

**Comment by stevekamps** [comment]
Not working on VU server.  The code does work on the HeroK server signup

**Comment by technicalbirdVayuz** [comment]
Please check again now

**Comment by technicalbirdVayuz** [comment]
@stevekamps  Have you checked this?
