### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#592]
Currently dashboard only allows us to click on next page rather than showing 7 or 8 different pages to click through faster.

I am trying to find the coach that signed up but can't sort by coach without having to click through 1800 Colleges

**Comment by technicalbirdVayuz** [comment]
Lets have only one sorting enable at 1 time?

**Comment by stevekamps** [comment]
![fforwad](https://user-images.githubusercontent.com/77851393/164043505-45669f7c-9b5d-4b74-908f-076e26fd3791.jpg)

**Comment by technicalbirdVayuz** [comment]
> Please check, fixed
