### ISSUE TITLE
Blog Content not showing on App 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#597]
Blog Content not showing on App

**Comment by stevekamps** [comment]
When will this be fixed. 7 days now and waiting

**Comment by rohitrvayuz** [comment]
https://user-images.githubusercontent.com/78350161/162424347-c1e72405-1e04-4ff9-b105-a3db19df68b9.mp4

**Comment by stevekamps** [comment]
Push to live app. closing
