### ISSUE TITLE
LOGO for VU is not clear 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#599]
LOGO for VU is not clear.  See attached

![Screenshot 2022-03-30 at 3 33 04 PM](https://user-images.githubusercontent.com/77851393/160934856-a712dd45-c547-4998-9bd3-4837eb7c1c63.png)

**Comment by stevekamps** [comment]
![volleyba_ll-01 (2)](https://user-images.githubusercontent.com/77851393/160938655-b1f77f7f-b8e5-4b4c-9082-142b0f004d92.png)

**Comment by stevekamps** [comment]
attached a good quality one

**Comment by stevekamps** [comment]
7 days and counting.  Isn't this a 2-minute fix?  Looks terrible. Please fix

**Comment by rohitrvayuz** [comment]
The issue here is that the profile image for this user is a user avatar and the VU-Logo is the background.
I have made the changes now. You may upload your profile image as the logo and it will work fine now.

**Comment by stevekamps** [comment]
This is the Vu dashboard user. I don’t know how to upload the logo

**Comment by stevekamps** [comment]
Please get this fixed. ASAP

**Comment by stevekamps** [comment]
Wy cant we get this fixed?  It is really frustrating

**Comment by rohitrvayuz** [comment]
This has been fixed. You need to update your profile pic for the said account.

**Comment by rohitrvayuz** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 10 50 17](https://user-images.githubusercontent.com/78350161/164378354-e9e685be-71b2-4a59-8da9-fa2768a57756.png)

**Comment by rohitrvayuz** [comment]
We have uploaded it from our end.
please check in Version 1.0.9 on iOS and Android
