### ISSUE TITLE
Athlete > Feed > Not Accessible - Showing Page not Found and on clicking back  a few seconds glimpse of Feed is coming

### ISSUE THREAD

**Issue by Arushi1390** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#6]
![Screenshot (638)](https://user-images.githubusercontent.com/88670762/129685713-831fe172-e09e-4129-8b3f-845c06b610b6.png)

**Comment by technicalbirdVayuz** [comment]
Please share the user credentials.
