### ISSUE TITLE
Highschool >> Events

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#60]
On making the organisation premium the option to the event is not on the header until i click on the virtual bench also no filters are there
No option to create event
![image](https://user-images.githubusercontent.com/85341053/130363383-7e33cefe-edfb-4eb8-a331-372e4998d37b.png)
![image](https://user-images.githubusercontent.com/85341053/130363585-ac452862-d7cf-4ece-a433-e931c5acad80.png)

**Comment by technicalbirdVayuz** [comment]
Please have a discussion on this. This was not mentioned in the modules sheet which was there as a requirement scope.
