### ISSUE TITLE
Sort colleges from A-Z when searching

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#600]
Sort colleges alphabetically from A-Z when searching

Currently, all colleges are listed on App from Z-A.  Also when a search is made by an athlete the results are coming up from Z-A. 

Please change to A-Z

**Comment by technicalbirdVayuz** [comment]
Currently, the sorting is based on the Joining date & we have changed that to Name, Please check it on Heroku. 

We will push it to production on Approval. Build will be live in 15 min on Heroku

**Comment by technicalbirdVayuz** [comment]
@stevekamps  PLease close if done

**Comment by technicalbirdVayuz** [comment]
@stevekamps PLease close if done

**Comment by stevekamps** [comment]
not done on newest build 1.0.2 (6)

**Comment by technicalbirdVayuz** [comment]
Please share the creds & screen recording also if possible.

**Comment by stevekamps** [comment]
***@***.***
Volleyball11$

Search for NCAA 

The schools come up from Z-A

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/164767833-0a0f37fb-e723-44ee-bcc4-a05d6f3d81b8.MP4

**Comment by technicalbirdVayuz** [comment]
Fixed
