### ISSUE TITLE
Add Profile Logo

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#601]
We can't add a College logo to the profiles we have created. We want to manually add all 1800 logos

**Comment by technicalbirdVayuz** [comment]
Do you need a page, where you can only add a profile image?

**Comment by stevekamps** [comment]
whatever is easiest for you.  It would look a lot nice if we can go in any manually add a logo for all 1800 colleges.

**Comment by technicalbirdVayuz** [comment]
Sharing more details, let me know if this works

- In User Listing in Admin, we need to give an option of filtering by Association first 
- Once done, then similar to the active deactivate button we need to give an option to upload a profile image. on clicking admin can change the profile picture of the college he want

**Comment by stevekamps** [comment]
Yes that would work

**Comment by technicalbirdVayuz** [comment]
Started this. Will be implemented by next week

**Comment by technicalbirdVayuz** [comment]
Changes has been implemented. Please check heroku after 15 min

**Comment by stevekamps** [comment]
Thanks. Please add to app

**Comment by technicalbirdVayuz** [comment]
In-App, No changes are required

**Comment by technicalbirdVayuz** [comment]
Please review & close

**Comment by stevekamps** [comment]
Yeah however we can make this possible. I think it wlll look so much better when the colleges have a logo.
