### ISSUE TITLE
College Claim Process

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#602]
Could we please get a step buy step written response on how a college will claim their page

**Comment by rgnarok** [comment]
Step :1 On User panel we have an option to generate link, On clicking a link will be generated
Step :2 It will be used in the email which is shared by some one from VU team (Offline Mode)[not on the VU platform]
Step :3 Once it is shared, on clicking on the link, association will be redirected to a page where he has to submit the email of the head coach
Step :4 If head coach submitted email is equal to the email stored in our db, an email with the temporary password will be shared to the association
Step :5 Email/ PAssword can further be changed from the panel itself in the profile & settings respectively.
@stevekamps

**Comment by stevekamps** [comment]
Thanks
