### ISSUE TITLE
Club Claim Process

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#603]
Please provide a written step by step response on how a club can claim their page we have created for them

**Comment by rgnarok** [comment]
For club you need to send them the email.with credentials there is no claim process like college @stevekamps

**Comment by stevekamps** [comment]
What credentials? The password is unknown

**Comment by rgnarok** [comment]
The password will go on the email which is entered to create the account. But steve, you can share how you want to sent the club claim process and we can move forward with that. 
@stevekamps

**Comment by stevekamps** [comment]
The clubs were created with the club admin email and uploaded with a CSV file.  We have no way of accessing the password. 
Could a club attempt to signin with their email and then reset password?  Would this be the easiest way?

**Comment by stevekamps** [comment]
Should be same claim process as Colleges.

**Comment by technicalbirdVayuz** [comment]
This was in discussion till now. We will start it this week. Updates will be shared

**Comment by technicalbirdVayuz** [comment]
The flow has been configured on Heroku, pls check

**Comment by technicalbirdVayuz** [comment]
Also, attaching sample for CSV Upload

[Club_updated_data.csv](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8518713/Club_updated_data.csv)

**Comment by stevekamps** [comment]
Works great. Please push to VU.  One small change attached.  When it takes you to the claim URL link it should say "Club Admin Email" rather than Head Coach Email
![clubclaim](https://user-images.githubusercontent.com/77851393/164254082-96a4bd06-4769-428f-a749-198c461dbe9c.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/164381181-9d49c957-954e-4856-af91-8bbc831aea8c.png)
Done
