### ISSUE TITLE
Use this attached cover photo for all athelte and coach cover photos 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#604]
Use this attached cover photo for all athelte and coach cover photos 
![Untitled design (20) (1)](https://user-images.githubusercontent.com/77851393/161165504-2a74b16b-5e2f-4e09-81dc-15b7dd5ea699.png)

**Comment by technicalbirdVayuz** [comment]
Done on Heroku. Please check, Once checked, will move it to production

**Comment by stevekamps** [comment]
Looks great. Please push it to the VU Server and the Apps
