### ISSUE TITLE
Use this attached cover photo as the default image for Blogs

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#605]

**Comment by stevekamps** [comment]
![Blogs](https://user-images.githubusercontent.com/77851393/161165712-99b43e60-8c8e-4e29-86b8-a0712532430a.png)

**Comment by technicalbirdVayuz** [comment]
Configured on Heroku, Please check

**Comment by stevekamps** [comment]
Looks good. Please push to VU server and the Apps

**Comment by technicalbirdVayuz** [comment]
Apps does not have option to create blogs
