### ISSUE TITLE
use this attached cover photo for the defualt image for all events 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#606]
![events](https://user-images.githubusercontent.com/77851393/161165775-6229e332-7043-49d2-ad0f-8e02846c0583.png)

**Comment by technicalbirdVayuz** [comment]
Configured on Heroku, Please check

**Comment by stevekamps** [comment]
Looks good. Please push to VU Server and the Apps

**Comment by technicalbirdVayuz** [comment]
Done (last friday)
