### ISSUE TITLE
Blogs - Images won't save in the blog 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#607]
Blogs - Images won't save that you add to the actual blog

**Comment by technicalbirdVayuz** [comment]
Hi,

Please check this. Images can be changed & working fine.


Link: https://drive.google.com/file/d/1uspES7HSvDStV38ewj1hiooDYQHvTg4l/view?usp=sharing

Please share a video in case you are facing a different issue

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/161956469-ca1f3b64-3e43-4a07-93d1-f2e29b937ddf.png)
Can you attach the image you tried to add in the blog

**Comment by technicalbirdVayuz** [comment]
Image is causing the issue here, if we upload the image having size more than 50 kb then its not getting uploaded

**Comment by stevekamps** [comment]
ALmost all phone images are 200-300KB. Can we please increase the size limit to 500KB

**Comment by technicalbirdVayuz** [comment]
We need to check for this, no option is available as such.

**Comment by stevekamps** [comment]
Please fix this issue.

**Comment by technicalbirdVayuz** [comment]
The issue has been fixed on Heroku. 

Also, From feed listing, we had to remove the description from the cards

The updated card will look like this
![image](https://user-images.githubusercontent.com/18699624/163319449-c0fe30a1-f9f7-472c-ad82-c15ce7aadb47.png)

**Comment by stevekamps** [comment]
OK. Please push to volleyball unite

**Comment by stevekamps** [comment]
OK. Please push to volleyball unite

**Comment by technicalbirdVayuz** [comment]
Done
