### ISSUE TITLE
Search filter not working for athletes 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#608]
see attached video

Uploading RPReplay_Final1649183054.MP4…

**Comment by technicalbirdVayuz** [comment]
Please attach again.

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/161994487-b2962014-1a20-4b75-8d7e-d4c9d3cf71d8.MP4

**Comment by stevekamps** [comment]
Does not work on the web version either. 
In my example I search NCAA, Division 1, California........nothing shows up

**Comment by technicalbirdVayuz** [comment]
@stevekamps I  have checked the database also, there is no user that belongs to the California state. However if you search for NCAA then there are 1116 athletes returned & in case of NCAA + Division 1 total of 360 athletes returned.


Its working as expected.

**Comment by stevekamps** [comment]
I have no idea what you are talking about with athletes.?

I am referring to an athlete search. 

When an athlete searches for colleges it is not working. 

There are a whole bunch of colleges in California that are NCAA, division 1.

The search filter is not finding them when I choose: 
Ncaa
Division 1
State- California

**Comment by technicalbirdVayuz** [comment]
> @stevekamps I have checked the database also, there is no user that belongs to the California state. However if you search for NCAA then there are 1116 athletes returned & in case of NCAA + Division 1 total of 360 athletes returned.
> 
> Its working as expected.

Ok, So the Athlete keyword is wrong here. I mean colleges. Yes We both are referring to athlete search. I mean # of users returned when you applied a filter.

**Comment by technicalbirdVayuz** [comment]
The issue is, Short codes have been used while entering data from the CSV & short codes does not matches with the state we have stored.

So, either we would need to replace the short code with the full state name & add the data again or we need to configure the search as per shortcodes.

Lets go with with first one as second one will create confusion in the future

**Comment by stevekamps** [comment]
[USACollegeDatabase.April.7.2022.xlsx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/8444196/USACollegeDatabase.April.7.2022.xlsx)

**Comment by technicalbirdVayuz** [comment]
Updated On Production. Please check

![image](https://user-images.githubusercontent.com/18699624/162409577-597d05c6-fb3b-41d8-9754-1d3c5ef8be31.png)

**Comment by stevekamps** [comment]
Looks good. Please push to vu and app

**Comment by technicalbirdVayuz** [comment]
Already Done
