### ISSUE TITLE
search bar issue

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#610]
When searching for a user or an organization on the search bar the results are not showing up alphabetically by first letter, second letter, etc.

For example if I type in a C the results will show all results when a user has a C anywhere in their name. 

It should be alphabetical for first letter then second letter etc.  For example if I type in C only the users that start with C should show up.  Currently any user with a C anywhere in their name shows up

**Comment by technicalbirdVayuz** [comment]
We have made the changes on Heroku, Please check. Build will be live in 15 min

**Comment by stevekamps** [comment]
Looks good. Please push to production and the apps
