### ISSUE TITLE
Blog from dashboard format 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#612]
Each time I try to log in and ad on to a blog the format disappears from what I had before.  Take a look a the attached and you will see that all the spacing etc. I had for the blog is now gone now that I opened it.  I would like to be able to continue to add on to blogs each week nd not lose the format
![blogformat](https://user-images.githubusercontent.com/77851393/162075698-41919503-53a5-4063-a939-9760336f36a3.jpg)

**Comment by stevekamps** [comment]
![blogformat2](https://user-images.githubusercontent.com/77851393/162076734-bef07f18-1972-4ea9-b342-4f175e600f15.jpg)

**Comment by stevekamps** [comment]
NOte that all of my formatting from Tip # 1 disappears when I added Tip # 2 today

**Comment by technicalbirdVayuz** [comment]
This has been fixed. Please check on heroku

**Comment by technicalbirdVayuz** [comment]
Updated on Production also

**Comment by stevekamps** [comment]
Stop telling me to check. Make it work on volleyball unite.com

**Comment by technicalbirdVayuz** [comment]
Sorry, but as a process. Every production build has to be approved because we are also responsible for handing stuff on volleyballunite.com

Whatever the issue, we want it to be checked So that main users would not get impacted.

**Comment by stevekamps** [comment]
Approved
