### ISSUE TITLE
Event Creation from Dashboard 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#614]
No logo is showing up for the event that VU admin created from dashboard.

**Comment by technicalbirdVayuz** [comment]
Before:

![image](https://user-images.githubusercontent.com/18699624/162671864-b21b8300-d8eb-4fa9-ae13-dc54a0d81841.png)


After: (Made changes)

![image](https://user-images.githubusercontent.com/18699624/162672007-862a7c97-52d6-4e78-9076-251b1587fc64.png)
