### ISSUE TITLE
College Notifications upon signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#615]
- Use our "Share App" feature to Invite your current athletes to VU and add them to your team roster
- Use our "Share App" feature to Invite your new recruits to VU and add them to your Class of 2022 
- Update your College Profile information 
- Welcome to Volleyball Unite!! Enjoy all the features and benefits of being a part of this community.

**Comment by technicalbirdVayuz** [comment]
Update: Shared Notifications has been configured on Heroku.

@ShikharVayuz  Please check & let me know if anything required

**Comment by stevekamps** [comment]
Looks good. Please push to Vu and app

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz  Please share credentials to check on heroku.

**Comment by stevekamps** [comment]
***@***.***
Volleyball11$

**Comment by technicalbirdVayuz** [comment]
> @technicalbirdVayuz Please share credentials to check on heroku.

@ShikharVayuz Use this : dan.dresen@alverno.edu , 12345678aA@

**Comment by ShikharVayuz** [comment]
Fixed

**Comment by stevekamps** [comment]
Looks good. Please push to Vu and app

**Comment by technicalbirdVayuz** [comment]
Done
