### ISSUE TITLE
Texual Changes in Message & Association Redirection Issue

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#616]
The process works.  A couple of additional tasks:
1)  We need to have a message that pops up after they verify their email.   "User - Verified. A temporary password has been sent to your email"
2) Once they log back in let me straight into the platform without having the need for us to verify again. I have added the screen below of what I am talking about.
![approved](https://user-images.githubusercontent.com/77851393/162502704-b4d51bf0-3b84-4c3a-b7bc-469caf2aa191.jpg)

_Originally posted by @stevekamps in https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/issues/611#issuecomment-1093217314_

**Comment by technicalbirdVayuz** [comment]
Both of the changes has been done & can be checked on heroku after 15 min

**Comment by stevekamps** [comment]
Looks good. Please push to VU and App.

**Comment by technicalbirdVayuz** [comment]
Yes, will do once configured in App today

**Comment by technicalbirdVayuz** [comment]
Yes, will be done one #615 is done today

**Comment by stevekamps** [comment]
Looks good. Please push to VU and App.

**Comment by technicalbirdVayuz** [comment]
Done Please check.
