### ISSUE TITLE
Search Filters for Athletes - State Issue 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#617]
The States only include 39 States. They go up to th eletter "P".  Missing all remaining States from P-Z

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/163106861-115e6c0d-df1a-4d29-a142-efc8f30c1865.png)

**Comment by technicalbirdVayuz** [comment]
Fixed
