### ISSUE TITLE
No Logo appearing for VU posts 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#618]
No Logo appearing for VU posts - See attached
![Screenshot 2022-04-12 at 9 19 30 AM](https://user-images.githubusercontent.com/77851393/162996750-c9686d0d-6c92-471b-9ef8-09954e238a6f.png)

**Comment by ShikharVayuz** [comment]
IOS build will be updated soon.
