### ISSUE TITLE
App Availability - Stores

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#619]
Can we please have the Volleyball Unite USA app (IOS and Google Playstore) only available in the USA?  I have changed the settings in the Apple console to USA only but it is still appearing in the Canada Appstore

**Comment by rohitrvayuz** [comment]
Ok

**Comment by rohitrvayuz** [comment]
Please check in new version 1.0.9 on iOS and Android.
