### ISSUE TITLE
we lost all the users we created, the blogs, events and posts from VU admin. 

### ISSUE THREAD

**Issue by technicalbirdVayuz** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#620]
Everything is there & working, Please check & share screen recording if not working

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/164262030-fa84eeb9-6a70-4a5c-b0c3-a35d1cc41d53.MP4

**Comment by stevekamps** [comment]
The app in the Appstore does not have any of users or any of the posts, blogs, events we created. I can't even login with our users. I am not sure how the heroK and the VU servers work?  My understanding is they're the same. Clearly not the case

**Comment by stevekamps** [comment]
Not working on the current app in the appstore
