### ISSUE TITLE
Google Play Non-Compliant

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#621]
<html>
<body>

Hi Developers at Amateur Sports Unite LLC,After a recent review, we found that your app Volleyball Unite USA (com.volleyballunite.usa) is not compliant with one or more of our Developer Program Policies. See below for more information about your app's status and how to correct the issue.Status: Approved with Issues - Further Action RequiredWe found issues with your app. You need to review and take action as described below, so that your app is not impacted in the future.Issue found: Invalid Data safety sectionWe reviewed your app's Data safety section in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety section that discloses their data collection and sharing practices - this is a requirement even if your app does not collect any user data.We detected user data transmitted off device that you have not disclosed in your app's Data safety section as user data collected.Issue detailsWe found an issue in the following area(s):SPLIT_BUNDLE 2: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)About the Data safety section in Google Play User Data PolicyStarting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.Please make changes to align your app's Data safety section with the app's behavior. This can be done by either:Updating your form in Play Console to declare collection of Data Types noted below; orRemoving unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.Learn more about how to Provide app privacy and security information for Google Play's Data safety section.Action required: Submit your app for another reviewHere's what to do to help get your app on Google Play:Make sure to read the applicable policies or requirements:Data safety section in Google Play User Data PolicyMake appropriate changes to your app (if possible), and be sure to address the issue described above. You may also want to check your app's store listing for compliance, if applicable.Double check that your app is compliant with all other Developer Program Policies.If you made changes to your app bundle, store listing, or APK, please sign in to your Play Console and submit the update(s).Contact supportIf you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team. We'll get back to you within 2 business days.Learn MoreVisit the Android Developers Blog to learn more about free tools and resources for building safe and successful apps.Thanks for your continued support in helping to make Google Play a positive experience for both developers and consumers. We look forward to seeing an updated version of your app on Google Play.Please complete a two question survey to help us improve this experience. |   | Status: Approved with Issues - Further Action RequiredWe found issues with your app. You need to review and take action as described below, so that your app is not impacted in the future. |   | Issue found: Invalid Data safety sectionWe reviewed your app's Data safety section in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety section that discloses their data collection and sharing practices - this is a requirement even if your app does not collect any user data.We detected user data transmitted off device that you have not disclosed in your app's Data safety section as user data collected.Issue detailsWe found an issue in the following area(s):SPLIT_BUNDLE 2: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)About the Data safety section in Google Play User Data PolicyStarting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.Please make changes to align your app's Data safety section with the app's behavior. This can be done by either:Updating your form in Play Console to declare collection of Data Types noted below; orRemoving unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.Learn more about how to Provide app privacy and security information for Google Play's Data safety section.
-- | -- | -- | -- | --
  | Status: Approved with Issues - Further Action RequiredWe found issues with your app. You need to review and take action as described below, so that your app is not impacted in the future.
  | Issue found: Invalid Data safety sectionWe reviewed your app's Data safety section in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety section that discloses their data collection and sharing practices - this is a requirement even if your app does not collect any user data.We detected user data transmitted off device that you have not disclosed in your app's Data safety section as user data collected.Issue detailsWe found an issue in the following area(s):SPLIT_BUNDLE 2: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)About the Data safety section in Google Play User Data PolicyStarting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.Please make changes to align your app's Data safety section with the app's behavior. This can be done by either:Updating your form in Play Console to declare collection of Data Types noted below; orRemoving unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.Learn more about how to Provide app privacy and security information for Google Play's Data safety section.
The Google Play Team | The Google Play Team
The Google Play Team

</body>
</html>Hi Developers at Amateur Sports Unite LLC,
After a recent review, we found that your app Volleyball Unite USA (com.volleyballunite.usa) is not compliant with one or more of our Developer Program Policies. See below for more information about your app's status and how to correct the issue.

Publishing Status	
Status: Approved with Issues - Further Action Required
We found issues with your app. You need to review and take action as described below, so that your app is not impacted in the future.

	
Issue found: Invalid Data safety section
We reviewed your app's Data safety section in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety section that discloses their data collection and sharing practices - this is a requirement even if your app does not collect any user data.

We detected user data transmitted off device that you have not disclosed in your app's Data safety section as user data collected.

Issue details

We found an issue in the following area(s):

SPLIT_BUNDLE 2: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)
SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)
About the Data safety section in Google Play User Data Policy
Starting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.

Please make changes to align your app's Data safety section with the app's behavior. This can be done by either:

Updating your form in Play Console to declare collection of Data Types noted below; or
Removing unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.
To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.
Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.
Learn more about how to [Provide app privacy and security information for Google Play's Data safety section](https://notifications.google.com/g/p/AD-FnEwLlZ12uoreztDUnDasgEgHA-Hz_oOcw-0e80baxzciUMOV_sIxOPl-5e-7tB8euQTJ_ftyVsd3EUJeqp8ifcTap38UtKYt4v78YqH0sF47V0I-nS3p7IqS1L6Yv9jdrMH-8dFPknF2Pw).
Action required: Submit your app for another review
Here's what to do to help get your app on Google Play:
Make sure to read the applicable policies or requirements:
[Data safety section in Google Play User Data Policy](https://notifications.google.com/g/p/AD-FnEwxtMPLLzTR8KTxkGAsHhMIbiUe0F_UWeIt8D9yH7KHm87sZXnEzav1vWTVvN4UJ0k15tx-mmQnAcuezA4hYqPCA-AguuGwLox9EMsQXe8udw9ZyrIqaZ37SX5dI-mRKHAItpek6jRQ6QETISeHg7RCSGGKf6t1)
Make appropriate changes to your app (if possible), and be sure to address the issue described above. You may also want to check your app's store listing for compliance, if applicable.
Double check that your app is compliant with all other [Developer Program Policies](https://notifications.google.com/g/p/AD-FnEzZGkATKNNQcAGqXYfXjz_9p7RCnIXAVzoz2-FVIMHUd3A9qdSvg9i2RtiUgK0Y8fUz88ghe0w47-4Byb3M00C8hK075x1J8TZugdL1aOJPy3nV0LQnCOgXt0U2QA).
If you made changes to your app bundle, store listing, or APK, please sign in to your [Play Console](http://notifications.google.com/g/p/AD-FnExrsA1-d1iDhT5Gag4u6uHe1ZrGbZPrz4PD7W97rc-Nphpobr3OBHOaNjNzNQHE2ET3MY-2j1-9djjS8M4Xk-bwxtHJemJqEh80-VGJ9Y7P7Iz6xo49BGODg4vq_UUZ3IaE-o3UqXjLHPN0VCsN) and submit the update(s).
Contact support
If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://notifications.google.com/g/p/AD-FnEw_yH31UTLQqV0WOx0xF4vi67iHZFZCly2AKM4AomLhc_ek6uwdFhyBVBjAjIxSk1nrI9-9riNGXX3oM-4MoWqCIfRpl7PXbNO5fVawYoDs4Zv8Zarj3CNzle-Vi3H9f7iitRJ7vfAJKZVO37h0Lu7R582Z). We'll get back to you within 2 business days.
Learn More
Visit the [Android Developers Blog](https://notifications.google.com/g/p/AD-FnEz1m-DWVTeTfvvCYFtROJUpwSpmIGGdZ4cUw3onwHU48StdNeVspQi5Rw2GaMWwJayZl27KI4uAnAfUc-7jwSDHMOoyV3PetFPWYFo-t8CRL2h7GxuL3l73U7iI3OqW9UvKR0DayGt1j6NNoMxGmW1slUX5l-XOR_o) to learn more about free tools and resources for building safe and successful apps.

Thanks for your continued support in helping to make Google Play a positive experience for both developers and consumers. We look forward to seeing an updated version of your app on Google Play.

Please complete a [two question survey](https://notifications.google.com/g/p/AD-FnExtPNm86QDscvBtBEi4kxRMHA1qkmRECuu-p6fBP6vJUDMeL7gKjxbBeRMOdyWiYhqaNspl_Hexm5AHLOAVL5kaEpvbnV1UItHhfou8PX0hLcoVfaHKpafauF2XRzIoAyC6_fWiH2DcniZVlTwvZ_wtO0SlBSR2wR1DEYSmvmHzcGPQTDg) to help us improve this experience.

The Google Play Team

**Comment by stevekamps** [comment]
Where is this at?

**Comment by rgnarok** [comment]
@rohitrvayuz  @ShikharVayuz  please update on this

**Comment by rohitrvayuz** [comment]
still in progress by Google

**Comment by rgnarok** [comment]
@rohitrvayuz @ShikharVayuz   any update on this?

**Comment by ShikharVayuz** [comment]
@rgnarok No updates as of now from google

**Comment by stevekamps** [comment]
Where is this at?  We are going to launch this week

**Comment by rgnarok** [comment]
@ShikharVayuz @rohitrvayuz  can we have a closure on this? Let me know what is the next actionable.

**Comment by rohitrvayuz** [comment]
Though  this does not affect the current build, only updates will get affected. For that I have re-submitted the form. 


<img width="678" alt="Screenshot 2022-06-22 at 10 18 20" src="https://user-images.githubusercontent.com/78350161/174946424-dc1842cd-54ef-4233-b798-5c06203954c5.png">


> Starting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.

**Comment by rohitrvayuz** [comment]
https://play.google.com/store/apps/details?id=com.volleyballunite.usa
