### ISSUE TITLE
Version 1.0.2 (6) does not have VU profile icon for VU dashboard posts on the app 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#623]
Version 1.0.2 (6) does not have VU profile icon for VU dashboard posts on the app

**Comment by stevekamps** [comment]
![Screenshot 2022-04-20 at 9 24 47 AM](https://user-images.githubusercontent.com/77851393/164266378-366571db-14c7-451f-894c-b0569fbed3f1.png)

**Comment by technicalbirdVayuz** [comment]
Logo Updated

**Comment by rohitrvayuz** [comment]
Please check in new version 1.0.9 on iOS and Android
