### ISSUE TITLE
Change bottom background image on website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#624]
Remove the background image at bottom of all pages and replace with IMG_2231-42 in black and white.  I emailed it to Kushagra as it is too big to attach here

**Comment by technicalbirdVayuz** [comment]
@rgnarok  Please share the mail

**Comment by rgnarok** [comment]
@technicalbirdVayuz  email shared

**Comment by vayuzpriya** [comment]
https://vu-usa.herokuapp.com/ 
Please Check Here

**Comment by technicalbirdVayuz** [comment]
Updated on Production

**Comment by stevekamps** [comment]
Looks great. Please close
