### ISSUE TITLE
Change the Images on the Ipad on the homepage 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#625]
Make a new collage with the following images 
![A15U5218](https://user-images.githubusercontent.com/77851393/165100751-51008a4c-8735-473f-bc45-b259c21bc221.JPG)
![image5](https://user-images.githubusercontent.com/77851393/165100905-8a0ceee3-8c39-4b40-a613-e7b12b70e68d.jpg)
<img width="249" alt="coach" src="https://user-images.githubusercontent.com/77851393/165100999-fedd6be6-5543-41e1-aaf8-064f4b8f2cc6.png">
![WVB CBC 23](https://user-images.githubusercontent.com/77851393/165101088-cd0aa0fb-1889-4d19-a942-61c806b69a0f.jpg)
![ShaniceMarcelleCAN](https://user-images.githubusercontent.com/77851393/165101194-fbfd1199-cfb8-451c-8353-df2a6ec9a26a.jpg)

**Comment by vayuzpriya** [comment]
https://vu-usa.herokuapp.com/ Please Check here

**Comment by stevekamps** [comment]
Looks great. Yes please push to VU

**Comment by technicalbirdVayuz** [comment]
Moved to production

**Comment by stevekamps** [comment]
Thanks. Looks great
