### ISSUE TITLE
College claim email issue - #1 priority

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#626]
college claim email has some formatting issues. See attached. 

Looks like perhaps the spam filter is taking out mages or icons?  

Just leave email and temporary password as basic font 

Currently a coach cannot see the temporary password, login email 

I tested with University XYZ and it worked but I tried with a real College and this is what they saw (See attached)

**Comment by stevekamps** [comment]
![IMG_0989](https://user-images.githubusercontent.com/77851393/166869155-7e33a6bd-0cb0-43a9-a836-40e1d16001aa.jpg)

**Comment by vayuzpriya** [comment]
FIxed Pls check it on heroku. and let me know if any issue.

**Comment by stevekamps** [comment]
It was working before on my end. The screenshot was from an actual
College.  It looked like their spam filter maybe got rid of the red button
or something?  Please advise as to what has been fixed?  Did you change it
all to basic text in the middle of the email?

**Comment by vayuzpriya** [comment]
I have to change the middle part of the template. Pls have a look. 
![vu-email-tempalte](https://user-images.githubusercontent.com/81085431/167091122-1b560e50-7cdc-4ca9-be54-2bf0492c9d53.jpg)

**Comment by stevekamps** [comment]
Looks good
