### ISSUE TITLE
Chnage Events Auto email 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#628]
currently, events are using the .ca email.

Please change to events@volleyballunite.com

Password for this email is Volleyball11$

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/174979281-4bf99da3-d921-486d-a688-b9e5c7b0d714.png)
Please check the creds.

Also, this account should be a G Suite account as we required in VU Canada also

**Comment by stevekamps** [comment]
OK. we will leave this for now
