### ISSUE TITLE
Add DNS records 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#632]
Hi Guys.  We are going to be using "pipedrive" for our Client Management.  In order to send out mass email campaigns, pipedrive is asking us to add the following DNS records to our domain in order to improve email delivery. Could you please add the following DNS records to the domain that is being hosted on AWS:

CNAME           pd1._domainkey.volleyballunite.com              pd1.pdrserv.com

CNAME            pd2._domainkey.volleyballunite.com            pd2.pdrserv.com

TXT             _pdcid.volleyballunite.com            U30u24fDcP7BWV3xJ05IXhzP2v3cIye2Nj4_bSw4smIM8dM1

**Comment by technicalbirdVayuz** [comment]
This will be done from namecheap. Currently its down for [maintenance](https://www.namecheap.com/status-updates/archives/70690)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/181200050-8b82beee-7646-4461-9094-41909b882eea.png)
Added them all
