### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#633]
We would like to set up each of our pages on our website for Google Analytics. Please see tagging measurement below.  Let me know if you require anything else.

To start collecting data make sure your website is tagged using the Measurement ID: G-7K5RNW0PPM

**Comment by technicalbirdVayuz** [comment]
Hi,

This will be done by tomorrow

**Comment by technicalbirdVayuz** [comment]
Done
