### ISSUE TITLE
Change Homepage website back to Recruiting Network 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#634]
Change Homepage, About Page, Contact us Page to "North America's Premier Volleyball Recruiting Network"

**Comment by stevekamps** [comment]
![Homepagetop](https://user-images.githubusercontent.com/77851393/181415973-6c92f7ad-7010-4368-9eed-9cdef0bcb406.jpg)

**Comment by stevekamps** [comment]
remove community and add "RECRUITING NETWORK" (Both in white all capitals and network under recruiting)

**Comment by rgnarok** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/85341053/182074165-fd44813b-9512-4356-a1f9-5dfac35ab0de.png">
@vayuzpriya  on mobile vire please fix and make recruiting and network in different line
