### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#639]
please see screenshot attached.  Can't access website. Warning comes up.  HUGE priority

![Uploading IMG_2175.PNG…]()

**Comment by technicalbirdVayuz** [comment]
SSL has expired. Please renew it.

**Comment by technicalbirdVayuz** [comment]
Currently, we have configured Free SSL. Will replace it once renewed SSL is provided

**Comment by stevekamps** [comment]
I have purchased an SSL.
You login with volleyballuniteusa@gmail.com
Password is Volleyball11$

comodosslstore.com

**Comment by technicalbirdVayuz** [comment]
Hi, 

We have completed the process, please check the mail at admin@volleyballunite.com

Here you will receive the SSL Certificates

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/190103003-6723e90f-e84c-4916-bc95-07426b251e60.png)
