### ISSUE TITLE
Google API issue with Cities and States 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#640]
Please see attached.  Looks like a google API issue as some of the states are missing and the cities are not being found. 

https://user-images.githubusercontent.com/77851393/187950687-7081a9c1-e590-4c87-80a8-c211eb3f34c8.MP4

**Comment by ShikharVayuz** [comment]
@stevekamps  Please provide the creds for the same.

**Comment by stevekamps** [comment]
vuathlete@mailinator.com
Volleyball11$

**Comment by stevekamps** [comment]
Is this fixed?

**Comment by stevekamps** [comment]
This is still not working. Cities are not populating

**Comment by ShikharVayuz** [comment]
https://user-images.githubusercontent.com/86296418/190920272-0bdffe7b-9f12-40d2-a29c-95ffa680981d.mp4

**Comment by ShikharVayuz** [comment]
@stevekamps I have updated the builds now on playstore and will be live soon further will update app store as well. Meanwhile I would like to share the video record for the issue fix.

**Comment by ShikharVayuz** [comment]
https://vayuztechnologies-my.sharepoint.com/:v:/g/personal/shikhar_jain_vayuztechnologies_onmicrosoft_com/EaN2SHaEWn5DpTn3PP7hIY8BJc_lpf5JwDX9ImMaVUJZqg

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/190923344-cf55f78d-077d-4824-a5c5-980e93df5e98.mov

**Comment by stevekamps** [comment]
Not working on IOS
