### ISSUE TITLE
Please add an FAQ Page to website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#641]
Please add an FAQ Page to website .  Add it on the bottom of the webpage where the "About Us" is located.  Call it FAQ.
Just a black background and white font like the privacy policy looks like.

MOve About us to directly before Contact Us on the bottom footer.

Please see attached FAQ's
[Volleyball Unite FAQ - Final Proof.docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/9472893/Volleyball.Unite.FAQ.-.Final.Proof.docx)

**Comment by technicalbirdVayuz** [comment]
Will update you once done

**Comment by technicalbirdVayuz** [comment]
Please check this Link: https://vu-usa.herokuapp.com/faq

**Comment by stevekamps** [comment]
I love the drop down menus.  

can we please make the FAQ fonts exactly like the terms and privacy fonts?

**Comment by stevekamps** [comment]
Can we please add one more FAQ?

What is the College Wish List?

Athletes can search for College Volleyball programs across the USA by using the powerful VU search filters.  Search filters include division, conference, state, city, tuition and student population.  Athlete's can add Colleges to their "Wishlist" that meet their academic and volleyball needs.  Colleges will receive a notification when an athlete "Wishlists" their College.

**Comment by rgnarok** [comment]
@technicalbirdVayuz  please add this and make this section live as asked by steve

**Comment by stevekamps** [comment]
Please move FAQ to the far left of the footer so that it is listed first

**Comment by stevekamps** [comment]
Change the background of the FAQ's to a deep black color to match the color of the privacy policy
