### ISSUE TITLE
Make USAV# non-mandatory during signup for athletes and coaches 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#642]
Make USAV# non-mandatory during signup for athletes and coaches

**Comment by technicalbirdVayuz** [comment]
This will be done by Monday, next week

**Comment by ShikharVayuz** [comment]
Configured in mobile app for coach and athlete

**Comment by technicalbirdVayuz** [comment]
There is an NCAA number also, Are we supposed to make it non-mandatory too?

Let us know, Apart from these changes has been done on Heroku & can be checked in 15 min

Link: https://vu-usa.herokuapp.com/

**Comment by stevekamps** [comment]
Yes leave the ncaa number as non- mandatory

**Comment by rgnarok** [comment]
![Uploading image.png…]()
