### ISSUE TITLE
Reactivate the followng for signup 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#643]
Reactivate the following for signup 

For Athletes
- Under other please reactivate beach, snow, sitting, para-volley, and professional as original development 

Retired 
- Reactivate retired user

School Organization type - reactivate

**Comment by technicalbirdVayuz** [comment]
This will be done by Monday, next week

**Comment by technicalbirdVayuz** [comment]
Please check on Heroku. Build will be live after 15 min

Link:   https://vu-usa.herokuapp.com/

**Comment by rgnarok** [comment]
DONE
