### ISSUE TITLE
Add an FAQ button

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#644]
Add an FAQ button (WHite button with red font) on the website as noted in the attached image

**Comment by stevekamps** [comment]
<img width="679" alt="FAQ" src="https://user-images.githubusercontent.com/77851393/190179819-e163168f-60b3-4711-b845-c4cba461e80a.png">

**Comment by stevekamps** [comment]
Sorry we don't like the look of the button.  Please remove

**Comment by technicalbirdVayuz** [comment]
> Sorry we don't like the look of the button. Please remove

Removed
