### ISSUE TITLE
Remove the secondary email from the signup process

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#645]
Remove the secondary email from the signup process. We don't want to have kids required to enter parent/guardian email

**Comment by technicalbirdVayuz** [comment]
From Athlete only or from coaches too?

**Comment by technicalbirdVayuz** [comment]
Done

**Comment by technicalbirdVayuz** [comment]
@ShikharVayuz Please remove Emails keys from the APis while calling from the App
