### ISSUE TITLE
Edit Personal Info - Web 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#647]
Athlete editing personal info on web. It says Province instead of State.  

![IMG_5642](https://user-images.githubusercontent.com/77851393/190920356-527ead5b-891d-4af6-81a9-27a6ad10da5b.jpg)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/191498993-11490a6f-1f2a-43d2-9774-327060b124f7.png)

**Comment by technicalbirdVayuz** [comment]
Will be live in next build

**Comment by stevekamps** [comment]
ok.
