### ISSUE TITLE
New AppStore and Google Playstore Images 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#656]
Please use the following images in Google Playstore and Appstore. 

[AppScreens_VU_App_Store1665066053869 (1).zip](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/9726553/AppScreens_VU_App_Store1665066053869.1.zip)

**Comment by ShikharVayuz** [comment]
@harshvayuz  Please update on ios.

**Comment by ShikharVayuz** [comment]
- [ ] PlayStore
- [ ] AppStore

**Comment by stevekamps** [comment]
Please push latest team flight app to AppStore

**Comment by stevekamps** [comment]
Please also add new images to the appstore before submitting next build

**Comment by harshvayuz** [comment]
@stevekamps  build is push over APP store with new images.
  version (1.1.3) , build no. - 2
