### ISSUE TITLE
Crop bottom image on homepage

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#657]
Could we please have the image at the bottom of the homepage cropped to just above the ball? See attached

**Comment by stevekamps** [comment]
![homeimage](https://user-images.githubusercontent.com/77851393/194368744-c217cbc8-9944-401e-bcf6-134bab31db18.jpg)

**Comment by stevekamps** [comment]
Please get this done. 30 second job

**Comment by technicalbirdVayuz** [comment]
Please check its live
