### ISSUE TITLE
Change buttons on web and app for organizations to red buttons with white font 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#658]
Change buttons on web and app for organizations to red buttons with white font .

Currently they are black buttons on app with red fonts and on the web they are white buttons with red fonts.

Please change them all to red buttons and white fonts

![IMG_0202](https://user-images.githubusercontent.com/77851393/194404525-b7f56368-59a9-4578-b124-c420af2f468b.jpeg)
![IMG_0203](https://user-images.githubusercontent.com/77851393/194404529-c06f9795-b186-4465-b5db-728cb7182e34.jpeg)

**Comment by ShikharVayuz** [comment]
This change needs to be done only in profile or throughout the app ? @stevekamps

**Comment by stevekamps** [comment]
Consistent throughout

**Comment by stevekamps** [comment]
looks good. closing
