### ISSUE TITLE
FAQ - App & Web

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#659]
Make FAQ questions in red font and the answers in white font

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/195775088-32527af4-9d26-4967-88fc-7d5f39fe2844.png)
This is how it will look like. Please check & confirm whether we can go with it or not.

Also, Page will be live at https://vu-usa.herokuapp.com/faq

**Comment by stevekamps** [comment]
Yes looks good

**Comment by stevekamps** [comment]
please push this change to volleyballunite.com

**Comment by stevekamps** [comment]
please push to volleyballunite.com

**Comment by technicalbirdVayuz** [comment]
Its live already https://volleyballunite.com/faq
