### ISSUE TITLE
Add Canadian Provinces and Cities to signups 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#660]
Add Canada Provinces and Cities to all user signups
-Add CCAA and Usport to drop down college athlete and college coach signups
- See video for all of the above 
- https://youtu.be/K40TphovudU
-

**Comment by technicalbirdVayuz** [comment]
@rgnarok Please take this discussion forward

**Comment by stevekamps** [comment]
lets get this done. simple process

**Comment by ShikharVayuz** [comment]
@technicalbirdVayuz Have kept in my agenda for the day 11/11

**Comment by technicalbirdVayuz** [comment]
> * https://youtu.be/K40TphovudU

checked the video, Mentioning the detailed changes

- [ ] Add Canadian Provinces to the State
- [ ] Change labels from State to Province / State
- [ ] Replace College with College/University
- [ ] Add optional in brackets before in NCAA/USA #
- [ ] Add CCAA & U Sports ( Is there any change required in the form too? if we are adding these fields? Please confirm @rgnarok @stevekamps )
- [ ] Make changes in Edit Profile Pages

**Comment by technicalbirdVayuz** [comment]
> > * https://youtu.be/K40TphovudU
> 
> checked the video, Mentioning the detailed changes
> 
> * [ ]  Add Canadian Provinces to the State
> * [ ]  Change labels from State to Province / State
> * [ ]  Replace College with College/University
> * [ ]  Add optional in brackets before in NCAA/USA #
> * [ ]  Add CCAA & U Sports ( Is there any change required in the form too? if we are adding these fields? Please confirm @rgnarok @stevekamps )
> * [ ]  Make changes in Edit Profile Pages

This has been done & can be checked on Heroku. https://vu-usa.herokuapp.com/

**Comment by technicalbirdVayuz** [comment]
> * Replace College with College/University

This will break things. A suggestion would be to University in a separate dropdown. Please share confirmation

**Comment by technicalbirdVayuz** [comment]
> * [ ]  Replace College with College/University
> * [ ]  Add CCAA & U Sports ( Is there any change required in the form too? if we are adding these fields? Please confirm @rgnarok @stevekamps )

**Comment by rgnarok** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/85341053/201328722-4cd640ca-a93a-41f6-99c9-0efb0f55b94a.png">
@technicalbirdVayuz  i have tried but cities are not coming up please check as a sugesstion

**Comment by technicalbirdVayuz** [comment]
> <img alt="image" width="853" src="https://user-images.githubusercontent.com/85341053/201328722-4cd640ca-a93a-41f6-99c9-0efb0f55b94a.png">
> 
> @technicalbirdVayuz i have tried but cities are not coming up please check as a sugesstion

Ok. please check it again.

**Comment by ShikharVayuz** [comment]
> checked the video, Mentioning the detailed changes
> 
> * [x]  Add Canadian Provinces to the State
> * [x]  Change labels from State to Province / State
> * [ ]  Replace College with College/University
> * [x]  Add optional in brackets before in NCAA/USA #
> * [ ]  Add CCAA & U Sports ( Is there any change required in the form too? if we are adding these fields? Please confirm @rgnarok @stevekamps )
> * [x]  Make changes in Edit Profile Pages

@technicalbirdVayuz @rgnarok Have done the same changes in App as well.

**Comment by rgnarok** [comment]
@technicalbirdVayuz  fixed at my end 
@stevekamps  please check so that we can move forward with making it live

**Comment by stevekamps** [comment]
Provinces and Cities all look great.  Please add CCAA and USport to the drop-down  menu for College coach and College athlete. See attachment

**Comment by stevekamps** [comment]
![coachprofile](https://user-images.githubusercontent.com/77851393/202301129-1ebbdf9d-2a9d-497c-8546-15298b24be80.jpg)

**Comment by technicalbirdVayuz** [comment]
> College athlete.

For college athletes, the league is not currently there in the form we have. Can you share the reference screenshot for this?

**Comment by technicalbirdVayuz** [comment]
> Please add CCAA and USport to the drop-down menu for College coach

This will be live in today's build
