### ISSUE TITLE
In App prices do not reflect what we have in the dashboard

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#661]
In App prices do not reflect what we have in the dashboard.  How does this work if we change things in the future?  Does the dashboard/web prices get updated on the App automatically?  Or is this a separate thing that needs completed?

![paidapp](https://user-images.githubusercontent.com/77851393/198113632-ef876780-d005-4397-bb59-f593be60f832.jpg)

**Comment by stevekamps** [comment]
![dashboardpayments](https://user-images.githubusercontent.com/77851393/198113840-f3a14cc1-fe6e-44a0-b0d1-8737ca1a2516.png)

**Comment by rohitrvayuz** [comment]
@stevekamps You update the price manually form the App Store.

**Comment by rohitrvayuz** [comment]
Goto 

1. https://appstoreconnect.apple.com/
2. My Apps
3. Select the App
4. Then select In-App Purchases
5. Then change the price through Price Schedule

<img width="1440" alt="Screenshot 2022-10-28 at 16 50 20" src="https://user-images.githubusercontent.com/78350161/198575697-5829cd91-fef7-4365-9438-2734d4283fcb.png">
<img width="1440" alt="Screenshot 2022-10-28 at 16 52 41" src="https://user-images.githubusercontent.com/78350161/198575764-ce7b1874-d301-4aa1-a6b2-9af43a50b612.png">
