### ISSUE TITLE
Clear database 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#662]
Please clear the entire USA dashboard of users except for the following users:
1) VU Athlete
2) VU Coach
3) Katelyn Cochran
4) Kale Cochran
5) University xyz
6) VU Club

**Comment by technicalbirdVayuz** [comment]
We have iniitated the process, all users expect mentioned will be deleted by 9 PM IST

**Comment by technicalbirdVayuz** [comment]
today
