### ISSUE TITLE
Add Sort Arrows in Dashboard 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#663]
Add Sort arrows for all columns in the dashboard so we can sort by name, city, state, email, and user type. Currently only user type and created has the sort arrow.

**Comment by technicalbirdVayuz** [comment]
State / City already have it. Also, at a time only one sorting is active, Please check & confirm

Name Email needs to be added

**Comment by technicalbirdVayuz** [comment]
Added, Please check it on Heroku
