### ISSUE TITLE
Add a Column to dashboard called "League"

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#665]
For Colleges, College Coaches, and College athletes it should list as one of the following in the dashboard:
- NCAA
- NAIA
- JUCO
- USport
- CCAA

FOr athletes and coaches and Associations nothing will show up in this column

**Comment by technicalbirdVayuz** [comment]
Changes done, will be live in the upcoming build on Heroku

**Comment by stevekamps** [comment]
ok push to volleyball unite

**Comment by technicalbirdVayuz** [comment]
Done
