### ISSUE TITLE
Query Email - Spelling Error

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#666]
Please fix the spelling error in the query auto repond email. 
It has an extra i in Admin. See attached
![queryemail](https://user-images.githubusercontent.com/77851393/202307142-77eb4633-f234-452e-9c7a-6a4e03886c85.jpg)

**Comment by technicalbirdVayuz** [comment]
Fixed, will be corrected in the upcoming build
