### ISSUE TITLE
Homepage >> Contact us

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#67]
Contact Us - Please make background image the same as the About us page.  It is cutting off heads on the contact us page and is also too bright which makes font difficult to read
Contact Us -The signup and join now need to be directed to coming soon page

**Comment by technicalbirdVayuz** [comment]
Contact Us -The signup and join now need to be directed to coming soon page (FIXED)

Contact Us - Please make background image the same as the About us page. It is cutting off heads on the contact us page and is also too bright which makes font difficult to read

**Comment by vayuzpriya** [comment]
@rgnarok  @technicalbirdVayuz  Issue Solved

**Comment by vayuzpriya** [comment]
@technicalbirdVayuz   I do have not any access to the change label.

**Comment by technicalbirdVayuz** [comment]
Invite shared again
