### ISSUE TITLE
Live >> Admin

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#68]
Cant access the admin on live server
![Uploading image.png…]()

**Comment by technicalbirdVayuz** [comment]
Image not updated, Pls cross check

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/130601228-83b28c29-5443-49dc-88ba-a813b881f782.png)

**Comment by technicalbirdVayuz** [comment]
http://volleyballunite.com/admin-signin Use this
