### ISSUE TITLE
Admin >> University access

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#69]
How to access the university account -

We will link the account with the head coach email which we are entering in the sheet
In case the college need to claim their account they will be shared with the email where they need to confirm by sharing the head coach email
They will share with a temporary password to log in and in the profile, they can update their official email and password through which they can operate

**Comment by technicalbirdVayuz** [comment]
Time will be shared, once we are done with the pointers

**Comment by technicalbirdVayuz** [comment]
As DIscussed Sharing the flow,
- On User panel we have an option to generate link, On clicking a link will be generated
- It will be used in the email which is shared by some one from VU team (Offline Mode)[not on the  VU platform]
- Once it is shared, on clicking on the link, association will be redirected to a page where he has to submit the email of the head coach
- If head coach submitted email is equal to the email stored in our db, an email with the temporary password will be shared to the association
- Email/ PAssword can further be changed from the panel itself in the profile & settings respectively.

@rgnarok Please confirm, will share the time on confirmation

**Comment by rgnarok** [comment]
Please do share the sign-in link for it also where they only need to add a password once the user has been confirmed by adding head coach email
Rest is fine

**Comment by technicalbirdVayuz** [comment]
Sign in link will be shared after step 4

**Comment by technicalbirdVayuz** [comment]
Time added

**Comment by technicalbirdVayuz** [comment]
Pls review

**Comment by technicalbirdVayuz** [comment]
@rgnarok  Please update the screenshot or share update

**Comment by rgnarok** [comment]
https://vu-usa.herokuapp.com/verify-head-coach/VVNFUl8xNjMxMzY4NzQzNTk5
On clicking on this link which i get from the admin it is taking me to homepage not to the head coach verification to move forward to verify college

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by rgnarok** [comment]
@stevekamps  here is the recoding to claim the college page https://drive.google.com/file/d/1til5UWBX9OMchDlzs7EzjVChW1bJqvcd/view?usp=sharing
