### ISSUE TITLE
User registeration >> Select user

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#7]
Change institution to colleges
![image](https://user-images.githubusercontent.com/85341053/129686698-1aa3f2bd-b692-4008-9e76-a5d6923aa04e.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/129877598-0182ad05-5fad-4bff-a5e7-5169887b93ad.png)
Pls close if no issues is there now!

**Comment by technicalbirdVayuz** [comment]
Closing this, Open in case of any change required

**Comment by rgnarok** [comment]
I asked to change the institution to college, not all the things correct it to "Organisation / College / Club / Highschool"

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/130733465-d6f488f5-0018-4140-9b67-c4ae58698ace.png)
Ok, Pls check now
