### ISSUE TITLE
Organisation >> State/Regional >> Premium features

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#76]
Incorrect payment details are there and also no option to access the search filter and events with or without the premium 
![image](https://user-images.githubusercontent.com/85341053/130366306-97aaf6b5-da75-4e61-9304-e0e5d4766e2e.png)

**Comment by technicalbirdVayuz** [comment]
#71 Similar issue
