### ISSUE TITLE
Homepage >> Live >> Safari mobile view

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#81]
Please see attached video. As you can see the footer is not showing

https://user-images.githubusercontent.com/85341053/130822643-7859ecea-4224-407a-97d4-b3e70eb55894.MP4

**Comment by vayuzpriya** [comment]
@rgnarok @technicalbirdVayuz this issue is already solved. 
Please check on Heroku and make code Live

**Comment by technicalbirdVayuz** [comment]
Code is live now
