### ISSUE TITLE
Highschool >> Profile

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#84]
![image](https://user-images.githubusercontent.com/85341053/131278716-1c04730e-4a4a-4af9-927b-496f9a964910.png)

- Athletic director name, email and phone number not coming up
- URL not getting updated
- Emails for sign up not getting updated
- Correct the text from state/regionalto Highschool

**Comment by rgnarok** [comment]
highschool10@mailinator.com
Kush96agra@

**Comment by technicalbirdVayuz** [comment]
- Athletic director name, email, and phone number not coming up - Done
- Correct the text from state/regional to Highschool - Done
- URL not getting updated (Fixed)
- Emails for sign-up not getting updated - There is no email. For Edit Profile, the complete page needs to be changed

**Comment by technicalbirdVayuz** [comment]
Mentioned here #87
