### ISSUE TITLE
Setting >> Subscription details 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#85]
fix the UI the details are not coming up properly
![image](https://user-images.githubusercontent.com/85341053/131340794-39d6ffdb-f94e-4194-8871-42f9f690f050.png)

**Comment by vayuzpriya** [comment]
Pls share the creds @rgnarok

**Comment by technicalbirdVayuz** [comment]
@vayuzpriya Is it done?

**Comment by vayuzpriya** [comment]
Fixed and reviewed by kushagra
