### ISSUE TITLE
Coach Sign up >> Coaching profile 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#9]
This will also have an option as Others,
Change school to high school
![image](https://user-images.githubusercontent.com/85341053/129687836-b76dcc1d-7610-4d84-9f74-51b93b77d678.png)

**Comment by technicalbirdVayuz** [comment]
School renamed to High School But for Others options, please create a new thread. AS this would going to impact the logic for premium also.
