### ISSUE TITLE
Organisation >> Event >>Create

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#90]
Event not getting created
![image](https://user-images.githubusercontent.com/85341053/131378794-8b1a7006-ad34-48ef-9261-5db9b54a77f4.png)

**Comment by technicalbirdVayuz** [comment]
Please crosscheck, I checked with disabling the location. Its working fine.

Pls share the test case in case issue persists
