### ISSUE TITLE
Retired >>Sign up >> Athlete 

### ISSUE THREAD

**Issue by rgnarok** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#98]
![image](https://user-images.githubusercontent.com/85341053/131567227-e83d6569-80d9-48d8-b2dc-fc07ce89c32e.png)
Change university to college

**Comment by technicalbirdVayuz** [comment]
Fixed for Retired

**Comment by technicalbirdVayuz** [comment]
Reverted back

**Comment by rgnarok** [comment]
@technicalbirdVayuz  Confirmedwith the client it will go for all the platform change universities to colleges

**Comment by technicalbirdVayuz** [comment]
Fixed, Please check
